syntax = "proto3";

package aimrt.protocols.viz_web;

message RpcIndexInfoRequest {
}

message RpcIndexStaticInfoResponse {
}

message RpcIndexDynamicInfoResponse {
  message RpcDynamicInfoMeta {
    string func_name = 1;
    uint32 client_count = 2;
    uint32 server_count = 3;
    repeated string backend_name = 4;
    repeated string filter_name = 5;
    float client_qps = 6;
    float server_qps = 7;
  }
  repeated RpcDynamicInfoMeta dynamic_info_meta = 1;
}

message RpcIndexInfoResponse {
  RpcIndexStaticInfoResponse rpc_index_static_info = 1;
  RpcIndexDynamicInfoResponse rpc_index_dynamic_info = 2;
}