package(
    default_visibility = ["//visibility:public"],
)

exports_files([
    "box.proto",
    "common.proto",
    "control_source.proto",
    "header.proto",
    "image.proto",
    "io_packet.proto",
    "joint.proto",
    "mocapjointstate.proto",
    "odometry.proto",
    "pixel_pose.proto",
    "qr_pose.proto",
    "quaternion.proto",
    "rpc.proto",
    "rpy.proto",
    "scalar_trajectory.proto",
    "se2_acceleration.proto",
    "se2_pose.proto",
    "se2_velocity.proto",
    "se3_acceleration.proto",
    "se3_pose.proto",
    "se3_trajectory.proto",
    "se3_velocity.proto",
    "timestamp.proto",
    "twist.proto",
    "vec2.proto",
    "vec3.proto",
    "wrench.proto",
    
])