# @package _global_
defaults:
  - /task/go2w_joystick_flat/base
  - _self_

training:
  task_name: Go2WJoystickFlat
  sim_backend: drake

algo:
  num_envs: 1024
  max_iterations: 151
  empirical_normalization: true
  obs_groups:
    actor:
      - actor
    critic:
      - critic
  policy:
    init_noise_std: 0.5
  algorithm:
    learning_rate: 3.0e-4
    entropy_coef: 1.0e-3

env:
  drake_backend_mode: batch
  drake_nthread: 0
