package(
    default_visibility = ["//visibility:public"],
)

exports_files([
    "agi_claw.proto",
    "agi_hand.proto",
    "hal_hand_service.proto",
    "hand_channel.proto",
    "hand.proto",
    "inspire.proto",
    "jodell.proto",
    "agi_o10_hand.proto"
])
