package(
    default_visibility = ["//visibility:public"],
)

exports_files([
    "jaka_ctrl.proto",
    "mc_base_channel.proto",
    "mc_base_service.proto",
    "mc_state.proto",
    "work_mode.proto",
])
