package(
    default_visibility = ["//visibility:public"],
)

exports_files([
    "foot_kine.proto",
    "kine_forward.proto",
    "kine_inverse.proto",
    "mc_kinematics_channel.proto",
    "mc_kinematics_service.proto",
])
