"""Robot package metadata and persistence shared by import entry points."""

from __future__ import annotations

import tempfile
from pathlib import Path
from typing import Any, Iterable

from backend.jsonio import write_json
from backend.model_validation import validate_model
from backend.paths import api_path, packages_root as workspace_packages_root
from backend.robot_packages import upsert_package
from contracts.validator import package_digest


_PACKAGE_COPY_SKIP_DIRS = frozenset({".git", "__pycache__", ".venv", "node_modules", ".idea", ".vscode"})
_PACKAGE_COPY_MAX_FILES = 2000
_PACKAGE_COPY_MAX_BYTES = 512 * 1024 * 1024
_MODEL_SUFFIXES = (".urdf", ".xml", ".mjcf")


_GENERIC_OBSERVATION = ["base_lin_vel", "base_ang_vel", "projected_gravity", "joint_pos", "joint_vel", "last_action"]


def _observation_dimension(components: list[str], *, dof: int, wheels: int) -> int | None:
    """按 `contract_migration` 的宽度白名单算总宽；有定不了宽的项就返回 None。

    导入契约的 `observation.dimension` 必须等于 Σwidth——`build_observation` 一见不等就整体留空
    （`widths-need-review`），所以宽度只能从同一张白名单派生，不能手写 9 + 3n。
    """
    from backend.contract_migration import JOINT_COMPONENTS, WIDTH_3

    total = 0
    for name in components:
        if name in WIDTH_3:
            total += 3
        elif name in JOINT_COMPONENTS:
            total += wheels if name.startswith("wheel_") else dof
        else:
            return None
    return total


def draft_model_contract(model_path: Path, model_format: str, inspection: dict[str, Any], digest: str) -> dict[str, Any]:
    from backend.family_readiness import family_observation_components, judge_family

    joints = inspection.get("joints", [])
    joint_names = [item.get("name") for item in joints if item.get("name")]
    actuated = [item for item in joints if item.get("type") not in {"fixed", "floating", "planar"}]
    actuated_names = [item.get("name") for item in actuated if item.get("name")]
    if model_format == "mjcf":
        targets = inspection.get("actuators", {}).get("targets", [])
        actuated_names = [name for name in targets if name in joint_names]
        if not actuated_names:
            actuated_names = joint_names
    wheel = any("wheel" in name.lower() for name in joint_names)
    robot_name = inspection.get("root_name") or model_path.stem
    robot_id = "imported_" + "".join(char.lower() if char.isalnum() else "_" for char in model_path.stem).strip("_")
    robot_id = robot_id[:48] or "imported_robot"
    mass = inspection.get("inertial", {}).get("total_mass_kg")
    # 判族**以族注册表为准**（腿数 / 角色别名 / 各腿顺序 / 形态 id 全对账）；判出族就按**族观测骨架**
    # 落观测段——否则导入的同族新机型从第一天起就与族内其它机型不同构，"同族复用同一套技能"落不了地。
    # 判不出族的（跨形态或命名不在词汇表内）保留通用骨架，导入照常成功，只是不假装是族成员。
    judgement = judge_family(actuated_names)
    components = list(_GENERIC_OBSERVATION)
    if judgement.get("family"):
        family_components = family_observation_components(str(judgement["family"]))
        if family_components:
            components = family_components
    wheels = sum(1 for name in actuated_names if "wheel" in name.lower())
    dimension = _observation_dimension(components, dof=len(actuated_names), wheels=wheels)
    return {
        "schema_version": "robot-contract-2.0",
        "contract_id": f"{robot_id}_contract_v1",
        "robot_id": robot_id,
        "family": str(robot_name),
        "size_class": "M",
        "locomotion_type": "W" if wheel else "P",
        "urdf": {"path": str(model_path).replace("\\", "/"), "hash": digest, "total_mass_kg": float(mass or 0.0), "mass_source": "mjcf_compiled" if model_format == "mjcf" else "urdf_inertial", "mesh_files": inspection.get("mesh_files", [])},
        "joints": {"actuated_joints": actuated_names, "passive_joints": [name for name in joint_names if name not in actuated_names], "default_pose": [0.0] * len(actuated_names)},
        "observation": {"dimension": dimension if dimension else max(1, 9 + len(actuated_names) * 3), "components": components},
        "action": {"dimension": len(actuated_names), "joint_order": actuated_names, "action_scale": 0.25},
        "control": {"control_hz": 50, "physics_hz": 1000, "decimation": 20},
        "description": "Imported robot asset draft generated by Legged Studio validation.",
        "tags": ["imported", model_format],
        "source": "legged_studio_asset_import",
        "min_mjlab_version": "1.6.0",
        "python_version": "3.12",
        # 判族结论（谁判的、依据什么）——**消费方必须在落盘前 pop 掉**：契约文件只放 schema 字段，
        # 结论只进导入报告（`import_staged_package` / `_preview_staged_package` 两处都这么做）。
        "family_judgement": judgement,
    }


def prepare_model_package(
    *,
    model_relative: Path,
    model_format: str,
    validation: dict[str, Any],
    content_hash: str,
    packages_root: Path,
    conversion_note: str = "",
) -> tuple[Path, dict[str, Any], dict[str, Any]]:
    contract = draft_model_contract(
        model_relative, validation.get("format", model_format),
        validation.get("inspection", {}), validation.get("sha256", ""),
    )
    if conversion_note:
        contract["description"] = (contract.get("description", "") + "；" + conversion_note).strip("；")
        contract.setdefault("tags", []).append("urdf-converted")
    package_id = f"{contract['robot_id']}_{content_hash[:10]}"
    package_root = packages_root / package_id
    contract.update({"robot_id": package_id, "contract_id": f"{package_id}_contract_v1"})
    contract["urdf"]["path"] = api_path(package_root / model_relative)
    descriptor = {
        "schema_version": "robot-package-1.0",
        "package_id": package_id,
        "task_kind": "generic",
        "native_task_id": None,
        "extension_root": None,
        "capabilities": ["generic_mjlab"],
        "model": {"format": model_format, "path": model_relative.as_posix(), "assets_path": model_relative.parent.as_posix()},
        "contract_path": "contract_legacy_v2.json",
        "content_sha256": content_hash,
    }
    return package_root, contract, descriptor


def persist_model_package(
    staging: Path, package_root: Path, contract: dict[str, Any], descriptor: dict[str, Any],
) -> dict[str, Any]:
    if not package_root.exists():
        write_json(staging / "contract_legacy_v2.json", contract)
        write_json(staging / "robot_package.json", descriptor)
        staging.rename(package_root)

    contract_note = None
    if not (package_root / "contract.json").exists():
        try:
            from backend.contract_migration import migrate_contract_dict

            draft = migrate_contract_dict(contract, None, generic_defaults=True)
            write_json(package_root / "contract.json", draft)
            contract_note = "generated（通用执行器默认值，训练前请校准）"
        except Exception as exc:
            contract_note = f"skipped: {exc}"

    upsert_package(package_root, source="workspace")
    return {"generated": contract_note is not None and contract_note.startswith("generated"), "note": contract_note}


def safe_import_relative_path(value: str) -> Path:
    normalized = value.replace("\\", "/").lstrip("/")
    candidate = Path(normalized)
    if not normalized or candidate.is_absolute() or ".." in candidate.parts:
        raise ValueError(f"invalid asset path: {value}")
    return candidate


def _list_package_tree(source_dir: Path) -> tuple[list[Path], list[str]]:
    files: list[Path] = []
    skipped: list[str] = []
    for child in sorted(source_dir.rglob("*")):
        if child.is_dir():
            if child.name in _PACKAGE_COPY_SKIP_DIRS:
                skipped.append(child.relative_to(source_dir).as_posix())
            continue
        if any(part in _PACKAGE_COPY_SKIP_DIRS for part in child.relative_to(source_dir).parts):
            continue
        if child.is_file():
            files.append(child.relative_to(source_dir))
    return files, skipped


def _stage_package_tree(source_dir: Path, staging: Path) -> dict[str, Any]:
    relative_files, skipped = _list_package_tree(source_dir)
    if not relative_files:
        raise ValueError(f"目录里没有文件: {source_dir}")
    if len(relative_files) > _PACKAGE_COPY_MAX_FILES:
        raise ValueError(f"目录文件数 {len(relative_files)} 超过上限 {_PACKAGE_COPY_MAX_FILES}（疑似指错了目录）")

    total_bytes = 0
    staged: list[tuple[Path, bytes]] = []
    for relative in relative_files:
        safe = safe_import_relative_path(relative.as_posix())
        data = (source_dir / relative).read_bytes()
        total_bytes += len(data)
        if total_bytes > _PACKAGE_COPY_MAX_BYTES:
            raise ValueError(f"目录体积超过上限 {_PACKAGE_COPY_MAX_BYTES // (1024 * 1024)} MB（疑似指错了目录）")
        target = staging / safe
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(data)
        staged.append((safe, data))
    return {"staged": staged, "skipped_dirs": skipped, "total_bytes": total_bytes}


def _pick_model_file(files: Iterable[Path], explicit: str | None = None) -> Path:
    if explicit:
        candidate = safe_import_relative_path(explicit)
        if candidate not in set(files):
            raise ValueError(f"指定的模型文件不在目录里: {explicit}")
        return candidate
    models = [item for item in files if item.suffix.lower() in _MODEL_SUFFIXES]
    if not models:
        raise ValueError("目录里找不到 URDF/MJCF 模型文件（后缀 .urdf/.xml/.mjcf）")
    if len(models) > 1:
        listed = ", ".join(item.as_posix() for item in sorted(models)[:12])
        raise ValueError(f"目录里有 {len(models)} 个候选模型文件，请用 --model 指定：{listed}")
    return models[0]



def _convert_urdf_to_mjcf(staged_model: Path) -> tuple[Path | None, str]:
    """URDF → MJCF（训练用模型）。返回 `(转换后的相对路径, 说明)`；转不了就 `(None, 原因)`。

    为什么在导入侧转：通用训练路径只吃 MJCF（`build_generic_task` 明确拒绝 URDF），
    而这台机器人的"训练模型"在契约里就是 `urdf.path` 指向的那份文件——8 台内置机型的
    `urdf.path` 也都是 `model/robot.xml`（MJCF）。转换用 MuJoCo 自己的 URDF 解析
    （`MjSpec.from_file`），**不改任何物理量**；转出来的文件与源 URDF 同目录，源文件原样保留。
    """
    try:
        import mujoco

        spec = mujoco.MjSpec.from_file(str(staged_model))
        spec.compile()  # `to_file` 只接受编译过的 spec
        target = staged_model.with_suffix(".xml")
        spec.to_file(str(target))
        return target, f"由 {staged_model.name} 自动转换为 {target.name}（MuJoCo MjSpec，物理量未改）"
    except Exception as exc:  # noqa: BLE001 — 转不了就如实回原因，导入本身照常（资产仍是 URDF）
        return None, f"URDF 自动转换失败（{type(exc).__name__}: {exc}）；导入按 URDF 原样继续"


def _effective_model(
    staging: Path, model_relative: Path, model_format: str, validation: dict[str, Any],
) -> tuple[Path, str, dict[str, Any], str]:
    """确定**训练用模型**（URDF 会被转成 MJCF 并重新校验）。写盘与预览共用这一份判据。"""

    if model_format != "urdf" or not validation.get("valid"):
        return model_relative, model_format, validation, ""
    converted, note = _convert_urdf_to_mjcf(staging / model_relative)
    if converted is None:
        # 转换没成：按 URDF 原样继续，原因进 warnings；**不返回 conversion note**
        # （返回它会让契约被标成 urdf-converted——"没转"不许看起来像"转过了"）。
        validation.setdefault("warnings", []).append(note)
        return model_relative, model_format, validation, ""
    converted_rel = converted.relative_to(staging)
    converted_validation = validate_model(
        path=str(converted), filename=converted.name, model_format="mjcf")
    converted_validation.setdefault("warnings", []).insert(0, note)
    return converted_rel, "mjcf", converted_validation, note


def import_staged_package(
    staging: Path, *, model_relative: Path, model_format: str,
    content_hash: str, packages_root: Path,
) -> dict[str, Any]:
    staged_model = staging / model_relative
    validation = validate_model(path=str(staged_model), filename=staged_model.name, model_format=model_format)
    if not validation.get("valid"):
        validation.update({"imported": False, "import_root": None, "model_path": None})
        return validation
    model_relative, model_format, validation, conversion_note = _effective_model(
        staging, model_relative, model_format, validation)

    package_root, contract, descriptor = prepare_model_package(
        model_relative=model_relative, model_format=model_format,
        validation=validation, content_hash=content_hash, packages_root=packages_root,
    )

    # 判族结论不落进契约文件（契约只放 schema 字段），只回给调用方进报告。
    family_judgement = contract.pop("family_judgement", None)
    contract_status = persist_model_package(staging, package_root, contract, descriptor)
    validation.update({
        "imported": True,
        "package_id": contract["robot_id"],
        "import_root": api_path(package_root),
        "package_root": api_path(package_root),
        "model_path": contract["urdf"]["path"],
        "contract_draft": contract,
        "contract": contract_status,
        "family_judgement": family_judgement,
    })
    return validation


def _preview_staged_package(
    staging: Path, *, model_relative: Path, model_format: str,
    content_hash: str, packages_root: Path,
) -> dict[str, Any]:
    staged_model = staging / model_relative
    validation = validate_model(path=str(staged_model), filename=staged_model.name, model_format=model_format)
    model_relative, model_format, validation, conversion_note = _effective_model(
        staging, model_relative, model_format, validation)
    preview: dict[str, Any] = {
        "preview": True,
        "valid": bool(validation.get("valid")),
        "format": validation.get("format", model_format),
        "errors": list(validation.get("errors") or []),
        "warnings": list(validation.get("warnings") or []),
        "stats": validation.get("stats"),
        "sha256": validation.get("sha256"),
    }
    if conversion_note:
        preview["conversion"] = conversion_note
    if not validation.get("valid"):
        return preview
    package_root, contract, _ = prepare_model_package(
        model_relative=model_relative, model_format=model_format,
        validation=validation, content_hash=content_hash, packages_root=packages_root,
        conversion_note=conversion_note,
    )
    family_judgement = contract.pop("family_judgement", None)
    preview.update({
        "package_id": contract["robot_id"],
        "package_root": api_path(package_root),
        "content_sha256": content_hash,
        "contract_draft": contract,
        "family_judgement": family_judgement,
    })
    try:
        from backend.contract_migration import migrate_contract_dict

        preview["contract_preview"] = migrate_contract_dict(contract, None, generic_defaults=True)
    except Exception as exc:
        preview["contract_preview"] = None
        preview["warnings"].append(f"contract_truth 预览生成失败: {exc}")
    return preview


def onboard_package(
    source_dir: Path | str, *, write: bool = False,
    model_filename: str | None = None, model_format: str = "auto",
    packages_root: Path | None = None,
) -> dict[str, Any]:
    """检查整个模型目录，默认预演；显式 write 才持久化并登记包。"""
    source_dir = Path(source_dir).expanduser().resolve()
    if not source_dir.is_dir():
        raise ValueError(f"目录不存在: {source_dir}")
    packages_root = Path(packages_root) if packages_root else workspace_packages_root()
    packages_root.mkdir(parents=True, exist_ok=True)
    prefix = ".staging-" if write else ".staging-preview-"
    # 校验只接受项目或工作区内路径，因此临时目录也必须位于工作区。
    with tempfile.TemporaryDirectory(prefix=prefix, dir=packages_root) as staging_value:
        staging = Path(staging_value)
        staged = _stage_package_tree(source_dir, staging)
        files = [relative for relative, _data in staged["staged"]]
        model_relative = _pick_model_file(files, model_filename)
        resolved_format = model_format if model_format != "auto" else ("urdf" if model_relative.suffix.lower() == ".urdf" else "mjcf")
        runner = import_staged_package if write else _preview_staged_package
        result = runner(
            staging, model_relative=model_relative, model_format=resolved_format,
            content_hash=package_digest(staged["staged"]), packages_root=packages_root,
        )
        result.update({
            "source_dir": str(source_dir),
            "model_file": model_relative.as_posix(),
            "file_count": len(files),
            "staged_bytes": staged["total_bytes"],
            "skipped_dirs": staged["skipped_dirs"],
        })
        return result
