"""Robot package metadata and persistence shared by import entry points."""

from __future__ import annotations

from pathlib import Path
from typing import Any

from backend.jsonio import write_json
from backend.paths import api_path
from backend.robot_packages import upsert_package


def draft_model_contract(model_path: Path, model_format: str, inspection: dict[str, Any], digest: str) -> dict[str, Any]:
    joints = inspection.get("joints", [])
    joint_names = [item.get("name") for item in joints if item.get("name")]
    actuated = [item for item in joints if item.get("type") not in {"fixed", "floating", "planar"}]
    actuated_names = [item.get("name") for item in actuated if item.get("name")]
    if model_format == "mjcf":
        targets = inspection.get("actuators", {}).get("targets", [])
        actuated_names = [name for name in targets if name in joint_names]
        if not actuated_names:
            actuated_names = joint_names
    wheel = any("wheel" in name.lower() for name in joint_names)
    robot_name = inspection.get("root_name") or model_path.stem
    robot_id = "imported_" + "".join(char.lower() if char.isalnum() else "_" for char in model_path.stem).strip("_")
    robot_id = robot_id[:48] or "imported_robot"
    mass = inspection.get("inertial", {}).get("total_mass_kg")
    return {
        "schema_version": "robot-contract-2.0",
        "contract_id": f"{robot_id}_contract_v1",
        "robot_id": robot_id,
        "family": str(robot_name),
        "size_class": "M",
        "locomotion_type": "W" if wheel else "P",
        "urdf": {"path": str(model_path).replace("\\", "/"), "hash": digest, "total_mass_kg": float(mass or 0.0), "mass_source": "urdf_inertial", "mesh_files": inspection.get("mesh_files", [])},
        "joints": {"actuated_joints": actuated_names, "passive_joints": [name for name in joint_names if name not in actuated_names], "default_pose": [0.0] * len(actuated_names)},
        "observation": {"dimension": max(1, 9 + len(actuated_names) * 3), "components": ["base_lin_vel", "base_ang_vel", "projected_gravity", "joint_pos", "joint_vel", "last_action"]},
        "action": {"dimension": len(actuated_names), "joint_order": actuated_names, "action_scale": 0.25},
        "control": {"control_hz": 50, "physics_hz": 1000, "decimation": 20},
        "description": "Imported robot asset draft generated by Legged Studio validation.",
        "tags": ["imported", model_format],
        "source": "legged_studio_asset_import",
        "min_mjlab_version": "1.6.0",
        "python_version": "3.12",
    }


def prepare_model_package(
    *,
    model_relative: Path,
    model_format: str,
    validation: dict[str, Any],
    content_hash: str,
    packages_root: Path,
) -> tuple[Path, dict[str, Any], dict[str, Any]]:
    contract = draft_model_contract(
        model_relative, validation.get("format", model_format),
        validation.get("inspection", {}), validation.get("sha256", ""),
    )
    package_id = f"{contract['robot_id']}_{content_hash[:10]}"
    package_root = packages_root / package_id
    contract.update({"robot_id": package_id, "contract_id": f"{package_id}_contract_v1"})
    contract["urdf"]["path"] = api_path(package_root / model_relative)
    descriptor = {
        "schema_version": "robot-package-1.0",
        "package_id": package_id,
        "task_kind": "generic",
        "native_task_id": None,
        "extension_root": None,
        "capabilities": ["generic_mjlab"],
        "model": {"format": model_format, "path": model_relative.as_posix(), "assets_path": model_relative.parent.as_posix()},
        "contract_path": "contract_legacy_v2.json",
        "content_sha256": content_hash,
    }
    return package_root, contract, descriptor


def persist_model_package(
    staging: Path, package_root: Path, contract: dict[str, Any], descriptor: dict[str, Any],
) -> dict[str, Any]:
    if not package_root.exists():
        write_json(staging / "contract_legacy_v2.json", contract)
        write_json(staging / "robot_package.json", descriptor)
        staging.rename(package_root)

    contract_note = None
    if not (package_root / "contract.json").exists():
        try:
            from backend.contract_migration import migrate_contract_dict

            draft = migrate_contract_dict(contract, None, generic_defaults=True)
            write_json(package_root / "contract.json", draft)
            contract_note = "generated（通用执行器默认值，训练前请校准）"
        except Exception as exc:
            contract_note = f"skipped: {exc}"

    upsert_package(package_root, source="workspace")
    return {"generated": contract_note is not None and contract_note.startswith("generated"), "note": contract_note}
