package(default_visibility = ["//visibility:public"])

cc_test(
    name = "unit_test",
    srcs = ["main.cpp"],
    deps = [
        "//src/test",
        "@googletest//:gtest_main",
    ],
    linkstatic = True,
)