// Copyright (c) 2025, AgiBot Inc.
// All rights reserved.

syntax = "proto3";
package aimdk.protocol;

import "aimdk/protocol/hds/exception.proto";
import "aimdk/protocol/common/header.proto";

/**
 * @brief 告警状态
 * @note 告警状态分为三种：未知、告警中、已清除
 */
enum AlertState {
  // 未知(默认状态)
  AlertState_UNDEFINED = 0;

  // 告警中
  AlertState_ACTIVE = 1;

  // 已清除
  AlertState_CLEARED = 2;

  // 告警中异常变更
  AlertState_ExceptionChanged = 3;

  // 恢复中
  AlertState_Recovering = 4;

}

/**
 * @brief 告警等级(健康状态)
 **/
enum AlertLevel {
  // 无告警
  AlertLevel_UNDEFINED = 0;

  // 致命告警
  AlertLevel_FATAL = 1;

  // 严重告警
  AlertLevel_SERIOUS = 2;

  // 警告告警
  AlertLevel_WARNING = 3;

  // 当前系统存在隐患
  AlertLevel_HIDDEN_DANGERS = 4;

  // 当前系统存在状态类告警
  AlertLevel_STATUS = 5;
}

/**
 * @brief 告警解决方案
 */
message AlertSolution{
  string type = 1;
  string content = 2; 
}

/**
 * @brief 告警展示类型
 */
enum AlertShowType{
    AlertShowType_Normal = 0;
    AlertShowType_Toast = 1;
}


/**
 * @brief 告警信息
 */
message Alert {
  // 告警ID
  string id = 1;

  // 告警产生的时间辍
  uint64 appeared_timestamp = 2;

  // 告警消失的时间辍
  uint64 disappeared_timestamp = 3;

  // 告警码
  string alert_code = 4;

  // 告警状态
  AlertState state = 5;

  // 当前告警包含的异常列表
  repeated ModuleException exception_list = 6;

  // 告警描述
  string description = 7;

  // 告警等级
  AlertLevel level = 8;

  //是否支持手动清除
  bool manual_clear = 9;

  //告警展示类型
  AlertShowType show_type = 10; 

  //告警解决方案列表
  repeated AlertSolution solution_list = 11;

}
