"""竞赛配方（族 Kit）消费的**机型侧 mdp 名称空间**（注入件）。

技能层不许 import 机型包，故该配方要用的机型 mdp 物件随 profile 带入（与 m20 的
`OfficialVelocityProfile.terms` 同一套机制）。本模块就是 zex-w 交出去的那一份：
**逐个具名**再导出（不用星导入 —— 名字集合即契约，多一个少一个都要在此显式改）。

* 奖励核：`..mdp.rewards` 里源配方实际引用的那批（平地档 16 项 / 越障档 25 项用到的全部）；
* 课程类：`..mdp.curriculums.command_levels_adaptive`（自适应命令区间课程）；
* 指标核：越障档诊断表用的那批（指标不影响训练行为，只影响日志）。
"""

from __future__ import annotations

from ..mdp.curriculums import command_levels_adaptive
from ..mdp.rewards import (
    actual_lin_vel_mean,
    actual_lin_vel_orthogonal_command_mean,
    adaptive_leg_motion_penalty,
    ang_vel_xy_l2,
    base_ground_contact_metric,
    base_height_l2,
    command_band_active,
    command_lin_vel_mean,
    command_yaw_vel_abs_mean,
    contact_forces,
    contact_fraction_reward,
    feet_contact_without_cmd,
    joint_mirror,
    joint_pos_penalty,
    joint_power,
    lin_vel_z_l2,
    safe_base_lin_vel,
    safe_foot_contact,
    safe_height_scan,
    stair_lateral_yaw_drift_l2,
    stand_still,
    track_angular_velocity,
    track_angular_velocity_z,
    track_linear_velocity,
    track_linear_velocity_x,
    track_linear_velocity_y,
    tracking_lin_vel_along_command_error,
    tracking_lin_vel_axis_error_band_mean,
    tracking_lin_vel_error,
    tracking_lin_vel_error_band_mean,
    tracking_lin_vel_x_error,
    tracking_lin_vel_y_error,
    tracking_yaw_vel_error,
    undesired_contacts,
    upward,
    upright_metric,
    wheel_actual_to_target_vel_ratio_mean,
    wheel_actual_vel_abs_mean,
    wheel_raw_action_abs_mean,
    wheel_roll_tracking,
    wheel_target_actual_sign_agreement,
    wheel_target_actual_vel_error_mean,
    wheel_target_vel_abs_mean,
)

__all__: tuple[str, ...] = (
    "actual_lin_vel_mean",
    "actual_lin_vel_orthogonal_command_mean",
    "adaptive_leg_motion_penalty",
    "ang_vel_xy_l2",
    "base_ground_contact_metric",
    "base_height_l2",
    "command_band_active",
    "command_levels_adaptive",
    "command_lin_vel_mean",
    "command_yaw_vel_abs_mean",
    "contact_forces",
    "contact_fraction_reward",
    "feet_contact_without_cmd",
    "joint_mirror",
    "joint_pos_penalty",
    "joint_power",
    "lin_vel_z_l2",
    "safe_base_lin_vel",
    "safe_foot_contact",
    "safe_height_scan",
    "stair_lateral_yaw_drift_l2",
    "stand_still",
    "track_angular_velocity",
    "track_angular_velocity_z",
    "track_linear_velocity",
    "track_linear_velocity_x",
    "track_linear_velocity_y",
    "tracking_lin_vel_along_command_error",
    "tracking_lin_vel_axis_error_band_mean",
    "tracking_lin_vel_error",
    "tracking_lin_vel_error_band_mean",
    "tracking_lin_vel_x_error",
    "tracking_lin_vel_y_error",
    "tracking_yaw_vel_error",
    "undesired_contacts",
    "upward",
    "upright_metric",
    "wheel_actual_to_target_vel_ratio_mean",
    "wheel_actual_vel_abs_mean",
    "wheel_raw_action_abs_mean",
    "wheel_roll_tracking",
    "wheel_target_actual_sign_agreement",
    "wheel_target_actual_vel_error_mean",
    "wheel_target_vel_abs_mean",
)
