/**
 * @file Point.h
 *
 * @brief Generated mirror of the mros `geometry_msgs/Point` message.
 *
 * THIS FILE IS GENERATED BY tools/limxsdk-gen/limxsdk_gen.py - DO NOT EDIT.
 * Regenerate it instead of patching it; hand edits are lost on the next run.
 *
 * © [2025] LimX Dynamics Technology Co., Ltd. All rights reserved.
 */

#ifndef _LIMX_SDK_MSG_GEOMETRY_MSGS_POINT_H_
#define _LIMX_SDK_MSG_GEOMETRY_MSGS_POINT_H_

#include <array>
#include <cstddef>
#include <cstdint>
#include <string>
#include <vector>

#include "limxsdk/codec/codec.h"

namespace limxsdk
{
  namespace msg
  {
    namespace geometry_msgs
    {
      /// @brief Mirror of the mros `geometry_msgs/Point` message.
      struct Point
      {
        static constexpr const char *TYPE = "geometry_msgs/Point";
        static constexpr const char *MD5 = "4a842b65f413084dc2b10fb484ea7f17";

        /// @brief ROS concatenated definition, as reported by mros.
        static const char *definition() { return "float64 x\nfloat64 y\nfloat64 z\n"; }

        double x = 0;
        double y = 0;
        double z = 0;

        /// @brief Decode one frame; false means discard the whole message.
        bool decode(::limxsdk::codec::Reader &reader)
        {
          if (!reader.read(x))
          {
            return false;
          }
          if (!reader.read(y))
          {
            return false;
          }
          if (!reader.read(z))
          {
            return false;
          }
          return !reader.failed();
        }

        /// @brief Encode into a buffer of at least encodedSize() bytes.
        bool encode(::limxsdk::codec::Writer &writer) const
        {
          if (!writer.write(x))
          {
            return false;
          }
          if (!writer.write(y))
          {
            return false;
          }
          if (!writer.write(z))
          {
            return false;
          }
          return !writer.failed();
        }

        /// @brief Exact number of bytes encode() will write.
        std::size_t encodedSize() const
        {
          return 24;
        }

        /// @brief Smallest possible encoding, used to reject bogus array lengths.
        static std::size_t minEncodedSize()
        {
          return 24;
        }
      };
    } // namespace geometry_msgs
  } // namespace msg
} // namespace limxsdk

#endif // _LIMX_SDK_MSG_GEOMETRY_MSGS_POINT_H_
