/**
 * @file Pose.h
 *
 * @brief Generated mirror of the mros `geometry_msgs/Pose` message.
 *
 * THIS FILE IS GENERATED BY tools/limxsdk-gen/limxsdk_gen.py - DO NOT EDIT.
 * Regenerate it instead of patching it; hand edits are lost on the next run.
 *
 * © [2025] LimX Dynamics Technology Co., Ltd. All rights reserved.
 */

#ifndef _LIMX_SDK_MSG_GEOMETRY_MSGS_POSE_H_
#define _LIMX_SDK_MSG_GEOMETRY_MSGS_POSE_H_

#include <array>
#include <cstddef>
#include <cstdint>
#include <string>
#include <vector>

#include "limxsdk/codec/codec.h"
#include "limxsdk/msg/geometry_msgs/Point.h"
#include "limxsdk/msg/geometry_msgs/Quaternion.h"

namespace limxsdk
{
  namespace msg
  {
    namespace geometry_msgs
    {
      /// @brief Mirror of the mros `geometry_msgs/Pose` message.
      struct Pose
      {
        static constexpr const char *TYPE = "geometry_msgs/Pose";
        static constexpr const char *MD5 = "e45d45a5a1ce597b249e23fb30fc871f";

        /// @brief ROS concatenated definition, as reported by mros.
        static const char *definition() { return "geometry_msgs/Point position\ngeometry_msgs/Quaternion orientation\n================================================================================\nMSG: geometry_msgs/Point\nfloat64 x\nfloat64 y\nfloat64 z\n================================================================================\nMSG: geometry_msgs/Quaternion\nfloat64 x\nfloat64 y\nfloat64 z\nfloat64 w\n"; }

        ::limxsdk::msg::geometry_msgs::Point position;
        ::limxsdk::msg::geometry_msgs::Quaternion orientation;

        /// @brief Decode one frame; false means discard the whole message.
        bool decode(::limxsdk::codec::Reader &reader)
        {
          if (!position.decode(reader))
          {
            return false;
          }
          if (!orientation.decode(reader))
          {
            return false;
          }
          return !reader.failed();
        }

        /// @brief Encode into a buffer of at least encodedSize() bytes.
        bool encode(::limxsdk::codec::Writer &writer) const
        {
          if (!position.encode(writer))
          {
            return false;
          }
          if (!orientation.encode(writer))
          {
            return false;
          }
          return !writer.failed();
        }

        /// @brief Exact number of bytes encode() will write.
        std::size_t encodedSize() const
        {
          std::size_t total = 0;
          total += position.encodedSize();
          total += orientation.encodedSize();
          return total;
        }

        /// @brief Smallest possible encoding, used to reject bogus array lengths.
        static std::size_t minEncodedSize()
        {
          return 0 + ::limxsdk::msg::geometry_msgs::Point::minEncodedSize() + ::limxsdk::msg::geometry_msgs::Quaternion::minEncodedSize();
        }
      };
    } // namespace geometry_msgs
  } // namespace msg
} // namespace limxsdk

#endif // _LIMX_SDK_MSG_GEOMETRY_MSGS_POSE_H_
