/**
 * @file PoseWithCovariance.h
 *
 * @brief Generated mirror of the mros `geometry_msgs/PoseWithCovariance` message.
 *
 * THIS FILE IS GENERATED BY tools/limxsdk-gen/limxsdk_gen.py - DO NOT EDIT.
 * Regenerate it instead of patching it; hand edits are lost on the next run.
 *
 * © [2025] LimX Dynamics Technology Co., Ltd. All rights reserved.
 */

#ifndef _LIMX_SDK_MSG_GEOMETRY_MSGS_POSEWITHCOVARIANCE_H_
#define _LIMX_SDK_MSG_GEOMETRY_MSGS_POSEWITHCOVARIANCE_H_

#include <array>
#include <cstddef>
#include <cstdint>
#include <string>
#include <vector>

#include "limxsdk/codec/codec.h"
#include "limxsdk/msg/geometry_msgs/Pose.h"

namespace limxsdk
{
  namespace msg
  {
    namespace geometry_msgs
    {
      /// @brief Mirror of the mros `geometry_msgs/PoseWithCovariance` message.
      struct PoseWithCovariance
      {
        static constexpr const char *TYPE = "geometry_msgs/PoseWithCovariance";
        static constexpr const char *MD5 = "c23e848cf1b7533a8d7c259073a97e6f";

        /// @brief ROS concatenated definition, as reported by mros.
        static const char *definition() { return "geometry_msgs/Pose pose\nfloat64[36] covariance\n================================================================================\nMSG: geometry_msgs/Pose\ngeometry_msgs/Point position\ngeometry_msgs/Quaternion orientation\n================================================================================\nMSG: geometry_msgs/Point\nfloat64 x\nfloat64 y\nfloat64 z\n================================================================================\nMSG: geometry_msgs/Quaternion\nfloat64 x\nfloat64 y\nfloat64 z\nfloat64 w\n"; }

        ::limxsdk::msg::geometry_msgs::Pose pose;
        std::array<double, 36> covariance;

        /// @brief Decode one frame; false means discard the whole message.
        bool decode(::limxsdk::codec::Reader &reader)
        {
          if (!pose.decode(reader))
          {
            return false;
          }
          if (!reader.readPodArrayFixed(covariance))
          {
            return false;
          }
          return !reader.failed();
        }

        /// @brief Encode into a buffer of at least encodedSize() bytes.
        bool encode(::limxsdk::codec::Writer &writer) const
        {
          if (!pose.encode(writer))
          {
            return false;
          }
          if (!writer.writePodArrayFixed(covariance))
          {
            return false;
          }
          return !writer.failed();
        }

        /// @brief Exact number of bytes encode() will write.
        std::size_t encodedSize() const
        {
          std::size_t total = 288;
          total += pose.encodedSize();
          return total;
        }

        /// @brief Smallest possible encoding, used to reject bogus array lengths.
        static std::size_t minEncodedSize()
        {
          return 288 + ::limxsdk::msg::geometry_msgs::Pose::minEncodedSize();
        }
      };
    } // namespace geometry_msgs
  } // namespace msg
} // namespace limxsdk

#endif // _LIMX_SDK_MSG_GEOMETRY_MSGS_POSEWITHCOVARIANCE_H_
