/**
 * @file TwistWithCovariance.h
 *
 * @brief Generated mirror of the mros `geometry_msgs/TwistWithCovariance` message.
 *
 * THIS FILE IS GENERATED BY tools/limxsdk-gen/limxsdk_gen.py - DO NOT EDIT.
 * Regenerate it instead of patching it; hand edits are lost on the next run.
 *
 * © [2025] LimX Dynamics Technology Co., Ltd. All rights reserved.
 */

#ifndef _LIMX_SDK_MSG_GEOMETRY_MSGS_TWISTWITHCOVARIANCE_H_
#define _LIMX_SDK_MSG_GEOMETRY_MSGS_TWISTWITHCOVARIANCE_H_

#include <array>
#include <cstddef>
#include <cstdint>
#include <string>
#include <vector>

#include "limxsdk/codec/codec.h"
#include "limxsdk/msg/geometry_msgs/Twist.h"

namespace limxsdk
{
  namespace msg
  {
    namespace geometry_msgs
    {
      /// @brief Mirror of the mros `geometry_msgs/TwistWithCovariance` message.
      struct TwistWithCovariance
      {
        static constexpr const char *TYPE = "geometry_msgs/TwistWithCovariance";
        static constexpr const char *MD5 = "1fe8a28e6890a4cc3ae4c3ca5c7d82e6";

        /// @brief ROS concatenated definition, as reported by mros.
        static const char *definition() { return "geometry_msgs/Twist twist\nfloat64[36] covariance\n================================================================================\nMSG: geometry_msgs/Twist\ngeometry_msgs/Vector3 linear\ngeometry_msgs/Vector3 angular\n================================================================================\nMSG: geometry_msgs/Vector3\nfloat64 x\nfloat64 y\nfloat64 z\n"; }

        ::limxsdk::msg::geometry_msgs::Twist twist;
        std::array<double, 36> covariance;

        /// @brief Decode one frame; false means discard the whole message.
        bool decode(::limxsdk::codec::Reader &reader)
        {
          if (!twist.decode(reader))
          {
            return false;
          }
          if (!reader.readPodArrayFixed(covariance))
          {
            return false;
          }
          return !reader.failed();
        }

        /// @brief Encode into a buffer of at least encodedSize() bytes.
        bool encode(::limxsdk::codec::Writer &writer) const
        {
          if (!twist.encode(writer))
          {
            return false;
          }
          if (!writer.writePodArrayFixed(covariance))
          {
            return false;
          }
          return !writer.failed();
        }

        /// @brief Exact number of bytes encode() will write.
        std::size_t encodedSize() const
        {
          std::size_t total = 288;
          total += twist.encodedSize();
          return total;
        }

        /// @brief Smallest possible encoding, used to reject bogus array lengths.
        static std::size_t minEncodedSize()
        {
          return 288 + ::limxsdk::msg::geometry_msgs::Twist::minEncodedSize();
        }
      };
    } // namespace geometry_msgs
  } // namespace msg
} // namespace limxsdk

#endif // _LIMX_SDK_MSG_GEOMETRY_MSGS_TWISTWITHCOVARIANCE_H_
