/**
 * @file Twist.h
 *
 * @brief Generated mirror of the mros `geometry_msgs/Twist` message.
 *
 * THIS FILE IS GENERATED BY tools/limxsdk-gen/limxsdk_gen.py - DO NOT EDIT.
 * Regenerate it instead of patching it; hand edits are lost on the next run.
 *
 * © [2025] LimX Dynamics Technology Co., Ltd. All rights reserved.
 */

#ifndef _LIMX_SDK_MSG_GEOMETRY_MSGS_TWIST_H_
#define _LIMX_SDK_MSG_GEOMETRY_MSGS_TWIST_H_

#include <array>
#include <cstddef>
#include <cstdint>
#include <string>
#include <vector>

#include "limxsdk/codec/codec.h"
#include "limxsdk/msg/geometry_msgs/Vector3.h"

namespace limxsdk
{
  namespace msg
  {
    namespace geometry_msgs
    {
      /// @brief Mirror of the mros `geometry_msgs/Twist` message.
      struct Twist
      {
        static constexpr const char *TYPE = "geometry_msgs/Twist";
        static constexpr const char *MD5 = "9f195f881246fdfa2798d1d3eebca84a";

        /// @brief ROS concatenated definition, as reported by mros.
        static const char *definition() { return "geometry_msgs/Vector3 linear\ngeometry_msgs/Vector3 angular\n================================================================================\nMSG: geometry_msgs/Vector3\nfloat64 x\nfloat64 y\nfloat64 z\n"; }

        ::limxsdk::msg::geometry_msgs::Vector3 linear;
        ::limxsdk::msg::geometry_msgs::Vector3 angular;

        /// @brief Decode one frame; false means discard the whole message.
        bool decode(::limxsdk::codec::Reader &reader)
        {
          if (!linear.decode(reader))
          {
            return false;
          }
          if (!angular.decode(reader))
          {
            return false;
          }
          return !reader.failed();
        }

        /// @brief Encode into a buffer of at least encodedSize() bytes.
        bool encode(::limxsdk::codec::Writer &writer) const
        {
          if (!linear.encode(writer))
          {
            return false;
          }
          if (!angular.encode(writer))
          {
            return false;
          }
          return !writer.failed();
        }

        /// @brief Exact number of bytes encode() will write.
        std::size_t encodedSize() const
        {
          std::size_t total = 0;
          total += linear.encodedSize();
          total += angular.encodedSize();
          return total;
        }

        /// @brief Smallest possible encoding, used to reject bogus array lengths.
        static std::size_t minEncodedSize()
        {
          return 0 + ::limxsdk::msg::geometry_msgs::Vector3::minEncodedSize() + ::limxsdk::msg::geometry_msgs::Vector3::minEncodedSize();
        }
      };
    } // namespace geometry_msgs
  } // namespace msg
} // namespace limxsdk

#endif // _LIMX_SDK_MSG_GEOMETRY_MSGS_TWIST_H_
