package(default_visibility = ["//visibility:public"])

cc_library(
    name = "all_in_one",
    hdrs = ["include/aimrte.h"],
    deps = [
        "//src/module",
        "//src/prelude",
        "//src/program",
    ],
)
