# SPDX-FileCopyrightText: Copyright (c) 2025 The Newton Developers
# SPDX-License-Identifier: Apache-2.0

import inspect
import unittest

import numpy as np
import warp as wp

import newton
from newton.tests.unittest_utils import assert_np_equal
from newton.viewer import ViewerNull


class _ViewerGeometryBatchingProbe(ViewerNull):
    """A minimal viewer probe for testing viewer-side batching/caching.

    Uses `ViewerNull` to avoid any rendering backend dependencies.
    """

    def __init__(self):
        super().__init__(num_frames=1)
        self.log_capsules_calls = 0
        self.log_instances_calls = 0

    def _hash_geometry(
        self, geo_type: int, geo_scale, thickness: float, is_solid: bool, geo_src=None, mirror: bool = False
    ) -> int:
        # Match ViewerGL's capsule batching behavior: ignore capsule dimensions in the hash so
        # varying-radius / varying-half_height capsules can share one cached geometry identity.
        if geo_type == newton.GeoType.CAPSULE:
            geo_scale = (1.0, 1.0)
        return super()._hash_geometry(geo_type, geo_scale, thickness, is_solid, geo_src, mirror)

    def set_model(self, model):
        super().set_model(model)
        if self.model is None:
            return

        # ViewerGL uses instanced cylinder + spheres and expects capsule body instance scales to be
        # `(radius, radius, half_height)`. Since this probe shares the same capsule hashing behavior
        # (dimensions ignored), we re-materialize the per-shape dimensions into per-instance scales.
        shape_scale_np = self.model.shape_scale.numpy()

        for batch in self._shape_instances.values():
            if batch.geo_type != newton.GeoType.CAPSULE:
                continue

            idxs = list(batch.model_shapes)
            scales = [
                wp.vec3(
                    float(shape_scale_np[s][0]),
                    float(shape_scale_np[s][0]),
                    float(shape_scale_np[s][1]),
                )
                for s in idxs
            ]
            batch.scales = wp.array(scales, dtype=wp.vec3, device=self.device)

    def log_instances(self, *_args, **_kwargs):
        self.log_instances_calls += 1

    def log_capsules(self, name, mesh, xforms, scales, colors, materials, hidden=False, opacities=None):
        self.log_capsules_calls += 1

        # Fallback behavior: treat capsule batches like any other instanced geometry.
        self.log_instances(name, mesh, xforms, scales, colors, materials, opacities=opacities, hidden=hidden)


class _ViewerMeshProbe(ViewerNull):
    """Capture meshes generated by the shared viewer geometry path."""

    def __init__(self):
        super().__init__(num_frames=1)
        self.points = None

    def log_mesh(self, _name, points, _indices, *args, **kwargs):
        """Capture generated mesh points."""
        self.points = points.numpy()


class _ViewerLegacyMeshSignatureProbe(ViewerNull):
    """Represent a third-party backend implementing the pre-PR mesh signature."""

    def __init__(self):
        super().__init__(num_frames=1)
        self.logged = False
        self.uvs = None

    def log_mesh(
        self,
        _name,
        _points,
        _indices,
        _normals=None,
        uvs=None,
        texture=None,
        hidden=False,
    ):
        """Record a mesh without accepting new texture-mapping keywords."""
        self.logged = True
        self.uvs = None if uvs is None else uvs.numpy()


class TestViewerGeometryBatching(unittest.TestCase):
    def test_mesh_rejects_invalid_texture_transform(self):
        """Reject malformed texture transforms at their Mesh owner."""
        vertices = np.array([[0, 0, 0], [1, 0, 0], [0, 1, 0]], dtype=np.float32)
        indices = np.array([0, 1, 2], dtype=np.int32)
        for transform in (
            ((1.0, 0.0), (0.0, 1.0)),
            ((1.0, 0.0, np.nan), (0.0, 1.0, 0.0)),
        ):
            with self.subTest(transform=transform), self.assertRaisesRegex(ValueError, "texture_transform"):
                newton.Mesh(vertices, indices, compute_inertia=False, texture_transform=transform)

    def test_texture_transform_is_owned_by_viewer_geometry_cache(self):
        """Keep texture-transform identity in the shared visual geometry cache."""
        vertices = np.array([[0, 0, 0], [1, 0, 0], [0, 1, 0]], dtype=np.float32)
        indices = np.array([0, 1, 2], dtype=np.int32)
        mesh = newton.Mesh(vertices, indices, compute_inertia=False)
        mesh.texture = np.full((2, 2, 3), 255, dtype=np.uint8)
        transformed_mesh = mesh.copy()
        transformed_mesh.texture_transform = ((0.5, 0.0, 0.25), (0.0, 2.0, -0.75))

        self.assertEqual(hash(transformed_mesh), hash(mesh))

        viewer = _ViewerGeometryBatchingProbe()
        mesh_hash = viewer._hash_geometry(newton.GeoType.MESH, (1.0, 1.0, 1.0), 0.0, True, mesh)
        transformed_mesh_hash = viewer._hash_geometry(newton.GeoType.MESH, (1.0, 1.0, 1.0), 0.0, True, transformed_mesh)
        self.assertNotEqual(transformed_mesh_hash, mesh_hash)

    def test_texture_transform_does_not_expand_backend_log_mesh_signature(self):
        """Transform UVs without expanding the public backend method contract."""
        parameters = inspect.signature(newton.viewer.ViewerBase.log_mesh).parameters
        forbidden = {
            "texture_transform",
            "texture_coordinate_source",
            "texture_scale",
            "texture_translate",
            "texture_rotate",
            "texture_projection",
        }
        self.assertTrue(forbidden.isdisjoint(parameters))
        self.assertFalse(hasattr(newton.Mesh, "TextureProjection"))
        self.assertFalse(hasattr(newton.Mesh, "TextureCoordinateSource"))

        authored_uvs = np.array(((0.1, 0.2), (1.1, 0.2), (0.1, 1.2)), dtype=np.float32)
        mesh = newton.Mesh(
            [[0, 0, 0], [1, 0, 0], [0, 1, 0]],
            [0, 1, 2],
            uvs=authored_uvs,
            compute_inertia=False,
            texture=np.full((2, 2, 3), 255, dtype=np.uint8),
            texture_transform=((0.5, 0.0, 0.25), (0.0, 2.0, -0.75)),
        )
        viewer = _ViewerLegacyMeshSignatureProbe()
        viewer.log_geo("/mesh", newton.GeoType.MESH, (1.0, 1.0, 1.0), 0.0, True, geo_src=mesh)
        self.assertTrue(viewer.logged)
        np.testing.assert_allclose(viewer.uvs, authored_uvs * (0.5, 2.0) + (0.25, -0.75))

    def test_barrel_cylinder_geometry(self):
        """Verify viewers generate the curved cylinder profile."""
        radius = 0.5
        half_height = 1.0
        barrel_radius = 2.0
        expected_equatorial_radius = radius + (half_height * half_height) / (
            barrel_radius + np.sqrt(barrel_radius * barrel_radius - half_height * half_height)
        )

        viewer = _ViewerMeshProbe()
        viewer.log_geo(
            "/barrel",
            newton.GeoType.CYLINDER,
            (radius, half_height, barrel_radius),
            0.0,
            True,
        )

        self.assertIsNotNone(viewer.points)
        radial_distances = np.linalg.norm(viewer.points[:, :2], axis=1)
        self.assertAlmostEqual(float(np.max(radial_distances)), expected_equatorial_radius, places=6)

    def test_mjcf_cylinder_site_ignores_display_size(self):
        """Treat an MJCF cylinder site's third size component as display metadata."""
        builder = newton.ModelBuilder()
        builder.add_mjcf(
            """
            <mujoco>
                <worldbody>
                    <body>
                        <geom type="cylinder" size="0.02 0.1"/>
                        <site type="cylinder" size="0.02 0.1"/>
                    </body>
                </worldbody>
            </mujoco>
            """
        )

        sites = [i for i, flags in enumerate(builder.shape_flags) if flags & newton.ShapeFlags.SITE]
        self.assertEqual(builder.shape_count, 2)
        self.assertEqual(len(sites), 1)

        site = sites[0]
        self.assertAlmostEqual(builder.shape_scale[site][2], 0.005)

        viewer = _ViewerGeometryBatchingProbe()
        viewer.set_model(builder.finalize())

        self.assertEqual(len(viewer._geometry_cache), 1)

    def test_native_cylinder_site_uses_barrel_radius(self):
        """Honor an explicitly authored barrel radius on a cylinder site."""
        radius = 0.5
        half_height = 1.0
        barrel_radius = 2.0

        builder = newton.ModelBuilder()
        builder.add_shape_cylinder(-1, radius=radius, half_height=half_height)
        site = builder.add_shape_cylinder(
            -1,
            radius=radius,
            half_height=half_height,
            barrel_radius=barrel_radius,
            as_site=True,
        )

        self.assertEqual(builder.shape_scale[site][2], barrel_radius)

        viewer = _ViewerGeometryBatchingProbe()
        viewer.set_model(builder.finalize())

        self.assertEqual(len(viewer._geometry_cache), 2)

    def test_capsule_geometry_is_batched_across_scales(self):
        """Varying capsule dimensions should share one cached capsule geometry."""
        builder = newton.ModelBuilder()
        body = builder.add_body(
            xform=wp.transform(wp.vec3(0.0, 0.0, 0.0), wp.quat_identity()),
            mass=1.0,
        )

        # Three capsules with different (radius, half_height).
        builder.add_shape_capsule(body=body, radius=0.02, half_height=0.10)
        builder.add_shape_capsule(body=body, radius=0.03, half_height=0.15)
        builder.add_shape_capsule(body=body, radius=0.05, half_height=0.07)

        model = builder.finalize()
        viewer = _ViewerGeometryBatchingProbe()
        viewer.show_collision = True
        viewer.set_model(model)

        # All capsule shapes should end up in a single capsule batch (same flags/static).
        capsule_batches = [b for b in viewer._shape_instances.values() if b.geo_type == newton.GeoType.CAPSULE]
        self.assertEqual(len(capsule_batches), 1)

        batch = capsule_batches[0]

        # Geometry caching check: the capsule batch should reference one cached geometry path,
        # even though the model contains capsules with different (radius, half_height).
        self.assertIsInstance(batch.mesh, str)
        self.assertIn(batch.mesh, viewer._geometry_cache.values())

        # This test builds a capsules-only model, so the viewer should only have to create/cache
        # a single geometry mesh path in total.
        self.assertEqual(len(set(viewer._geometry_cache.values())), 1)
        self.assertEqual(len(batch.scales), 3)

        # Scales should be rewritten to (r, r, half_height) per shape.
        scales_np = batch.scales.numpy()
        expected = np.array(
            [
                [0.02, 0.02, 0.10],
                [0.03, 0.03, 0.15],
                [0.05, 0.05, 0.07],
            ],
            dtype=np.float32,
        )

        scales_sorted = scales_np[np.lexsort((scales_np[:, 2], scales_np[:, 0]))]
        expected_sorted = expected[np.lexsort((expected[:, 2], expected[:, 0]))]
        assert_np_equal(scales_sorted, expected_sorted, tol=1e-6)

    def test_log_state_routes_capsules_to_log_capsules(self):
        """`ViewerBase.log_state()` should dispatch capsule batches via `log_capsules()`."""
        builder = newton.ModelBuilder()
        body = builder.add_body(
            xform=wp.transform(wp.vec3(0.0, 0.0, 0.0), wp.quat_identity()),
            mass=1.0,
        )
        builder.add_shape_capsule(body=body, radius=0.05, half_height=0.2)
        builder.add_shape_box(body=body, hx=0.1, hy=0.1, hz=0.1)

        model = builder.finalize()
        state = model.state()

        viewer = _ViewerGeometryBatchingProbe()
        viewer.show_collision = True
        viewer.set_model(model)
        viewer.begin_frame(0.0)
        viewer.log_state(state)

        self.assertGreaterEqual(viewer.log_capsules_calls, 1)
        self.assertGreaterEqual(viewer.log_instances_calls, 1)


if __name__ == "__main__":
    unittest.main(verbosity=2)
