# Copyright (c) 2024-2025 zh

M20:
  model_names: 
    - "Jun18_15-24-47_lc.pt" # locomotion
    - "Jun13_23-01-46_highplatform.pt" # 高台
    - "policy_dwaq.pt" # model from https://github.com/yusongmin1/Dreamwaq

  dt: 0.005
  decimation: 4
  num_of_dofs: 16
  num_observations: 57
  observations: ["commands", "ang_vel", "gravity_vec", "dof_pos", "dof_vel", "actions"]
  observations_history: [5, 4, 3, 2, 1, 0]
  clip_obs: 100.0
  fixed_kp: [80.0, 80.0, 80.0, 0.0,
             80.0, 80.0, 80.0, 0.0,
             80.0, 80.0, 80.0, 0.0,
             80.0, 80.0, 80.0, 0.0]
  fixed_kd: [2.0, 2.0, 2.0, 0.6,
             2.0, 2.0, 2.0, 0.6,
             2.0, 2.0, 2.0, 0.6,
             2.0, 2.0, 2.0, 0.6] 
  rl_kp: [80.0, 80.0, 80.0, 0.0,
          80.0, 80.0, 80.0, 0.0,
          80.0, 80.0, 80.0, 0.0,
          80.0, 80.0, 80.0, 0.0]
  rl_kd: [2.0, 2.0, 2.0, 0.6,
          2.0, 2.0, 2.0, 0.6,
          2.0, 2.0, 2.0, 0.6,
          2.0, 2.0, 2.0, 0.6]  
  action_scale: [0.25, 0.25, 0.25, 5.0,
                 0.25, 0.25, 0.25, 5.0,
                 0.25, 0.25, 0.25, 5.0,
                 0.25, 0.25, 0.25, 5.0]
  wheel_indices: [3, 7, 11, 15]
  ang_vel_scale: 0.25
  dof_pos_scale: 1.0
  dof_vel_scale: 0.05
  commands_scale: [2.0, 2.0, 0.25]
  torque_limits: [80, 80, 80, 80,
                  80, 80, 80, 80,
                  80, 80, 80, 80,
                  80, 80, 80, 80]
  default_dof_pos: [0.0, -0.6, 1.0, 0.0, 
                    0.0, -0.6, 1.0, 0.0, 
                    0.0, 0.6, -1.0, 0.0, 
                    0.0, 0.6, -1.0, 0.0]
  joint_controller_names: ["fl_hipx_joint", "fl_hipy_joint", "fl_knee_joint", "fl_wheel_joint",
                           "fr_hipx_joint", "fr_hipy_joint", "fr_knee_joint", "fr_wheel_joint",
                           "hl_hipx_joint", "hl_hipy_joint", "hl_knee_joint", "hl_wheel_joint",
                           "hr_hipx_joint", "hr_hipy_joint", "hr_knee_joint", "hr_wheel_joint"]
  joint_mapping: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
