package(default_visibility = ["//visibility:public"])

cc_library(
    name = "aimrt_module_protobuf_interface",
    srcs = [],
    hdrs = glob(["**/*.h"]),
    deps = [
        "@integration//:protobuf",
        "//src/interface/aimrt_module_cpp_interface",
    ],
    includes = [".."],
)
