package(default_visibility = ["//visibility:public"])

cc_library(
    name = "ros2_util",
    hdrs = glob(["*.h"]),
    deps = [
        "@jsoncpp",
        "@ros2_rclcpp//:rclcpp",
        "@yaml-cpp",
    ],
)
