# Copyright (c) 2025, AgiBot Inc.
# All rights reserved.

# ----------------------------------------------------
# request

# 请求数据头
std_msgs/Header header

# 请求焦点信息
FocusRequester focus_requester

---

# ----------------------------------------------------
# response

# 响应数据头
std_msgs/Header header

# 请求结果
FocusResponse focus_response

