# Copyright (c) 2025, AgiBot Inc.
# All rights reserved.

# ----------------------------------------------------
# request

# 请求数据头
std_msgs/Header header

---

# ----------------------------------------------------
# response

# 当前播放设备
# default: 本体
# 蓝牙设备传入MAC地址
string address

# 响应数据头
std_msgs/Header header