# Copyright (c) 2025, AgiBot Inc.
# All rights reserved.

# ----------------------------------------------------
# request

# 请求数据头
std_msgs/Header header

# 请求静音状态
# true(mute)
# false(unmute)
bool is_mute

---

# ----------------------------------------------------
# response

# 响应数据头
std_msgs/Header header

# 当前静音状态
bool is_mute

