/**
 * @file TaskState.h
 *
 * @brief Generated mirror of the mros `task_state_msgs/TaskState` message.
 *
 * THIS FILE IS GENERATED BY tools/limxsdk-gen/limxsdk_gen.py - DO NOT EDIT.
 * Regenerate it instead of patching it; hand edits are lost on the next run.
 *
 * © [2025] LimX Dynamics Technology Co., Ltd. All rights reserved.
 */

#ifndef _LIMX_SDK_MSG_TASK_STATE_MSGS_TASKSTATE_H_
#define _LIMX_SDK_MSG_TASK_STATE_MSGS_TASKSTATE_H_

#include <array>
#include <cstddef>
#include <cstdint>
#include <string>
#include <vector>

#include "limxsdk/codec/codec.h"
#include "limxsdk/msg/std_msgs/Header.h"

namespace limxsdk
{
  namespace msg
  {
    namespace task_state_msgs
    {
      /// @brief Mirror of the mros `task_state_msgs/TaskState` message.
      struct TaskState
      {
        static constexpr const char *TYPE = "task_state_msgs/TaskState";
        static constexpr const char *MD5 = "12e2b939762eccd12758c38a0293b215";
        static constexpr int8_t TASK_STATE_RUNNING = 0;
        static constexpr int8_t TASK_STATE_PAUSED = 1;
        static constexpr int8_t TASK_STATE_CANCELED = 2;
        static constexpr int8_t TASK_STATE_FINISHED = 3;
        static constexpr int8_t TASK_STATE_CHECK_VERSION = 4;
        static constexpr int8_t TASK_STATE_DOWNLOADING = 5;
        static constexpr int8_t TASK_STATE_DOWNLOAD_FINISHED = 6;
        static constexpr int8_t TASK_STATE_UPGRADING = 7;
        static constexpr int8_t TASK_STATE_RESTART_SERVICE = 8;
        static constexpr int8_t TASK_STATE_UPGRAD_FINISHED = 9;
        static constexpr int8_t TASK_STATE_UPGRAD_FAILED = 10;

        /// @brief ROS concatenated definition, as reported by mros.
        static const char *definition() { return "std_msgs/Header header\nint8 TASK_STATE_RUNNING  = 0\nint8 TASK_STATE_PAUSED   = 1\nint8 TASK_STATE_CANCELED = 2\nint8 TASK_STATE_FINISHED = 3\nint8 TASK_STATE_CHECK_VERSION     = 4\nint8 TASK_STATE_DOWNLOADING       = 5\nint8 TASK_STATE_DOWNLOAD_FINISHED = 6\nint8 TASK_STATE_UPGRADING         = 7\nint8 TASK_STATE_RESTART_SERVICE   = 8\nint8 TASK_STATE_UPGRAD_FINISHED   = 9\nint8 TASK_STATE_UPGRAD_FAILED     = 10\nint8 state\nstring data\n================================================================================\nMSG: std_msgs/Header\nuint32 seq\ntime stamp\nstring frame_id\n"; }

        ::limxsdk::msg::std_msgs::Header header;
        int8_t state = 0;
        std::string data;

        /// @brief Decode one frame; false means discard the whole message.
        bool decode(::limxsdk::codec::Reader &reader)
        {
          if (!header.decode(reader))
          {
            return false;
          }
          if (!reader.read(state))
          {
            return false;
          }
          if (!reader.read(data))
          {
            return false;
          }
          return !reader.failed();
        }

        /// @brief Encode into a buffer of at least encodedSize() bytes.
        bool encode(::limxsdk::codec::Writer &writer) const
        {
          if (!header.encode(writer))
          {
            return false;
          }
          if (!writer.write(state))
          {
            return false;
          }
          if (!writer.write(data))
          {
            return false;
          }
          return !writer.failed();
        }

        /// @brief Exact number of bytes encode() will write.
        std::size_t encodedSize() const
        {
          std::size_t total = 5;
          total += header.encodedSize();
          total += data.size();
          return total;
        }

        /// @brief Smallest possible encoding, used to reject bogus array lengths.
        static std::size_t minEncodedSize()
        {
          return 5 + ::limxsdk::msg::std_msgs::Header::minEncodedSize();
        }
      };
    } // namespace task_state_msgs
  } // namespace msg
} // namespace limxsdk

#endif // _LIMX_SDK_MSG_TASK_STATE_MSGS_TASKSTATE_H_
