// Copyright (c) 2024 The AimRT Authors.
// AimRT is licensed under Mulan PSL v2.

#pragma once

#include "src/interface/aimrt_module_cpp_interface/allocator/allocator.h"
#include "src/interface/aimrt_module_cpp_interface/channel/channel_context.h"
#include "src/interface/aimrt_module_cpp_interface/channel/channel_handle.h"
#include "src/interface/aimrt_module_cpp_interface/co/aimrt_context.h"
#include "src/interface/aimrt_module_cpp_interface/co/async_scope.h"
#include "src/interface/aimrt_module_cpp_interface/co/inline_scheduler.h"
#include "src/interface/aimrt_module_cpp_interface/co/on.h"
#include "src/interface/aimrt_module_cpp_interface/co/schedule.h"
#include "src/interface/aimrt_module_cpp_interface/co/start_detached.h"
#include "src/interface/aimrt_module_cpp_interface/co/sync_wait.h"
#include "src/interface/aimrt_module_cpp_interface/co/task.h"
#include "src/interface/aimrt_module_cpp_interface/co/then.h"
#include "src/interface/aimrt_module_cpp_interface/configurator/configurator.h"
#include "src/interface/aimrt_module_cpp_interface/context/context.h"
#include "src/interface/aimrt_module_cpp_interface/context/res/channel.h"
#include "src/interface/aimrt_module_cpp_interface/context/res/service.h"
#include "src/interface/aimrt_module_cpp_interface/core.h"
#include "src/interface/aimrt_module_cpp_interface/executor/executor.h"
#include "src/interface/aimrt_module_cpp_interface/executor/executor_manager.h"
#include "src/interface/aimrt_module_cpp_interface/executor/timer.h"
#include "src/interface/aimrt_module_cpp_interface/logger/logger.h"
#include "src/interface/aimrt_module_cpp_interface/module_base.h"
#include "src/interface/aimrt_module_cpp_interface/parameter/parameter_handle.h"
#include "src/interface/aimrt_module_cpp_interface/rpc/rpc_co_filter.h"
#include "src/interface/aimrt_module_cpp_interface/rpc/rpc_context.h"
#include "src/interface/aimrt_module_cpp_interface/rpc/rpc_handle.h"
#include "src/interface/aimrt_module_cpp_interface/rpc/rpc_status.h"
#include "src/interface/aimrt_module_cpp_interface/util/buffer.h"
#include "src/interface/aimrt_module_cpp_interface/util/buffer_array_allocator.h"
#include "src/interface/aimrt_module_cpp_interface/util/function.h"
#include "src/interface/aimrt_module_cpp_interface/util/string.h"
#include "src/interface/aimrt_module_cpp_interface/util/type_support.h"
#include "src/interface/aimrt_module_cpp_interface/util/version.h"
