package(default_visibility = ["//visibility:public"])

cc_library(
    name = "common",
    hdrs = [
        "my_module.h",
    ],
    srcs = [
        "my_module.cpp",
    ],
    deps = [
        "//:aimrte",
    ],
)
