package(
    default_visibility = ["//visibility:public"],
)

exports_files([
    "Temp.msg",
    "TempState.msg",
])

filegroup(
    name = "ros2_files",
    srcs = glob([
        "*.msg",
    ]),
)
