package(
    default_visibility = ["//visibility:public"],
)

exports_files([
    "process_health_channel.proto",
    "process_health.proto",
    "process_heartbeat_channel.proto",
    "process_heartbeat.proto",
])
