/**
 * @file type_registry.h
 *
 * @brief TYPE+MD5 table of every generated message mirror.
 *
 * THIS FILE IS GENERATED BY tools/limxsdk-gen/limxsdk_gen.py - DO NOT EDIT.
 * Regenerate it instead of patching it; hand edits are lost on the next run.
 *
 * queryTopicSupport() looks a live topic up in this table. A match on TYPE
 * means the SDK ships a generated class for it; a match on MD5 means that
 * class is the same revision the peer advertised. The table is a pair of
 * string literals per type, so adding a message never changes the exported
 * ABI of limxsdk_lowlevel.
 *
 * © [2025] LimX Dynamics Technology Co., Ltd. All rights reserved.
 */

#ifndef _LIMX_SDK_MSG_TYPE_REGISTRY_H_
#define _LIMX_SDK_MSG_TYPE_REGISTRY_H_

#include <cstddef>

namespace limxsdk
{
  namespace msg
  {
    /// @brief One generated mirror, identified the same way mros matches subscriptions.
    struct MirroredType
    {
      const char *type;
      const char *md5;
    };

    /// @brief All generated mirrors. @p count receives the length; never null entries.
    inline const MirroredType *mirroredTypes(std::size_t *count)
    {
      static const MirroredType kTable[] = {
          {"control_msgs/GripperCommand", "680acaff79486f017132a7f198d40f08"},
          {"controller_manager_msgs/ControllerState", "aeb6b261d97793ab74099a3740245272"},
          {"controller_manager_msgs/HardwareInterfaceResources", "f25b55cbf1d1f76e82e5ec9e83f76258"},
          {"controller_msgs/IMUData", "4713fbd787897a0c91a2a31aa6a873c6"},
          {"controller_msgs/JointCmd", "4cdfcb8fe72a285fbf420eab84b4b860"},
          {"controller_msgs/JointCmdLimx", "aa66c708f26b270ba9c935d9e8db6182"},
          {"controller_msgs/JointState", "0d1d997e638ba23ee585b83a152596fe"},
          {"controller_msgs/RCASCmdStamped", "55583299a0c731b2fc59553bae330532"},
          {"controller_msgs/RCASCmdStampedWL", "0197db14404650210fcc1b048026a46d"},
          {"controller_msgs/RCCmdStamped", "cb92ef9a5f527c5fa02b4b5096689a38"},
          {"diagnostic_msgs/DiagnosticValue", "879d5c821998ca0ab6e3520e8c63e5fc"},
          {"geometry_msgs/Point", "4a842b65f413084dc2b10fb484ea7f17"},
          {"geometry_msgs/Pose", "e45d45a5a1ce597b249e23fb30fc871f"},
          {"geometry_msgs/PoseWithCovariance", "c23e848cf1b7533a8d7c259073a97e6f"},
          {"geometry_msgs/Quaternion", "a779879fadf0160734f906b8c19c7004"},
          {"geometry_msgs/Twist", "9f195f881246fdfa2798d1d3eebca84a"},
          {"geometry_msgs/TwistWithCovariance", "1fe8a28e6890a4cc3ae4c3ca5c7d82e6"},
          {"geometry_msgs/Vector3", "4a842b65f413084dc2b10fb484ea7f17"},
          {"hand_msgs/HandCmd", "cc671eacc3dec085edca419077f5b87a"},
          {"hand_msgs/HandMsg", "5bf399d0b94663b56e927d0e9c254c1c"},
          {"hand_msgs/HandState", "0e859982707a5c9b2e1da5a16bffb891"},
          {"hand_msgs/TactileCmd", "8b0263238e251bcb7003327943797186"},
          {"hand_msgs/TactileHandCmd", "b81dd29ed39e709fef66ce4325d8bc29"},
          {"hand_msgs/TactileHandState", "ac5f5ca79b187659a94b06b37f2a6caa"},
          {"hand_msgs/TactileState", "b8b0b952da0486df66b2e68584d4b3c2"},
          {"ipcamera_msgs/CameraCtrl", "41cfee5ccb3e668affc169faf932fb42"},
          {"nav_msgs/MapMetaData", "10cfc8a2818024d3248802c00c95f11b"},
          {"nav_msgs/OccupancyGrid", "3381f2d731d4076ec5c71b0759edbe4e"},
          {"nav_msgs/Odometry", "cd5e73d190d741a2f92e81eda573aca7"},
          {"perception_msgs/HeightEstimateResult", "cf11f0059969194da977bc733040e097"},
          {"sensor_msgs/Joy", "5a9ea5f83505693b71e785041e67a8bb"},
          {"sensor_msgs/JoyH16", "c65ce9204f033c8f40297b950337e517"},
          {"std_msgs/Bool", "8b94c1b53db61fb6aed406028ad6332a"},
          {"std_msgs/Byte", "ad736a2e8818154c487bb80fe42ce43b"},
          {"std_msgs/Empty", "d41d8cd98f00b204e9800998ecf8427e"},
          {"std_msgs/Float32MultiArray", "6a40e0ffa6a17a503ac3f8616991b1f6"},
          {"std_msgs/Float64Array", "fb60495edd59d3fcf90e173153ae8a9a"},
          {"std_msgs/Float64MultiArray", "4b7d974086d4060e7db4613a7e6c3ba4"},
          {"std_msgs/Header", "2176decaecbce78abc3b96ef049fabed"},
          {"std_msgs/Int32Array", "1ce4762ce13f3d9e1f17586acc253067"},
          {"std_msgs/Int8", "27ffa0c9c4b8fb8492252bcad9e5c57b"},
          {"std_msgs/Int8Array", "76e8caca558be0db7a08d3479289f362"},
          {"std_msgs/MultiArrayDimension", "4cd0c83a8683deae40ecdac60e53bfa8"},
          {"std_msgs/MultiArrayLayout", "0fed2a11c13e11c5571b4e2a995a91a3"},
          {"std_msgs/String", "992ce8a1687cec8c8bd883ec73ca41d1"},
          {"std_msgs/UInt16Array", "2b9446334eb40dbaedf25a747be49905"},
          {"task_state_msgs/TaskState", "12e2b939762eccd12758c38a0293b215"},
          {"teleop_msgs/VRState", "00c31bc920504fb5ee84c550ff4ee100"},
      };
      if (count != nullptr)
      {
        *count = sizeof(kTable) / sizeof(kTable[0]);
      }
      return kTable;
    }
  } // namespace msg
} // namespace limxsdk

#endif // _LIMX_SDK_MSG_TYPE_REGISTRY_H_
