package(
    default_visibility = ["//visibility:public"],
)

exports_files([
    "aim_master.proto",
    "mc_remote_channel.proto",
    "mc_remote_service.proto",
    "quest_pro_controller.proto",
    "remote_command.proto",
    "universal_gamepad.proto",
])
