/**
 * @file HeightEstimateResult.h
 *
 * @brief Generated mirror of the mros `perception_msgs/HeightEstimateResult` message.
 *
 * THIS FILE IS GENERATED BY tools/limxsdk-gen/limxsdk_gen.py - DO NOT EDIT.
 * Regenerate it instead of patching it; hand edits are lost on the next run.
 *
 * © [2025] LimX Dynamics Technology Co., Ltd. All rights reserved.
 */

#ifndef _LIMX_SDK_MSG_PERCEPTION_MSGS_HEIGHTESTIMATERESULT_H_
#define _LIMX_SDK_MSG_PERCEPTION_MSGS_HEIGHTESTIMATERESULT_H_

#include <array>
#include <cstddef>
#include <cstdint>
#include <string>
#include <vector>

#include "limxsdk/codec/codec.h"
#include "limxsdk/msg/std_msgs/Header.h"

namespace limxsdk
{
  namespace msg
  {
    namespace perception_msgs
    {
      /// @brief Mirror of the mros `perception_msgs/HeightEstimateResult` message.
      struct HeightEstimateResult
      {
        static constexpr const char *TYPE = "perception_msgs/HeightEstimateResult";
        static constexpr const char *MD5 = "cf11f0059969194da977bc733040e097";

        /// @brief ROS concatenated definition, as reported by mros.
        static const char *definition() { return "std_msgs/Header header\nfloat64 estimate_height\nstring desc\n================================================================================\nMSG: std_msgs/Header\nuint32 seq\ntime stamp\nstring frame_id\n"; }

        ::limxsdk::msg::std_msgs::Header header;
        double estimate_height = 0;
        std::string desc;

        /// @brief Decode one frame; false means discard the whole message.
        bool decode(::limxsdk::codec::Reader &reader)
        {
          if (!header.decode(reader))
          {
            return false;
          }
          if (!reader.read(estimate_height))
          {
            return false;
          }
          if (!reader.read(desc))
          {
            return false;
          }
          return !reader.failed();
        }

        /// @brief Encode into a buffer of at least encodedSize() bytes.
        bool encode(::limxsdk::codec::Writer &writer) const
        {
          if (!header.encode(writer))
          {
            return false;
          }
          if (!writer.write(estimate_height))
          {
            return false;
          }
          if (!writer.write(desc))
          {
            return false;
          }
          return !writer.failed();
        }

        /// @brief Exact number of bytes encode() will write.
        std::size_t encodedSize() const
        {
          std::size_t total = 12;
          total += header.encodedSize();
          total += desc.size();
          return total;
        }

        /// @brief Smallest possible encoding, used to reject bogus array lengths.
        static std::size_t minEncodedSize()
        {
          return 12 + ::limxsdk::msg::std_msgs::Header::minEncodedSize();
        }
      };
    } // namespace perception_msgs
  } // namespace msg
} // namespace limxsdk

#endif // _LIMX_SDK_MSG_PERCEPTION_MSGS_HEIGHTESTIMATERESULT_H_
