controller_manager:
    ros__parameters:
        update_rate: 500  # Hz
        use_sim_time: true

        joint_state_broadcaster:
            type: joint_state_broadcaster/JointStateBroadcaster

        imu_sensor_broadcaster:
            type: imu_sensor_broadcaster/ImuSensorBroadcaster

        robot_joint_controller:
            type: effort_controllers/JointGroupEffortController

robot_joint_controller:
    ros__parameters:
        joints:
            - fl_hipx_joint
            - fl_hipy_joint
            - fl_knee_joint
            - fl_wheel_joint
            - fr_hipx_joint
            - fr_hipy_joint
            - fr_knee_joint
            - fr_wheel_joint
            - hl_hipx_joint
            - hl_hipy_joint
            - hl_knee_joint
            - hl_wheel_joint
            - hr_hipx_joint
            - hr_hipy_joint
            - hr_knee_joint
            - hr_wheel_joint

imu_sensor_broadcaster:
    ros__parameters:
        sensor_name: "imu_sensor"
        frame_id: imu_link
