load("@rules_pkg//pkg:pkg.bzl", "pkg_tar")
load("@integration//rules/utils:flattern_tar.bzl", "flatten_tar")
load("@integration//rules/utils:cc_single.bzl", "cc_single_library")

package(default_visibility = ["//visibility:public"])

alias(
    name = "aimrte",
    actual = "//src/all_in_one:all_in_one",
)

pkg_tar(
    name = "aimrte_plugins_tar",
    srcs = [
        "//plugin/monitor/core:aimrt_monitor_plugin",
    ],
    extension = "tar",
    include_runfiles = True,
    mode = "0755",
    tags = ["tar"],
)

flatten_tar(
    name = "aimrte_plugins_flatten_tar",
    src = ":aimrte_plugins_tar",
    prefix = "bin",
)

pkg_tar(
    name = "aimrte_typesupport_tar",
    srcs = [
        "//aimdk/protocol/common:aimdk_protocol_common_type_support",
        "//aimdk/protocol/demo:aimdk_protocol_demo_channel_type_support",
        "//aimdk/protocol/hal/bms:aimdk_protocol_hal_bms_channel_type_support",
        "//aimdk/protocol/hal/hand:aimdk_protocol_agi_claw_type_support",
        "//aimdk/protocol/hal/hand:aimdk_protocol_agi_hand_type_support",
        "//aimdk/protocol/hal/hand:aimdk_protocol_hand_channel_type_support",
        "//aimdk/protocol/hal/hand:aimdk_protocol_inspire_type_support",
        "//aimdk/protocol/hal/hand:aimdk_protocol_jodell_type_support",
        "//aimdk/protocol/hal/joint:aimdk_protocol_joint_channel_type_support",
        "//aimdk/protocol/hal/joint:aimdk_protocol_joint_msgs_type_support",
        "//aimdk/protocol/hal/light:aimdk_protocol_hal_light_channel_type_support",
        "//aimdk/protocol/hal/light:aimdk_protocol_light_type_support",
        "//aimdk/protocol/hal/neck:aimdk_protocol_neck_type_support",
        "//aimdk/protocol/hal/pose:aimdk_protocol_pose_msgs_type_support",
        "//aimdk/protocol/hal/power:aimdk_protocol_power_msgs_type_support",
        "//aimdk/protocol/hal/sensors:aimdk_protocol_color_depth_image_channel_type_support",
        "//aimdk/protocol/hal/sensors:aimdk_protocol_image_channel_type_support",
        "//aimdk/protocol/hal/sensors:aimdk_protocol_sensors_msgs_type_support",
        "//aimdk/protocol/hal/state:aimdk_protocol_emergency_state_type_support",
        "//aimdk/protocol/hal/state:aimdk_protocol_hal_state_channel_type_support",
        "//aimdk/protocol/hal/state:aimdk_protocol_operation_mode_type_support",
        "//aimdk/protocol/hal/temp:aimdk_protocol_hal_temp_channel_type_support",
        "//aimdk/protocol/hal/temp:aimdk_protocol_temp_msgs_type_support",
        "//aimdk/protocol/hal/temp:aimdk_protocol_temp_type_support",
        "//aimdk/protocol/hds:aimdk_protocol_alert_channel_type_support",
        "//aimdk/protocol/hds:aimdk_protocol_alert_type_support",
        "//aimdk/protocol/hds:aimdk_protocol_exception_channel_type_support",
        "//aimdk/protocol/hds:aimdk_protocol_exception_type_support",
        "//aimdk/protocol/hds:aimdk_protocol_fallback_channel_type_support",
        "//aimdk/protocol/hds:aimdk_protocol_hds_msgs_type_support",
        "//aimdk/protocol/hds:aimdk_protocol_health_channel_type_support",
        "//aimdk/protocol/hds:aimdk_protocol_health_type_support",
        "//aimdk/protocol/hds:aimdk_protocol_system_status_type_support",
        "//aimdk/protocol/hds/process:aimdk_protocol_process_health_channel_type_support",
        "//aimdk/protocol/hds/process:aimdk_protocol_process_health_type_support",
        "//aimdk/protocol/hds/process:aimdk_protocol_process_heartbeat_channel_type_support",
        "//aimdk/protocol/hds/process:aimdk_protocol_process_heartbeat_type_support",
        "//aimdk/protocol/mc/action:aimdk_protocol_mc_action_cmd_type_support",
        "//aimdk/protocol/mc/action:aimdk_protocol_mc_action_type_support",
        "//aimdk/protocol/mc/base:aimdk_protocol_jaka_ctrl_type_support",
        "//aimdk/protocol/mc/base:aimdk_protocol_mc_base_channel_type_support",
        "//aimdk/protocol/mc/base:aimdk_protocol_mc_state_type_support",
        "//aimdk/protocol/mc/base:aimdk_protocol_work_mode_type_support",
        "//aimdk/protocol/mc/common:aimdk_protocol_mc_arm_type_support",
        "//aimdk/protocol/mc/common:aimdk_protocol_move_pose_mode_type_support",
        "//aimdk/protocol/mc/common:aimdk_protocol_planning_type_support",
        "//aimdk/protocol/mc/data:aimdk_protocol_mc_data_arm_type_support",
        "//aimdk/protocol/mc/data:aimdk_protocol_mc_joint_type_support",
        "//aimdk/protocol/mc/data:aimdk_protocol_mc_mgpt_type_support",
        "//aimdk/protocol/mc/data:aimdk_protocol_mc_planning_type_support",
        "//aimdk/protocol/mc/data:aimdk_protocol_mc_tcp_type_support",
        "//aimdk/protocol/mc/force:aimdk_protocol_mc_force_primitive_type_support",
        "//aimdk/protocol/mc/kinematics:aimdk_protocol_foot_kine_type_support",
        "//aimdk/protocol/mc/kinematics:aimdk_protocol_kine_forward_type_support",
        "//aimdk/protocol/mc/kinematics:aimdk_protocol_kine_inverse_type_support",
        "//aimdk/protocol/mc/kinematics:aimdk_protocol_mc_kinematics_channel_type_support",
        "//aimdk/protocol/mc/motion:aimdk_protocol_locomotion_type_support",
        "//aimdk/protocol/mc/motion:aimdk_protocol_mc_adjust_type_support",
        "//aimdk/protocol/mc/motion:aimdk_protocol_mc_motion_channel_type_support",
        "//aimdk/protocol/mc/motion:aimdk_protocol_mc_motion_planning_type_support",
        "//aimdk/protocol/mc/motion:aimdk_protocol_mc_motion_stand_type_support",
        "//aimdk/protocol/mc/motion:aimdk_protocol_mc_motion_waist_type_support",
        "//aimdk/protocol/mc/motion:aimdk_protocol_motion_param_type_support",
        "//aimdk/protocol/mc/motion:aimdk_protocol_move_type_support",
        "//aimdk/protocol/mc/motion:aimdk_protocol_movj_type_support",
        "//aimdk/protocol/mc/remote:aimdk_protocol_aim_master_type_support",
        "//aimdk/protocol/mc/remote:aimdk_protocol_mc_remote_channel_type_support",
        "//aimdk/protocol/mc/remote:aimdk_protocol_quest_pro_controller_type_support",
        "//aimdk/protocol/mc/remote:aimdk_protocol_remote_command_type_support",
        "//aimdk/protocol/mc/remote:aimdk_protocol_universal_gamepad_type_support",
        "//aimdk/protocol/mc/test:aimdk_protocol_mc_test_type_support",
        "//aimdk/protocol/mc/tools:aimdk_protocol_mc_tools_cfg_type_support",
        "//aimdk/protocol/trace:aimdk_protocol_event_channel_type_support",
        "//ros2/common:ros2_common_type_support",
        "//ros2/demo:ros2_demo_msgs_type_support",
        "//ros2/record_playback:ros2_record_playback_msgs_type_support",
    ],
    extension = "tar",
    include_runfiles = True,
    mode = "0755",
    tags = ["tar"],
)

flatten_tar(
    name = "aimrte_typesupport_flatten_tar",
    src = ":aimrte_typesupport_tar",
    prefix = "bin",
)


pkg_tar(
    name = "record_playback_module_tar",
    srcs = [
    ],
    extension = "tar",
    mode = "0755",
    strip_prefix = ".",
    tags = ["tar"],
    deps = [
        "//tool/record_playback/src:record_playback_bin_flatten_tar",
        "//tool/record_playback/src:record_playback_without_bin_tar",
        "@integration//:all_plugins_tar",
        "@integration//:all_typesupport_tar",
        "@integration//:mcap_cli_tar",
    ],
)
pkg_tar(
    name = "example_module_tar",
    srcs = [
    ],
    extension = "tar",
    mode = "0755",
    strip_prefix = ".",
    tags = ["tar"],
    deps = [
        "//example/module/ping:ping_flatten_bin_tar",
        "//example/module/ping:ping_without_bin_tar",
        "//example/module/pong:pong_flatten_bin_tar",
        "//example/module/pong:pong_without_bin_tar",
        "//example/program:program_flatten_bin_tar",
        "//example/program:program_without_bin_tar",
        "//example/cfg:cfg_flatten_bin_tar",
        "//example/cfg:cfg_without_bin_tar",
        "@integration//:all_plugins_tar",
        "//src/main:aimrte_flatten_tar",
    ],
)


cc_library(
    name = "aimdk_protocol_libs",
    deps = [
        "//aimdk/protocol/common:box_cc_proto",
        "//aimdk/protocol/common:common_cc_proto",
        "//aimdk/protocol/common:control_source_cc_proto",
        "//aimdk/protocol/common:header_cc_proto",
        "//aimdk/protocol/common:image_cc_proto",
        "//aimdk/protocol/common:io_packet_cc_proto",
        "//aimdk/protocol/common:joint_cc_proto",
        "//aimdk/protocol/common:mocapjointstate_cc_proto",
        "//aimdk/protocol/common:odometry_cc_proto",
        "//aimdk/protocol/common:pixel_pose_cc_proto",
        "//aimdk/protocol/common:qr_pose_cc_proto",
        "//aimdk/protocol/common:quaternion_cc_proto",
        "//aimdk/protocol/common:rpc_cc_proto",
        "//aimdk/protocol/common:rpy_cc_proto",
        "//aimdk/protocol/common:scalar_trajectory_cc_proto",
        "//aimdk/protocol/common:se2_acceleration_cc_proto",
        "//aimdk/protocol/common:se2_pose_cc_proto",
        "//aimdk/protocol/common:se2_velocity_cc_proto",
        "//aimdk/protocol/common:se3_acceleration_cc_proto",
        "//aimdk/protocol/common:se3_pose_cc_proto",
        "//aimdk/protocol/common:se3_trajectory_cc_proto",
        "//aimdk/protocol/common:se3_velocity_cc_proto",
        "//aimdk/protocol/common:timestamp_cc_proto",
        "//aimdk/protocol/common:twist_cc_proto",
        "//aimdk/protocol/common:vec2_cc_proto",
        "//aimdk/protocol/common:vec3_cc_proto",
        "//aimdk/protocol/common:wrench_cc_proto",
        "//aimdk/protocol/demo:demo_channel_cc_proto",
        "//aimdk/protocol/demo:demo_service_rpc",
        "//aimdk/protocol/em:api_rpc",
        "//aimdk/protocol/hal/bms:hal_bms_channel_cc_proto",
        "//aimdk/protocol/hal/bms:hal_bms_service_rpc",
        "//aimdk/protocol/hal/hand:hal_hand_service_rpc",
        "//aimdk/protocol/hal/hand:hand_cc_proto",
        "//aimdk/protocol/hal/hand:hand_channel_cc_proto",
        "//aimdk/protocol/hal/joint:joint_channel_cc_proto",
        "//aimdk/protocol/hal/light:hal_light_channel_cc_proto",
        "//aimdk/protocol/hal/light:hal_light_service_rpc",
        "//aimdk/protocol/hal/neck:hal_neck_service_rpc",
        "//aimdk/protocol/hal/power:hal_power_service_rpc",
        "//aimdk/protocol/hal/sensors:cameras_intrinsic_rpc",
        "//aimdk/protocol/hal/state:hal_emergency_service_rpc",
        "//aimdk/protocol/hal/state:hal_state_channel_cc_proto",
        "//aimdk/protocol/hal/state:mcu_state_cc_proto",
        "//aimdk/protocol/hal/temp:hal_temp_channel_cc_proto",
        "//aimdk/protocol/hal/temp:hal_temp_service_rpc",
        "//aimdk/protocol/hds:alert_channel_cc_proto",
        "//aimdk/protocol/hds:exception_channel_cc_proto",
        "//aimdk/protocol/hds:fallback_channel_cc_proto",
        "//aimdk/protocol/hds:hds_service_rpc",
        "//aimdk/protocol/hds:health_channel_cc_proto",
        "//aimdk/protocol/hds:system_status_cc_proto",
        "//aimdk/protocol/hds/monitor:monitor_service_rpc",
        "//aimdk/protocol/hds/process:process_health_channel_cc_proto",
        "//aimdk/protocol/hds/process:process_heartbeat_channel_cc_proto",
        "//aimdk/protocol/mc/action:mc_action_cc_proto",
        "//aimdk/protocol/mc/action:mc_action_service_rpc",
        "//aimdk/protocol/mc/base:mc_base_channel_cc_proto",
        "//aimdk/protocol/mc/base:mc_base_service_rpc",
        "//aimdk/protocol/mc/common:planning_cc_proto",
        "//aimdk/protocol/mc/data:mc_data_service_rpc",
        "//aimdk/protocol/mc/force:mc_force_primitive_cc_proto",
        "//aimdk/protocol/mc/force:mc_force_service_rpc",
        "//aimdk/protocol/mc/kinematics:foot_kine_cc_proto",
        "//aimdk/protocol/mc/kinematics:mc_kinematics_channel_cc_proto",
        "//aimdk/protocol/mc/motion:locomotion_cc_proto",
        "//aimdk/protocol/mc/motion:mc_motion_channel_cc_proto",
        "//aimdk/protocol/mc/motion:mc_motion_service_rpc",
        "//aimdk/protocol/mc/motion:waist_cc_proto",
        "//aimdk/protocol/mc/remote:mc_remote_channel_cc_proto",
        "//aimdk/protocol/mc/test:mc_test_service_rpc",
        "//aimdk/protocol/mc/tools:mc_tools_service_rpc",
        "//aimdk/protocol/trace:event_channel_cc_proto",
    ],
)

cc_library(
    name = "ros2_libs",
    deps = [
        "//aimdk/protocol/hal/joint:joint_msgs_lib",
        "//aimdk/protocol/hal/pose:pose_msgs_lib",
        "//aimdk/protocol/hal/power:power_msgs_lib",
        "//aimdk/protocol/hal/sensors:sensors_msgs_lib",
        "//aimdk/protocol/hal/temp:temp_msgs_lib",
        "//ros2/demo:demo_msgs_rpc",
        "//ros2/record_playback/GetActionList:record_playback_msgs_rpc",
        "//ros2/record_playback/GetBagList:record_playback_msgs_rpc",
        "//ros2/record_playback/GetUploadAllowed:record_playback_msgs_rpc",
        "//ros2/record_playback/StartRecord:record_playback_msgs_rpc",
        "//ros2/record_playback/StopRecord:record_playback_msgs_rpc",
        "//ros2/record_playback/UpdateRecordAction:record_playback_msgs_rpc",
        "@ros2_rosidl//:rosidl_runtime_cpp",
    ],
)

cc_single_library(
    name = "libaimrt_comm",
    deps = [
        ":aimdk_protocol_libs",
        ":ros2_libs",
        "//:aimrte",
        "//src/all_in_one",
        "//src/common",
        "//src/concepts",
        "//src/container",
        "//src/convert",
        "//src/core",
        "//src/ctx",
        "//src/database",
        "//src/dynamic_lib",
        "//src/hds",
        "//src/macro",
        "//src/match",
        "//src/minidump",
        "//src/module",
        "//src/panic",
        "//src/prelude",
        "//src/private/backward",
        "//src/program",
        "//src/program/app_mode",
        "//src/program/details",
        "//src/program/pkg_mode",
        "//src/ref",
        "//src/register_backward",
        "//src/res",
        "//src/runtime/base",
        "//src/runtime/impl:aimrte_runtime",
        "//src/runtime/interface",
        "//src/runtime/internal",
        "//src/sync",
        "//src/sys",
        "//src/test",
        "//src/trace",
        "//src/trait",
        "//src/utils",
    ],
)
