/**
 * @file DiagnosticValue.h
 *
 * @brief Generated mirror of the mros `diagnostic_msgs/DiagnosticValue` message.
 *
 * THIS FILE IS GENERATED BY tools/limxsdk-gen/limxsdk_gen.py - DO NOT EDIT.
 * Regenerate it instead of patching it; hand edits are lost on the next run.
 *
 * © [2025] LimX Dynamics Technology Co., Ltd. All rights reserved.
 */

#ifndef _LIMX_SDK_MSG_DIAGNOSTIC_MSGS_DIAGNOSTICVALUE_H_
#define _LIMX_SDK_MSG_DIAGNOSTIC_MSGS_DIAGNOSTICVALUE_H_

#include <array>
#include <cstddef>
#include <cstdint>
#include <string>
#include <vector>

#include "limxsdk/codec/codec.h"
#include "limxsdk/msg/std_msgs/Header.h"

namespace limxsdk
{
  namespace msg
  {
    namespace diagnostic_msgs
    {
      /// @brief Mirror of the mros `diagnostic_msgs/DiagnosticValue` message.
      struct DiagnosticValue
      {
        static constexpr const char *TYPE = "diagnostic_msgs/DiagnosticValue";
        static constexpr const char *MD5 = "879d5c821998ca0ab6e3520e8c63e5fc";
        static constexpr int32_t OK = 0;
        static constexpr int32_t WARN = 1;
        static constexpr int32_t ERROR = 2;

        /// @brief ROS concatenated definition, as reported by mros.
        static const char *definition() { return "std_msgs/Header header\nint32 OK=0\nint32 WARN=1\nint32 ERROR=2\nint32 level\nstring name\nint32 code\nstring message\n================================================================================\nMSG: std_msgs/Header\nuint32 seq\ntime stamp\nstring frame_id\n"; }

        ::limxsdk::msg::std_msgs::Header header;
        int32_t level = 0;
        std::string name;
        int32_t code = 0;
        std::string message;

        /// @brief Decode one frame; false means discard the whole message.
        bool decode(::limxsdk::codec::Reader &reader)
        {
          if (!header.decode(reader))
          {
            return false;
          }
          if (!reader.read(level))
          {
            return false;
          }
          if (!reader.read(name))
          {
            return false;
          }
          if (!reader.read(code))
          {
            return false;
          }
          if (!reader.read(message))
          {
            return false;
          }
          return !reader.failed();
        }

        /// @brief Encode into a buffer of at least encodedSize() bytes.
        bool encode(::limxsdk::codec::Writer &writer) const
        {
          if (!header.encode(writer))
          {
            return false;
          }
          if (!writer.write(level))
          {
            return false;
          }
          if (!writer.write(name))
          {
            return false;
          }
          if (!writer.write(code))
          {
            return false;
          }
          if (!writer.write(message))
          {
            return false;
          }
          return !writer.failed();
        }

        /// @brief Exact number of bytes encode() will write.
        std::size_t encodedSize() const
        {
          std::size_t total = 16;
          total += header.encodedSize();
          total += name.size();
          total += message.size();
          return total;
        }

        /// @brief Smallest possible encoding, used to reject bogus array lengths.
        static std::size_t minEncodedSize()
        {
          return 16 + ::limxsdk::msg::std_msgs::Header::minEncodedSize();
        }
      };
    } // namespace diagnostic_msgs
  } // namespace msg
} // namespace limxsdk

#endif // _LIMX_SDK_MSG_DIAGNOSTIC_MSGS_DIAGNOSTICVALUE_H_
