/**
 * @file CameraCtrl.h
 *
 * @brief Generated mirror of the mros `ipcamera_msgs/CameraCtrl` message.
 *
 * THIS FILE IS GENERATED BY tools/limxsdk-gen/limxsdk_gen.py - DO NOT EDIT.
 * Regenerate it instead of patching it; hand edits are lost on the next run.
 *
 * © [2025] LimX Dynamics Technology Co., Ltd. All rights reserved.
 */

#ifndef _LIMX_SDK_MSG_IPCAMERA_MSGS_CAMERACTRL_H_
#define _LIMX_SDK_MSG_IPCAMERA_MSGS_CAMERACTRL_H_

#include <array>
#include <cstddef>
#include <cstdint>
#include <string>
#include <vector>

#include "limxsdk/codec/codec.h"

namespace limxsdk
{
  namespace msg
  {
    namespace ipcamera_msgs
    {
      /// @brief Mirror of the mros `ipcamera_msgs/CameraCtrl` message.
      struct CameraCtrl
      {
        static constexpr const char *TYPE = "ipcamera_msgs/CameraCtrl";
        static constexpr const char *MD5 = "41cfee5ccb3e668affc169faf932fb42";
        static constexpr int32_t IPC_CMD_UP = 0;
        static constexpr int32_t IPC_CMD_DOWN = 1;
        static constexpr int32_t IPC_CMD_LEFT = 2;
        static constexpr int32_t IPC_CMD_RIGHT = 3;
        static constexpr int32_t IPC_CMD_ZOOM_UP_START = 4;
        static constexpr int32_t IPC_CMD_ZOOM_UP_STOP = 6;
        static constexpr int32_t IPC_CMD_ZOOM_DOWN_START = 7;
        static constexpr int32_t IPC_CMD_ZOOM_DOWN_STOP = 8;
        static constexpr int32_t IPC_CMD_SET_LOCK_MODE = 9;
        static constexpr int32_t IPC_CMD_SET_FOLLOW_MODE = 10;

        /// @brief ROS concatenated definition, as reported by mros.
        static const char *definition() { return "int32 IPC_CMD_UP = 0\nint32 IPC_CMD_DOWN = 1\nint32 IPC_CMD_LEFT = 2\nint32 IPC_CMD_RIGHT = 3\nint32 IPC_CMD_ZOOM_UP_START = 4\nint32 IPC_CMD_ZOOM_UP_STOP = 6\nint32 IPC_CMD_ZOOM_DOWN_START = 7\nint32 IPC_CMD_ZOOM_DOWN_STOP = 8\nint32 IPC_CMD_SET_LOCK_MODE = 9\nint32 IPC_CMD_SET_FOLLOW_MODE = 10\nint32 cmd\n"; }

        int32_t cmd = 0;

        /// @brief Decode one frame; false means discard the whole message.
        bool decode(::limxsdk::codec::Reader &reader)
        {
          if (!reader.read(cmd))
          {
            return false;
          }
          return !reader.failed();
        }

        /// @brief Encode into a buffer of at least encodedSize() bytes.
        bool encode(::limxsdk::codec::Writer &writer) const
        {
          if (!writer.write(cmd))
          {
            return false;
          }
          return !writer.failed();
        }

        /// @brief Exact number of bytes encode() will write.
        std::size_t encodedSize() const
        {
          return 4;
        }

        /// @brief Smallest possible encoding, used to reject bogus array lengths.
        static std::size_t minEncodedSize()
        {
          return 4;
        }
      };
    } // namespace ipcamera_msgs
  } // namespace msg
} // namespace limxsdk

#endif // _LIMX_SDK_MSG_IPCAMERA_MSGS_CAMERACTRL_H_
