// Copyright (c) 2025, AgiBot Inc.
// All rights reserved.

#pragma once

#include "./count.h"

/**
 * \brief Concatenating multiple names into a new name.
 */
#define AIMRTE_CONCAT(...) AIMRTE_DETAILS_CONCAT_CALLER(AIMRTE_DETAILS_CONCAT_, AIMRTE_COUNT_ARGS(__VA_ARGS__))(__VA_ARGS__)

// A helper function ensures that the x- and y-parameters are fully expanded before the splice is performed.
#define AIMRTE_DETAILS_CONCAT(x, y) x##y
#define AIMRTE_DETAILS_CONCAT_CALLER(x, y) AIMRTE_DETAILS_CONCAT(x, y)

// Macro implementations with different number of parameters
#define AIMRTE_DETAILS_CONCAT_2(x, y) AIMRTE_DETAILS_CONCAT_CALLER(x, y)
#define AIMRTE_DETAILS_CONCAT_3(x, ...) AIMRTE_DETAILS_CONCAT_CALLER(x, AIMRTE_DETAILS_CONCAT_2(__VA_ARGS__))
#define AIMRTE_DETAILS_CONCAT_4(x, ...) AIMRTE_DETAILS_CONCAT_CALLER(x, AIMRTE_DETAILS_CONCAT_3(__VA_ARGS__))
#define AIMRTE_DETAILS_CONCAT_5(x, ...) AIMRTE_DETAILS_CONCAT_CALLER(x, AIMRTE_DETAILS_CONCAT_4(__VA_ARGS__))
#define AIMRTE_DETAILS_CONCAT_6(x, ...) AIMRTE_DETAILS_CONCAT_CALLER(x, AIMRTE_DETAILS_CONCAT_5(__VA_ARGS__))
#define AIMRTE_DETAILS_CONCAT_7(x, ...) AIMRTE_DETAILS_CONCAT_CALLER(x, AIMRTE_DETAILS_CONCAT_6(__VA_ARGS__))
#define AIMRTE_DETAILS_CONCAT_8(x, ...) AIMRTE_DETAILS_CONCAT_CALLER(x, AIMRTE_DETAILS_CONCAT_7(__VA_ARGS__))
#define AIMRTE_DETAILS_CONCAT_9(x, ...) AIMRTE_DETAILS_CONCAT_CALLER(x, AIMRTE_DETAILS_CONCAT_8(__VA_ARGS__))
#define AIMRTE_DETAILS_CONCAT_10(x, ...) AIMRTE_DETAILS_CONCAT_CALLER(x, AIMRTE_DETAILS_CONCAT_9(__VA_ARGS__))
#define AIMRTE_DETAILS_CONCAT_11(x, ...) AIMRTE_DETAILS_CONCAT_CALLER(x, AIMRTE_DETAILS_CONCAT_10(__VA_ARGS__))
#define AIMRTE_DETAILS_CONCAT_12(x, ...) AIMRTE_DETAILS_CONCAT_CALLER(x, AIMRTE_DETAILS_CONCAT_11(__VA_ARGS__))
#define AIMRTE_DETAILS_CONCAT_13(x, ...) AIMRTE_DETAILS_CONCAT_CALLER(x, AIMRTE_DETAILS_CONCAT_12(__VA_ARGS__))
#define AIMRTE_DETAILS_CONCAT_14(x, ...) AIMRTE_DETAILS_CONCAT_CALLER(x, AIMRTE_DETAILS_CONCAT_13(__VA_ARGS__))
#define AIMRTE_DETAILS_CONCAT_15(x, ...) AIMRTE_DETAILS_CONCAT_CALLER(x, AIMRTE_DETAILS_CONCAT_14(__VA_ARGS__))
#define AIMRTE_DETAILS_CONCAT_16(x, ...) AIMRTE_DETAILS_CONCAT_CALLER(x, AIMRTE_DETAILS_CONCAT_15(__VA_ARGS__))
#define AIMRTE_DETAILS_CONCAT_17(x, ...) AIMRTE_DETAILS_CONCAT_CALLER(x, AIMRTE_DETAILS_CONCAT_16(__VA_ARGS__))
#define AIMRTE_DETAILS_CONCAT_18(x, ...) AIMRTE_DETAILS_CONCAT_CALLER(x, AIMRTE_DETAILS_CONCAT_17(__VA_ARGS__))
#define AIMRTE_DETAILS_CONCAT_19(x, ...) AIMRTE_DETAILS_CONCAT_CALLER(x, AIMRTE_DETAILS_CONCAT_18(__VA_ARGS__))
#define AIMRTE_DETAILS_CONCAT_20(x, ...) AIMRTE_DETAILS_CONCAT_CALLER(x, AIMRTE_DETAILS_CONCAT_19(__VA_ARGS__))
#define AIMRTE_DETAILS_CONCAT_21(x, ...) AIMRTE_DETAILS_CONCAT_CALLER(x, AIMRTE_DETAILS_CONCAT_20(__VA_ARGS__))
#define AIMRTE_DETAILS_CONCAT_22(x, ...) AIMRTE_DETAILS_CONCAT_CALLER(x, AIMRTE_DETAILS_CONCAT_21(__VA_ARGS__))
#define AIMRTE_DETAILS_CONCAT_23(x, ...) AIMRTE_DETAILS_CONCAT_CALLER(x, AIMRTE_DETAILS_CONCAT_22(__VA_ARGS__))
#define AIMRTE_DETAILS_CONCAT_24(x, ...) AIMRTE_DETAILS_CONCAT_CALLER(x, AIMRTE_DETAILS_CONCAT_23(__VA_ARGS__))
#define AIMRTE_DETAILS_CONCAT_25(x, ...) AIMRTE_DETAILS_CONCAT_CALLER(x, AIMRTE_DETAILS_CONCAT_24(__VA_ARGS__))
#define AIMRTE_DETAILS_CONCAT_26(x, ...) AIMRTE_DETAILS_CONCAT_CALLER(x, AIMRTE_DETAILS_CONCAT_25(__VA_ARGS__))
#define AIMRTE_DETAILS_CONCAT_27(x, ...) AIMRTE_DETAILS_CONCAT_CALLER(x, AIMRTE_DETAILS_CONCAT_26(__VA_ARGS__))
#define AIMRTE_DETAILS_CONCAT_28(x, ...) AIMRTE_DETAILS_CONCAT_CALLER(x, AIMRTE_DETAILS_CONCAT_27(__VA_ARGS__))
#define AIMRTE_DETAILS_CONCAT_29(x, ...) AIMRTE_DETAILS_CONCAT_CALLER(x, AIMRTE_DETAILS_CONCAT_28(__VA_ARGS__))
#define AIMRTE_DETAILS_CONCAT_30(x, ...) AIMRTE_DETAILS_CONCAT_CALLER(x, AIMRTE_DETAILS_CONCAT_29(__VA_ARGS__))
#define AIMRTE_DETAILS_CONCAT_31(x, ...) AIMRTE_DETAILS_CONCAT_CALLER(x, AIMRTE_DETAILS_CONCAT_30(__VA_ARGS__))
#define AIMRTE_DETAILS_CONCAT_32(x, ...) AIMRTE_DETAILS_CONCAT_CALLER(x, AIMRTE_DETAILS_CONCAT_31(__VA_ARGS__))
#define AIMRTE_DETAILS_CONCAT_33(x, ...) AIMRTE_DETAILS_CONCAT_CALLER(x, AIMRTE_DETAILS_CONCAT_32(__VA_ARGS__))
#define AIMRTE_DETAILS_CONCAT_34(x, ...) AIMRTE_DETAILS_CONCAT_CALLER(x, AIMRTE_DETAILS_CONCAT_33(__VA_ARGS__))
#define AIMRTE_DETAILS_CONCAT_35(x, ...) AIMRTE_DETAILS_CONCAT_CALLER(x, AIMRTE_DETAILS_CONCAT_34(__VA_ARGS__))
#define AIMRTE_DETAILS_CONCAT_36(x, ...) AIMRTE_DETAILS_CONCAT_CALLER(x, AIMRTE_DETAILS_CONCAT_35(__VA_ARGS__))
#define AIMRTE_DETAILS_CONCAT_37(x, ...) AIMRTE_DETAILS_CONCAT_CALLER(x, AIMRTE_DETAILS_CONCAT_36(__VA_ARGS__))
#define AIMRTE_DETAILS_CONCAT_38(x, ...) AIMRTE_DETAILS_CONCAT_CALLER(x, AIMRTE_DETAILS_CONCAT_37(__VA_ARGS__))
#define AIMRTE_DETAILS_CONCAT_39(x, ...) AIMRTE_DETAILS_CONCAT_CALLER(x, AIMRTE_DETAILS_CONCAT_38(__VA_ARGS__))
#define AIMRTE_DETAILS_CONCAT_40(x, ...) AIMRTE_DETAILS_CONCAT_CALLER(x, AIMRTE_DETAILS_CONCAT_39(__VA_ARGS__))
#define AIMRTE_DETAILS_CONCAT_41(x, ...) AIMRTE_DETAILS_CONCAT_CALLER(x, AIMRTE_DETAILS_CONCAT_40(__VA_ARGS__))
#define AIMRTE_DETAILS_CONCAT_42(x, ...) AIMRTE_DETAILS_CONCAT_CALLER(x, AIMRTE_DETAILS_CONCAT_41(__VA_ARGS__))
#define AIMRTE_DETAILS_CONCAT_43(x, ...) AIMRTE_DETAILS_CONCAT_CALLER(x, AIMRTE_DETAILS_CONCAT_42(__VA_ARGS__))
#define AIMRTE_DETAILS_CONCAT_44(x, ...) AIMRTE_DETAILS_CONCAT_CALLER(x, AIMRTE_DETAILS_CONCAT_43(__VA_ARGS__))
#define AIMRTE_DETAILS_CONCAT_45(x, ...) AIMRTE_DETAILS_CONCAT_CALLER(x, AIMRTE_DETAILS_CONCAT_44(__VA_ARGS__))
#define AIMRTE_DETAILS_CONCAT_46(x, ...) AIMRTE_DETAILS_CONCAT_CALLER(x, AIMRTE_DETAILS_CONCAT_45(__VA_ARGS__))
#define AIMRTE_DETAILS_CONCAT_47(x, ...) AIMRTE_DETAILS_CONCAT_CALLER(x, AIMRTE_DETAILS_CONCAT_46(__VA_ARGS__))
#define AIMRTE_DETAILS_CONCAT_48(x, ...) AIMRTE_DETAILS_CONCAT_CALLER(x, AIMRTE_DETAILS_CONCAT_47(__VA_ARGS__))
#define AIMRTE_DETAILS_CONCAT_49(x, ...) AIMRTE_DETAILS_CONCAT_CALLER(x, AIMRTE_DETAILS_CONCAT_48(__VA_ARGS__))
