load("@integration//rules/utils:proto.bzl", "protobuf_utils")

package(default_visibility = ["//visibility:public"])

protobuf_utils(
    name = "time_manipulator_plugin_utils",
    dep_protos = [
    ],
    is_rpc = True,
    only_aimrt_rpc = True,
    output_proto_name = "time_manipulator_plugin_new",
    proto = "time_manipulator.proto",
)
