package(
    default_visibility = ["//visibility:public"],
)

exports_files([
    "FootSensor.msg",
    "FootSensorState.msg",
    "ForceSensor.msg",
    "ForceSensorState.msg",
    "LivoxPoint.msg",
    "LivoxPointCloud.msg",
])

filegroup(
    name = "ros2_files",
    srcs = glob([
        "*.msg",
    ]),
)
