/**
 * @file VRState.h
 *
 * @brief Generated mirror of the mros `teleop_msgs/VRState` message.
 *
 * THIS FILE IS GENERATED BY tools/limxsdk-gen/limxsdk_gen.py - DO NOT EDIT.
 * Regenerate it instead of patching it; hand edits are lost on the next run.
 *
 * © [2025] LimX Dynamics Technology Co., Ltd. All rights reserved.
 */

#ifndef _LIMX_SDK_MSG_TELEOP_MSGS_VRSTATE_H_
#define _LIMX_SDK_MSG_TELEOP_MSGS_VRSTATE_H_

#include <array>
#include <cstddef>
#include <cstdint>
#include <string>
#include <vector>

#include "limxsdk/codec/codec.h"
#include "limxsdk/msg/std_msgs/Header.h"

namespace limxsdk
{
  namespace msg
  {
    namespace teleop_msgs
    {
      /// @brief Mirror of the mros `teleop_msgs/VRState` message.
      struct VRState
      {
        static constexpr const char *TYPE = "teleop_msgs/VRState";
        static constexpr const char *MD5 = "00c31bc920504fb5ee84c550ff4ee100";

        /// @brief ROS concatenated definition, as reported by mros.
        static const char *definition() { return "std_msgs/Header header\nfloat32[16] eyePose\nfloat32[16] l\nfloat32[16] r\nfloat32[2] leftJS\nfloat32 leftTrig\nfloat32 leftGrip\nbool LThU\nbool LTr\nbool LG\nbool X\nbool Y\nfloat32[2] rightJS\nfloat32 rightTrig\nfloat32 rightGrip\nbool RThU\nbool RTr\nbool RG\nbool A\nbool B\n================================================================================\nMSG: std_msgs/Header\nuint32 seq\ntime stamp\nstring frame_id\n"; }

        ::limxsdk::msg::std_msgs::Header header;
        std::array<float, 16> eyePose;
        std::array<float, 16> l;
        std::array<float, 16> r;
        std::array<float, 2> leftJS;
        float leftTrig = 0;
        float leftGrip = 0;
        uint8_t LThU = 0;
        uint8_t LTr = 0;
        uint8_t LG = 0;
        uint8_t X = 0;
        uint8_t Y = 0;
        std::array<float, 2> rightJS;
        float rightTrig = 0;
        float rightGrip = 0;
        uint8_t RThU = 0;
        uint8_t RTr = 0;
        uint8_t RG = 0;
        uint8_t A = 0;
        uint8_t B = 0;

        /// @brief Decode one frame; false means discard the whole message.
        bool decode(::limxsdk::codec::Reader &reader)
        {
          if (!header.decode(reader))
          {
            return false;
          }
          if (!reader.readPodArrayFixed(eyePose))
          {
            return false;
          }
          if (!reader.readPodArrayFixed(l))
          {
            return false;
          }
          if (!reader.readPodArrayFixed(r))
          {
            return false;
          }
          if (!reader.readPodArrayFixed(leftJS))
          {
            return false;
          }
          if (!reader.read(leftTrig))
          {
            return false;
          }
          if (!reader.read(leftGrip))
          {
            return false;
          }
          if (!reader.read(LThU))
          {
            return false;
          }
          if (!reader.read(LTr))
          {
            return false;
          }
          if (!reader.read(LG))
          {
            return false;
          }
          if (!reader.read(X))
          {
            return false;
          }
          if (!reader.read(Y))
          {
            return false;
          }
          if (!reader.readPodArrayFixed(rightJS))
          {
            return false;
          }
          if (!reader.read(rightTrig))
          {
            return false;
          }
          if (!reader.read(rightGrip))
          {
            return false;
          }
          if (!reader.read(RThU))
          {
            return false;
          }
          if (!reader.read(RTr))
          {
            return false;
          }
          if (!reader.read(RG))
          {
            return false;
          }
          if (!reader.read(A))
          {
            return false;
          }
          if (!reader.read(B))
          {
            return false;
          }
          return !reader.failed();
        }

        /// @brief Encode into a buffer of at least encodedSize() bytes.
        bool encode(::limxsdk::codec::Writer &writer) const
        {
          if (!header.encode(writer))
          {
            return false;
          }
          if (!writer.writePodArrayFixed(eyePose))
          {
            return false;
          }
          if (!writer.writePodArrayFixed(l))
          {
            return false;
          }
          if (!writer.writePodArrayFixed(r))
          {
            return false;
          }
          if (!writer.writePodArrayFixed(leftJS))
          {
            return false;
          }
          if (!writer.write(leftTrig))
          {
            return false;
          }
          if (!writer.write(leftGrip))
          {
            return false;
          }
          if (!writer.write(LThU))
          {
            return false;
          }
          if (!writer.write(LTr))
          {
            return false;
          }
          if (!writer.write(LG))
          {
            return false;
          }
          if (!writer.write(X))
          {
            return false;
          }
          if (!writer.write(Y))
          {
            return false;
          }
          if (!writer.writePodArrayFixed(rightJS))
          {
            return false;
          }
          if (!writer.write(rightTrig))
          {
            return false;
          }
          if (!writer.write(rightGrip))
          {
            return false;
          }
          if (!writer.write(RThU))
          {
            return false;
          }
          if (!writer.write(RTr))
          {
            return false;
          }
          if (!writer.write(RG))
          {
            return false;
          }
          if (!writer.write(A))
          {
            return false;
          }
          if (!writer.write(B))
          {
            return false;
          }
          return !writer.failed();
        }

        /// @brief Exact number of bytes encode() will write.
        std::size_t encodedSize() const
        {
          std::size_t total = 234;
          total += header.encodedSize();
          return total;
        }

        /// @brief Smallest possible encoding, used to reject bogus array lengths.
        static std::size_t minEncodedSize()
        {
          return 234 + ::limxsdk::msg::std_msgs::Header::minEncodedSize();
        }
      };
    } // namespace teleop_msgs
  } // namespace msg
} // namespace limxsdk

#endif // _LIMX_SDK_MSG_TELEOP_MSGS_VRSTATE_H_
