# @package _global_
defaults:
  - /task/microduck_velocity_flat/base
  - _self_

training:
  task_name: MicroduckVelocityFlat
  sim_backend: mujoco
  play_steps: 2000

algo:
  num_envs: 2048
  max_iterations: 500
  empirical_normalization: true
  obs_groups:
    actor:
      - policy
    critic:
      - critic
  policy:
    init_noise_std: 1.0
  algorithm:
    learning_rate: 1.0e-3
    entropy_coef: 0.01
