package(
    default_visibility = ["//visibility:public"],
)

exports_files([
    "emergency_state.proto",
    "hal_emergency_service.proto",
    "hal_operation_mode_service.proto",
    "hal_state_channel.proto",
    "operation_mode.proto",
    "mcu_state.proto",
])
