//! Validates the Rust FK against MuJoCo reference fixtures.
//!
//! Fixtures are generated by `scripts/gen_fixtures.py` (run via `uv`) and
//! checked in under `tests/fixtures/`. Regenerate them whenever the
//! bundled MJCFs change.

use std::collections::HashMap;
use std::path::Path;

use microduck_kinematics::{JointVector, Model};
use serde::Deserialize;

#[derive(Deserialize)]
struct Fixture {
    #[allow(dead_code)]
    version: String,
    samples: Vec<Sample>,
    #[allow(dead_code)]
    site_names: Vec<String>,
}

#[derive(Deserialize)]
struct Sample {
    joints: HashMap<String, f64>,
    sites: HashMap<String, SitePose>,
}

#[derive(Deserialize)]
struct SitePose {
    pos: [f64; 3],
    quat: [f64; 4],
}

fn load(path: &str) -> Fixture {
    let data = std::fs::read_to_string(Path::new(env!("CARGO_MANIFEST_DIR")).join(path))
        .expect("fixture not found — run `uv run --project scripts python scripts/gen_fixtures.py`");
    serde_json::from_str(&data).expect("fixture parse")
}

fn assert_matches(model: &Model, fx: &Fixture, version: &str) {
    const POS_TOL: f64 = 1e-6;   // metres
    const QUAT_TOL: f64 = 1e-6;  // unitless

    for (i, sample) in fx.samples.iter().enumerate() {
        let mut q = JointVector::new();
        for (name, &angle) in &sample.joints {
            q.set(name, angle);
        }

        for (site_name, expected) in &sample.sites {
            let got = model.site_pose(site_name, &q);
            let pos_err: f64 = expected
                .pos
                .iter()
                .zip(got.translation.iter())
                .map(|(a, b)| (a - b).abs())
                .fold(0.0, f64::max);
            assert!(
                pos_err < POS_TOL,
                "[{version}] sample #{i} site {site_name:?}: pos mismatch {pos_err} \
                 expected {:?} got {:?}",
                expected.pos,
                got.translation,
            );

            // Compare quaternions modulo sign (q and -q represent the same rotation).
            let got_q = got.rotation;
            let got_arr = [got_q.w, got_q.i, got_q.j, got_q.k];
            let d_plus: f64 = expected
                .quat
                .iter()
                .zip(got_arr.iter())
                .map(|(a, b)| (a - b).abs())
                .fold(0.0, f64::max);
            let d_minus: f64 = expected
                .quat
                .iter()
                .zip(got_arr.iter())
                .map(|(a, b)| (a + b).abs())
                .fold(0.0, f64::max);
            let quat_err = d_plus.min(d_minus);
            assert!(
                quat_err < QUAT_TOL,
                "[{version}] sample #{i} site {site_name:?}: quat mismatch {quat_err} \
                 expected {:?} got {:?}",
                expected.quat,
                got_arr,
            );
        }
    }
}

#[test]
fn v1_matches_mujoco() {
    let fx = load("tests/fixtures/fk_v1.json");
    assert_matches(&Model::v1(), &fx, "v1");
}

#[test]
fn v1_5_matches_mujoco() {
    let fx = load("tests/fixtures/fk_v1.5.json");
    assert_matches(&Model::v1_5(), &fx, "v1.5");
}

#[test]
fn alpha_matches_mujoco() {
    let fx = load("tests/fixtures/fk_alpha.json");
    assert_matches(&Model::alpha(), &fx, "alpha");
}
