package(
    default_visibility = ["//visibility:public"],
)

exports_files([
    "arm.proto",
    "joint.proto",
    "mc_data_service.proto",
    "mgpt.proto",
    "planning.proto",
    "tcp.proto",
])
