load("@integration//rules/utils:proto.bzl", "protobuf_utils")

package(default_visibility = ["//visibility:public"])

protobuf_utils(
    name = "arm_utils",
    dep_protos = [
    ],
    proto = "@aimrt_protocol//aimdk/protocol/mc/common:arm.proto",
    type_support_name = "aimdk_protocol_mc_arm",
)

protobuf_utils(
    name = "move_pose_mode_utils",
    dep_protos = [
    ],
    proto = "@aimrt_protocol//aimdk/protocol/mc/common:move_pose_mode.proto",
    type_support_name = "aimdk_protocol_move_pose_mode",
)

protobuf_utils(
    name = "planning_utils",
    dep_protos = [
    ],
    proto = "@aimrt_protocol//aimdk/protocol/mc/common:planning.proto",
    type_support_name = "aimdk_protocol_planning",
)
