#!/bin/sh

# /etc/X11/xinit/xinitrc
#
# global xinitrc file, used by all X sessions started by xinit (startx)

# disable dpms to fix screen blank and flickering
xset s 0
xset dpms 0 0 0
xset -dpms
# invoke global X session script
. /etc/X11/Xsession
