package(default_visibility = ["//visibility:public"])

cc_library(
    name = "pkg_mode",
    srcs = ["pkg_mode.cpp"],
    hdrs = ["pkg_mode.h"],
    deps = [
        "//src/program/details",
    ],
)
