FSM:
  _: # enabled fsms
    Passive:
      id: 1
    FixStand:
      id: 2
      type: Fix
    FixSquat:
      id: 3
      type: Fix
    Velocity_Up:
      id: 4
      type: RLBase
    Velocity_Down:
      id: 5
      type: RLBase
    Velocity_Left:
      id: 6
      type: RLBase
    Velocity_Right:
      id: 7
      type: RLBase

  Passive:
    transitions: 
      FixStand: LT + A.on_pressed
    mode: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
    kd: [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]
  FixStand:
    transitions: 
      Passive: LT + B.on_pressed
      FixSquat: LT + A.on_pressed
      Velocity_Up: start + up
      Velocity_Down: start + down
      Velocity_Left: start + left
      Velocity_Right: start + right
    kp: [60, 80, 80, 60, 80, 80, 60, 80, 80, 60, 80, 80]
    kd: [5, 4, 4, 5, 4, 4, 5, 4, 4, 5, 4, 4]
    ts: [0, 1, 2]
    qs: [
      [],
      [0.0, 1.36, -2.65, 0.0, 1.36, -2.65, 0.0, 1.36, -2.65, 0.0, 1.36, -2.65],
      [0., 0.8, -1.5, 0., 0.8, -1.5, 0., 0.8, -1.5, 0., 0.8, -1.5],
    ]
  FixSquat:
    transitions:
      Passive: LT + B.on_pressed
      FixStand: LT + A.on_pressed
    auto_transition: Passive
    kp: [60, 80, 80, 60, 80, 80, 60, 80, 80, 60, 80, 80]
    kd: [5, 4, 4, 5, 4, 4, 5, 4, 4, 5, 4, 4]
    ts: [0, 1, 2]
    qs: [
      [],
      [0., 0.8, -1.5, 0., 0.8, -1.5, 0., 0.8, -1.5, 0., 0.8, -1.5],
      [0.0, 1.36, -2.65, 0.0, 1.36, -2.65, 0.0, 1.36, -2.65, 0.0, 1.36, -2.65],
    ]
  Velocity_Up:
    transitions: 
      Passive: LT + B.on_pressed
      FixSquat: LT + A.on_pressed
      Velocity_Down: start + down
      Velocity_Left: start + left
      Velocity_Right: start + right
    policy_dir: ../../../logs/go2/go2_moe_cts_137k_0.6713
    fixed_command:
      enabled: true
      lin_vel_x: 1.0
      lin_vel_y: 0.0
      ang_vel_z: 0.0
      duration: 3.0
  Velocity_Down:
    transitions: 
      Passive: LT + B.on_pressed
      FixSquat: LT + A.on_pressed
      Velocity_Up: start + up
      Velocity_Left: start + left
      Velocity_Right: start + right
    # policy_dir: ../../../logs/go2/go2_moe_cts_flat_max4.5_71k
    policy_dir: ../../../logs/go2/go2_rl_lab/v0.1.8_fast_flat_40k  # fast model
    velocity_command_damping:
      enabled: true
      vx:
        speed_points: [0.0, 1.0, 2.0, 4.0]
        time_constants: [0.0, 0.0, 0.4, 0.6]
        max_acceleration: 4.0  # m/s^2
        max_deceleration: 3.0  # m/s^2
  Velocity_Left:
    transitions: 
      Passive: LT + B.on_pressed
      FixSquat: LT + A.on_pressed
      Velocity_Up: start + up
      Velocity_Down: start + down
      Velocity_Right: start + right
    policy_dir: ../../../logs/go2/go2_moe_cts_164k_0.6715
  Velocity_Right:
    transitions: 
      Passive: LT + B.on_pressed
      FixSquat: LT + A.on_pressed
      Velocity_Up: start + up
      Velocity_Down: start + down
      Velocity_Left: start + left
    policy_dir: ../../../logs/go2/go2_rl_robotlab/go2_moe_cts_v4.2_176k_0.6984
    logging: false
    logging_dt: 0.01
    fixed_command:
      enabled: true
      lin_vel_x: 1.0
      lin_vel_y: 0.0
      ang_vel_z: 0.0
      duration: 3.5
    joint_pos_udp:
      enabled: true
      host: 192.168.1.255
      port: 15000
      dt: 0.1
