/**
 * @file Empty.h
 *
 * @brief Generated mirror of the mros `std_msgs/Empty` message.
 *
 * THIS FILE IS GENERATED BY tools/limxsdk-gen/limxsdk_gen.py - DO NOT EDIT.
 * Regenerate it instead of patching it; hand edits are lost on the next run.
 *
 * © [2025] LimX Dynamics Technology Co., Ltd. All rights reserved.
 */

#ifndef _LIMX_SDK_MSG_STD_MSGS_EMPTY_H_
#define _LIMX_SDK_MSG_STD_MSGS_EMPTY_H_

#include <array>
#include <cstddef>
#include <cstdint>
#include <string>
#include <vector>

#include "limxsdk/codec/codec.h"

namespace limxsdk
{
  namespace msg
  {
    namespace std_msgs
    {
      /// @brief Mirror of the mros `std_msgs/Empty` message.
      struct Empty
      {
        static constexpr const char *TYPE = "std_msgs/Empty";
        static constexpr const char *MD5 = "d41d8cd98f00b204e9800998ecf8427e";

        /// @brief ROS concatenated definition, as reported by mros.
        static const char *definition() { return ""; }


        /// @brief Decode one frame; false means discard the whole message.
        bool decode(::limxsdk::codec::Reader &reader)
        {
          (void)reader;
          return !reader.failed();
        }

        /// @brief Encode into a buffer of at least encodedSize() bytes.
        bool encode(::limxsdk::codec::Writer &writer) const
        {
          (void)writer;
          return !writer.failed();
        }

        /// @brief Exact number of bytes encode() will write.
        std::size_t encodedSize() const
        {
          return 0;
        }

        /// @brief Smallest possible encoding, used to reject bogus array lengths.
        static std::size_t minEncodedSize()
        {
          return 0;
        }
      };
    } // namespace std_msgs
  } // namespace msg
} // namespace limxsdk

#endif // _LIMX_SDK_MSG_STD_MSGS_EMPTY_H_
