/**
 * @file Float64MultiArray.h
 *
 * @brief Generated mirror of the mros `std_msgs/Float64MultiArray` message.
 *
 * THIS FILE IS GENERATED BY tools/limxsdk-gen/limxsdk_gen.py - DO NOT EDIT.
 * Regenerate it instead of patching it; hand edits are lost on the next run.
 *
 * © [2025] LimX Dynamics Technology Co., Ltd. All rights reserved.
 */

#ifndef _LIMX_SDK_MSG_STD_MSGS_FLOAT64MULTIARRAY_H_
#define _LIMX_SDK_MSG_STD_MSGS_FLOAT64MULTIARRAY_H_

#include <array>
#include <cstddef>
#include <cstdint>
#include <string>
#include <vector>

#include "limxsdk/codec/codec.h"
#include "limxsdk/msg/std_msgs/MultiArrayLayout.h"

namespace limxsdk
{
  namespace msg
  {
    namespace std_msgs
    {
      /// @brief Mirror of the mros `std_msgs/Float64MultiArray` message.
      struct Float64MultiArray
      {
        static constexpr const char *TYPE = "std_msgs/Float64MultiArray";
        static constexpr const char *MD5 = "4b7d974086d4060e7db4613a7e6c3ba4";

        /// @brief ROS concatenated definition, as reported by mros.
        static const char *definition() { return "std_msgs/MultiArrayLayout layout\nfloat64[] data\n================================================================================\nMSG: std_msgs/MultiArrayLayout\nstd_msgs/MultiArrayDimension[] dim\nuint32 data_offset\n================================================================================\nMSG: std_msgs/MultiArrayDimension\nstring label\nuint32 size\nuint32 stride\n"; }

        ::limxsdk::msg::std_msgs::MultiArrayLayout layout;
        std::vector<double> data;

        /// @brief Decode one frame; false means discard the whole message.
        bool decode(::limxsdk::codec::Reader &reader)
        {
          if (!layout.decode(reader))
          {
            return false;
          }
          if (!reader.readPodArray(data))
          {
            return false;
          }
          return !reader.failed();
        }

        /// @brief Encode into a buffer of at least encodedSize() bytes.
        bool encode(::limxsdk::codec::Writer &writer) const
        {
          if (!layout.encode(writer))
          {
            return false;
          }
          if (!writer.writePodArray(data))
          {
            return false;
          }
          return !writer.failed();
        }

        /// @brief Exact number of bytes encode() will write.
        std::size_t encodedSize() const
        {
          std::size_t total = 4;
          total += layout.encodedSize();
          total += data.size() * 8;
          return total;
        }

        /// @brief Smallest possible encoding, used to reject bogus array lengths.
        static std::size_t minEncodedSize()
        {
          return 4 + ::limxsdk::msg::std_msgs::MultiArrayLayout::minEncodedSize();
        }
      };
    } // namespace std_msgs
  } // namespace msg
} // namespace limxsdk

#endif // _LIMX_SDK_MSG_STD_MSGS_FLOAT64MULTIARRAY_H_
