/**
 * @file Header.h
 *
 * @brief Generated mirror of the mros `std_msgs/Header` message.
 *
 * THIS FILE IS GENERATED BY tools/limxsdk-gen/limxsdk_gen.py - DO NOT EDIT.
 * Regenerate it instead of patching it; hand edits are lost on the next run.
 *
 * © [2025] LimX Dynamics Technology Co., Ltd. All rights reserved.
 */

#ifndef _LIMX_SDK_MSG_STD_MSGS_HEADER_H_
#define _LIMX_SDK_MSG_STD_MSGS_HEADER_H_

#include <array>
#include <cstddef>
#include <cstdint>
#include <string>
#include <vector>

#include "limxsdk/codec/codec.h"

namespace limxsdk
{
  namespace msg
  {
    namespace std_msgs
    {
      /// @brief Mirror of the mros `std_msgs/Header` message.
      struct Header
      {
        static constexpr const char *TYPE = "std_msgs/Header";
        static constexpr const char *MD5 = "2176decaecbce78abc3b96ef049fabed";

        /// @brief ROS concatenated definition, as reported by mros.
        static const char *definition() { return "uint32 seq\ntime stamp\nstring frame_id\n"; }

        uint32_t seq = 0;
        ::limxsdk::codec::Time stamp;
        std::string frame_id;

        /// @brief Decode one frame; false means discard the whole message.
        bool decode(::limxsdk::codec::Reader &reader)
        {
          if (!reader.read(seq))
          {
            return false;
          }
          if (!reader.read(stamp))
          {
            return false;
          }
          if (!reader.read(frame_id))
          {
            return false;
          }
          return !reader.failed();
        }

        /// @brief Encode into a buffer of at least encodedSize() bytes.
        bool encode(::limxsdk::codec::Writer &writer) const
        {
          if (!writer.write(seq))
          {
            return false;
          }
          if (!writer.write(stamp))
          {
            return false;
          }
          if (!writer.write(frame_id))
          {
            return false;
          }
          return !writer.failed();
        }

        /// @brief Exact number of bytes encode() will write.
        std::size_t encodedSize() const
        {
          std::size_t total = 16;
          total += frame_id.size();
          return total;
        }

        /// @brief Smallest possible encoding, used to reject bogus array lengths.
        static std::size_t minEncodedSize()
        {
          return 16;
        }
      };
    } // namespace std_msgs
  } // namespace msg
} // namespace limxsdk

#endif // _LIMX_SDK_MSG_STD_MSGS_HEADER_H_
