/**
 * @file Int8.h
 *
 * @brief Generated mirror of the mros `std_msgs/Int8` message.
 *
 * THIS FILE IS GENERATED BY tools/limxsdk-gen/limxsdk_gen.py - DO NOT EDIT.
 * Regenerate it instead of patching it; hand edits are lost on the next run.
 *
 * © [2025] LimX Dynamics Technology Co., Ltd. All rights reserved.
 */

#ifndef _LIMX_SDK_MSG_STD_MSGS_INT8_H_
#define _LIMX_SDK_MSG_STD_MSGS_INT8_H_

#include <array>
#include <cstddef>
#include <cstdint>
#include <string>
#include <vector>

#include "limxsdk/codec/codec.h"

namespace limxsdk
{
  namespace msg
  {
    namespace std_msgs
    {
      /// @brief Mirror of the mros `std_msgs/Int8` message.
      struct Int8
      {
        static constexpr const char *TYPE = "std_msgs/Int8";
        static constexpr const char *MD5 = "27ffa0c9c4b8fb8492252bcad9e5c57b";

        /// @brief ROS concatenated definition, as reported by mros.
        static const char *definition() { return "int8 data\n"; }

        int8_t data = 0;

        /// @brief Decode one frame; false means discard the whole message.
        bool decode(::limxsdk::codec::Reader &reader)
        {
          if (!reader.read(data))
          {
            return false;
          }
          return !reader.failed();
        }

        /// @brief Encode into a buffer of at least encodedSize() bytes.
        bool encode(::limxsdk::codec::Writer &writer) const
        {
          if (!writer.write(data))
          {
            return false;
          }
          return !writer.failed();
        }

        /// @brief Exact number of bytes encode() will write.
        std::size_t encodedSize() const
        {
          return 1;
        }

        /// @brief Smallest possible encoding, used to reject bogus array lengths.
        static std::size_t minEncodedSize()
        {
          return 1;
        }
      };
    } // namespace std_msgs
  } // namespace msg
} // namespace limxsdk

#endif // _LIMX_SDK_MSG_STD_MSGS_INT8_H_
