/**
 * @file MultiArrayDimension.h
 *
 * @brief Generated mirror of the mros `std_msgs/MultiArrayDimension` message.
 *
 * THIS FILE IS GENERATED BY tools/limxsdk-gen/limxsdk_gen.py - DO NOT EDIT.
 * Regenerate it instead of patching it; hand edits are lost on the next run.
 *
 * © [2025] LimX Dynamics Technology Co., Ltd. All rights reserved.
 */

#ifndef _LIMX_SDK_MSG_STD_MSGS_MULTIARRAYDIMENSION_H_
#define _LIMX_SDK_MSG_STD_MSGS_MULTIARRAYDIMENSION_H_

#include <array>
#include <cstddef>
#include <cstdint>
#include <string>
#include <vector>

#include "limxsdk/codec/codec.h"

namespace limxsdk
{
  namespace msg
  {
    namespace std_msgs
    {
      /// @brief Mirror of the mros `std_msgs/MultiArrayDimension` message.
      struct MultiArrayDimension
      {
        static constexpr const char *TYPE = "std_msgs/MultiArrayDimension";
        static constexpr const char *MD5 = "4cd0c83a8683deae40ecdac60e53bfa8";

        /// @brief ROS concatenated definition, as reported by mros.
        static const char *definition() { return "string label\nuint32 size\nuint32 stride\n"; }

        std::string label;
        uint32_t size = 0;
        uint32_t stride = 0;

        /// @brief Decode one frame; false means discard the whole message.
        bool decode(::limxsdk::codec::Reader &reader)
        {
          if (!reader.read(label))
          {
            return false;
          }
          if (!reader.read(size))
          {
            return false;
          }
          if (!reader.read(stride))
          {
            return false;
          }
          return !reader.failed();
        }

        /// @brief Encode into a buffer of at least encodedSize() bytes.
        bool encode(::limxsdk::codec::Writer &writer) const
        {
          if (!writer.write(label))
          {
            return false;
          }
          if (!writer.write(size))
          {
            return false;
          }
          if (!writer.write(stride))
          {
            return false;
          }
          return !writer.failed();
        }

        /// @brief Exact number of bytes encode() will write.
        std::size_t encodedSize() const
        {
          std::size_t total = 12;
          total += label.size();
          return total;
        }

        /// @brief Smallest possible encoding, used to reject bogus array lengths.
        static std::size_t minEncodedSize()
        {
          return 12;
        }
      };
    } // namespace std_msgs
  } // namespace msg
} // namespace limxsdk

#endif // _LIMX_SDK_MSG_STD_MSGS_MULTIARRAYDIMENSION_H_
