/**
 * @file MultiArrayLayout.h
 *
 * @brief Generated mirror of the mros `std_msgs/MultiArrayLayout` message.
 *
 * THIS FILE IS GENERATED BY tools/limxsdk-gen/limxsdk_gen.py - DO NOT EDIT.
 * Regenerate it instead of patching it; hand edits are lost on the next run.
 *
 * © [2025] LimX Dynamics Technology Co., Ltd. All rights reserved.
 */

#ifndef _LIMX_SDK_MSG_STD_MSGS_MULTIARRAYLAYOUT_H_
#define _LIMX_SDK_MSG_STD_MSGS_MULTIARRAYLAYOUT_H_

#include <array>
#include <cstddef>
#include <cstdint>
#include <string>
#include <vector>

#include "limxsdk/codec/codec.h"
#include "limxsdk/msg/std_msgs/MultiArrayDimension.h"

namespace limxsdk
{
  namespace msg
  {
    namespace std_msgs
    {
      /// @brief Mirror of the mros `std_msgs/MultiArrayLayout` message.
      struct MultiArrayLayout
      {
        static constexpr const char *TYPE = "std_msgs/MultiArrayLayout";
        static constexpr const char *MD5 = "0fed2a11c13e11c5571b4e2a995a91a3";

        /// @brief ROS concatenated definition, as reported by mros.
        static const char *definition() { return "std_msgs/MultiArrayDimension[] dim\nuint32 data_offset\n================================================================================\nMSG: std_msgs/MultiArrayDimension\nstring label\nuint32 size\nuint32 stride\n"; }

        std::vector<::limxsdk::msg::std_msgs::MultiArrayDimension> dim;
        uint32_t data_offset = 0;

        /// @brief Decode one frame; false means discard the whole message.
        bool decode(::limxsdk::codec::Reader &reader)
        {
          if (!reader.readMsgArray(dim))
          {
            return false;
          }
          if (!reader.read(data_offset))
          {
            return false;
          }
          return !reader.failed();
        }

        /// @brief Encode into a buffer of at least encodedSize() bytes.
        bool encode(::limxsdk::codec::Writer &writer) const
        {
          if (!writer.writeMsgArray(dim))
          {
            return false;
          }
          if (!writer.write(data_offset))
          {
            return false;
          }
          return !writer.failed();
        }

        /// @brief Exact number of bytes encode() will write.
        std::size_t encodedSize() const
        {
          std::size_t total = 8;
          total += ::limxsdk::codec::arraySize(dim);
          return total;
        }

        /// @brief Smallest possible encoding, used to reject bogus array lengths.
        static std::size_t minEncodedSize()
        {
          return 8;
        }
      };
    } // namespace std_msgs
  } // namespace msg
} // namespace limxsdk

#endif // _LIMX_SDK_MSG_STD_MSGS_MULTIARRAYLAYOUT_H_
