/**
 * @file ControllerState.h
 *
 * @brief Generated mirror of the mros `controller_manager_msgs/ControllerState` message.
 *
 * THIS FILE IS GENERATED BY tools/limxsdk-gen/limxsdk_gen.py - DO NOT EDIT.
 * Regenerate it instead of patching it; hand edits are lost on the next run.
 *
 * © [2025] LimX Dynamics Technology Co., Ltd. All rights reserved.
 */

#ifndef _LIMX_SDK_MSG_CONTROLLER_MANAGER_MSGS_CONTROLLERSTATE_H_
#define _LIMX_SDK_MSG_CONTROLLER_MANAGER_MSGS_CONTROLLERSTATE_H_

#include <array>
#include <cstddef>
#include <cstdint>
#include <string>
#include <vector>

#include "limxsdk/codec/codec.h"
#include "limxsdk/msg/controller_manager_msgs/HardwareInterfaceResources.h"

namespace limxsdk
{
  namespace msg
  {
    namespace controller_manager_msgs
    {
      /// @brief Mirror of the mros `controller_manager_msgs/ControllerState` message.
      struct ControllerState
      {
        static constexpr const char *TYPE = "controller_manager_msgs/ControllerState";
        static constexpr const char *MD5 = "aeb6b261d97793ab74099a3740245272";

        /// @brief ROS concatenated definition, as reported by mros.
        static const char *definition() { return "string name\nstring state\nstring type\ncontroller_manager_msgs/HardwareInterfaceResources[] claimed_resources\n================================================================================\nMSG: controller_manager_msgs/HardwareInterfaceResources\nstring hardware_interface\nstring[] resources\n"; }

        std::string name;
        std::string state;
        std::string type;
        std::vector<::limxsdk::msg::controller_manager_msgs::HardwareInterfaceResources> claimed_resources;

        /// @brief Decode one frame; false means discard the whole message.
        bool decode(::limxsdk::codec::Reader &reader)
        {
          if (!reader.read(name))
          {
            return false;
          }
          if (!reader.read(state))
          {
            return false;
          }
          if (!reader.read(type))
          {
            return false;
          }
          if (!reader.readMsgArray(claimed_resources))
          {
            return false;
          }
          return !reader.failed();
        }

        /// @brief Encode into a buffer of at least encodedSize() bytes.
        bool encode(::limxsdk::codec::Writer &writer) const
        {
          if (!writer.write(name))
          {
            return false;
          }
          if (!writer.write(state))
          {
            return false;
          }
          if (!writer.write(type))
          {
            return false;
          }
          if (!writer.writeMsgArray(claimed_resources))
          {
            return false;
          }
          return !writer.failed();
        }

        /// @brief Exact number of bytes encode() will write.
        std::size_t encodedSize() const
        {
          std::size_t total = 16;
          total += name.size();
          total += state.size();
          total += type.size();
          total += ::limxsdk::codec::arraySize(claimed_resources);
          return total;
        }

        /// @brief Smallest possible encoding, used to reject bogus array lengths.
        static std::size_t minEncodedSize()
        {
          return 16;
        }
      };
    } // namespace controller_manager_msgs
  } // namespace msg
} // namespace limxsdk

#endif // _LIMX_SDK_MSG_CONTROLLER_MANAGER_MSGS_CONTROLLERSTATE_H_
