/**
 * @file HardwareInterfaceResources.h
 *
 * @brief Generated mirror of the mros `controller_manager_msgs/HardwareInterfaceResources` message.
 *
 * THIS FILE IS GENERATED BY tools/limxsdk-gen/limxsdk_gen.py - DO NOT EDIT.
 * Regenerate it instead of patching it; hand edits are lost on the next run.
 *
 * © [2025] LimX Dynamics Technology Co., Ltd. All rights reserved.
 */

#ifndef _LIMX_SDK_MSG_CONTROLLER_MANAGER_MSGS_HARDWAREINTERFACERESOURCES_H_
#define _LIMX_SDK_MSG_CONTROLLER_MANAGER_MSGS_HARDWAREINTERFACERESOURCES_H_

#include <array>
#include <cstddef>
#include <cstdint>
#include <string>
#include <vector>

#include "limxsdk/codec/codec.h"

namespace limxsdk
{
  namespace msg
  {
    namespace controller_manager_msgs
    {
      /// @brief Mirror of the mros `controller_manager_msgs/HardwareInterfaceResources` message.
      struct HardwareInterfaceResources
      {
        static constexpr const char *TYPE = "controller_manager_msgs/HardwareInterfaceResources";
        static constexpr const char *MD5 = "f25b55cbf1d1f76e82e5ec9e83f76258";

        /// @brief ROS concatenated definition, as reported by mros.
        static const char *definition() { return "string hardware_interface\nstring[] resources\n"; }

        std::string hardware_interface;
        std::vector<std::string> resources;

        /// @brief Decode one frame; false means discard the whole message.
        bool decode(::limxsdk::codec::Reader &reader)
        {
          if (!reader.read(hardware_interface))
          {
            return false;
          }
          if (!reader.readValueArray(resources, 4))
          {
            return false;
          }
          return !reader.failed();
        }

        /// @brief Encode into a buffer of at least encodedSize() bytes.
        bool encode(::limxsdk::codec::Writer &writer) const
        {
          if (!writer.write(hardware_interface))
          {
            return false;
          }
          if (!writer.writeValueArray(resources))
          {
            return false;
          }
          return !writer.failed();
        }

        /// @brief Exact number of bytes encode() will write.
        std::size_t encodedSize() const
        {
          std::size_t total = 8;
          total += hardware_interface.size();
          total += ::limxsdk::codec::arraySize(resources);
          return total;
        }

        /// @brief Smallest possible encoding, used to reject bogus array lengths.
        static std::size_t minEncodedSize()
        {
          return 8;
        }
      };
    } // namespace controller_manager_msgs
  } // namespace msg
} // namespace limxsdk

#endif // _LIMX_SDK_MSG_CONTROLLER_MANAGER_MSGS_HARDWAREINTERFACERESOURCES_H_
