package(
    default_visibility = ["//visibility:public"],
)

exports_files([
    "Command.msg",
    "JointCommand.msg",
    "JointState.msg",
    "State.msg"
])

filegroup(
    name = "ros2_files",
    srcs = glob([
        "*.msg",
    ]),
)
