package(
    default_visibility = ["//visibility:public"],
)

exports_files([
    "cameras_intrinsic.proto",
    "cameras_snapshot.proto",
    "color_depth_image_channel.proto",
    "image_channel.proto",
    "rs2_camera.proto",
])

filegroup(
    name = "ros2_files",
    srcs = [
        "CMakeLists.txt",
        'package.xml'
    ],
)
