/**
 * @file GripperCommand.h
 *
 * @brief Generated mirror of the mros `control_msgs/GripperCommand` message.
 *
 * THIS FILE IS GENERATED BY tools/limxsdk-gen/limxsdk_gen.py - DO NOT EDIT.
 * Regenerate it instead of patching it; hand edits are lost on the next run.
 *
 * © [2025] LimX Dynamics Technology Co., Ltd. All rights reserved.
 */

#ifndef _LIMX_SDK_MSG_CONTROL_MSGS_GRIPPERCOMMAND_H_
#define _LIMX_SDK_MSG_CONTROL_MSGS_GRIPPERCOMMAND_H_

#include <array>
#include <cstddef>
#include <cstdint>
#include <string>
#include <vector>

#include "limxsdk/codec/codec.h"

namespace limxsdk
{
  namespace msg
  {
    namespace control_msgs
    {
      /// @brief Mirror of the mros `control_msgs/GripperCommand` message.
      struct GripperCommand
      {
        static constexpr const char *TYPE = "control_msgs/GripperCommand";
        static constexpr const char *MD5 = "680acaff79486f017132a7f198d40f08";

        /// @brief ROS concatenated definition, as reported by mros.
        static const char *definition() { return "float64 position\nfloat64 max_effort\n"; }

        double position = 0;
        double max_effort = 0;

        /// @brief Decode one frame; false means discard the whole message.
        bool decode(::limxsdk::codec::Reader &reader)
        {
          if (!reader.read(position))
          {
            return false;
          }
          if (!reader.read(max_effort))
          {
            return false;
          }
          return !reader.failed();
        }

        /// @brief Encode into a buffer of at least encodedSize() bytes.
        bool encode(::limxsdk::codec::Writer &writer) const
        {
          if (!writer.write(position))
          {
            return false;
          }
          if (!writer.write(max_effort))
          {
            return false;
          }
          return !writer.failed();
        }

        /// @brief Exact number of bytes encode() will write.
        std::size_t encodedSize() const
        {
          return 16;
        }

        /// @brief Smallest possible encoding, used to reject bogus array lengths.
        static std::size_t minEncodedSize()
        {
          return 16;
        }
      };
    } // namespace control_msgs
  } // namespace msg
} // namespace limxsdk

#endif // _LIMX_SDK_MSG_CONTROL_MSGS_GRIPPERCOMMAND_H_
