package(default_visibility = ["//visibility:public"])

filegroup(
    name = "protoc_plugin_gen_aimrte_rpc",
    srcs = ["protoc_plugin_gen_aimrte_rpc.py"],
)

filegroup(
    name = "ros2_protocol_gen_aimrte_rpc",
    srcs = ["ros2_protocol_gen_aimrte_rpc.py"],
)

filegroup(
    name = "protoc_plugin_gen_aimrt_cc_type_support",
    srcs = ["protoc_plugin_gen_aimrt_cc_type_support.py"],
)

filegroup(
    name = "protoc_plugin_gen_aimrt_cc_type_support_ros2",
    srcs = ["protoc_plugin_gen_aimrt_cc_type_support_ros2.py"],
)
