package(
    default_visibility = ["//visibility:public"],
)

exports_files([
    "RecordUpload.msg",
    "BagInfo.msg",
    "ActionInfo.msg",
    "TopicMeta.msg",
])

filegroup(
    name = "ros2_files",
    srcs = glob(
        [
            "**",
        ],
        exclude = ["BUILD"],
    ),
)