/**
 * @file HandMsg.h
 *
 * @brief Generated mirror of the mros `hand_msgs/HandMsg` message.
 *
 * THIS FILE IS GENERATED BY tools/limxsdk-gen/limxsdk_gen.py - DO NOT EDIT.
 * Regenerate it instead of patching it; hand edits are lost on the next run.
 *
 * © [2025] LimX Dynamics Technology Co., Ltd. All rights reserved.
 */

#ifndef _LIMX_SDK_MSG_HAND_MSGS_HANDMSG_H_
#define _LIMX_SDK_MSG_HAND_MSGS_HANDMSG_H_

#include <array>
#include <cstddef>
#include <cstdint>
#include <string>
#include <vector>

#include "limxsdk/codec/codec.h"
#include "limxsdk/msg/std_msgs/Header.h"

namespace limxsdk
{
  namespace msg
  {
    namespace hand_msgs
    {
      /// @brief Mirror of the mros `hand_msgs/HandMsg` message.
      struct HandMsg
      {
        static constexpr const char *TYPE = "hand_msgs/HandMsg";
        static constexpr const char *MD5 = "5bf399d0b94663b56e927d0e9c254c1c";

        /// @brief ROS concatenated definition, as reported by mros.
        static const char *definition() { return "std_msgs/Header header\nstring[] names\nfloat32[] pos\nfloat32[] vel\nfloat32[] current\nfloat32[] time\n================================================================================\nMSG: std_msgs/Header\nuint32 seq\ntime stamp\nstring frame_id\n"; }

        ::limxsdk::msg::std_msgs::Header header;
        std::vector<std::string> names;
        std::vector<float> pos;
        std::vector<float> vel;
        std::vector<float> current;
        std::vector<float> time;

        /// @brief Decode one frame; false means discard the whole message.
        bool decode(::limxsdk::codec::Reader &reader)
        {
          if (!header.decode(reader))
          {
            return false;
          }
          if (!reader.readValueArray(names, 4))
          {
            return false;
          }
          if (!reader.readPodArray(pos))
          {
            return false;
          }
          if (!reader.readPodArray(vel))
          {
            return false;
          }
          if (!reader.readPodArray(current))
          {
            return false;
          }
          if (!reader.readPodArray(time))
          {
            return false;
          }
          return !reader.failed();
        }

        /// @brief Encode into a buffer of at least encodedSize() bytes.
        bool encode(::limxsdk::codec::Writer &writer) const
        {
          if (!header.encode(writer))
          {
            return false;
          }
          if (!writer.writeValueArray(names))
          {
            return false;
          }
          if (!writer.writePodArray(pos))
          {
            return false;
          }
          if (!writer.writePodArray(vel))
          {
            return false;
          }
          if (!writer.writePodArray(current))
          {
            return false;
          }
          if (!writer.writePodArray(time))
          {
            return false;
          }
          return !writer.failed();
        }

        /// @brief Exact number of bytes encode() will write.
        std::size_t encodedSize() const
        {
          std::size_t total = 20;
          total += header.encodedSize();
          total += ::limxsdk::codec::arraySize(names);
          total += pos.size() * 4;
          total += vel.size() * 4;
          total += current.size() * 4;
          total += time.size() * 4;
          return total;
        }

        /// @brief Smallest possible encoding, used to reject bogus array lengths.
        static std::size_t minEncodedSize()
        {
          return 20 + ::limxsdk::msg::std_msgs::Header::minEncodedSize();
        }
      };
    } // namespace hand_msgs
  } // namespace msg
} // namespace limxsdk

#endif // _LIMX_SDK_MSG_HAND_MSGS_HANDMSG_H_
