/**
 * @file TactileCmd.h
 *
 * @brief Generated mirror of the mros `hand_msgs/TactileCmd` message.
 *
 * THIS FILE IS GENERATED BY tools/limxsdk-gen/limxsdk_gen.py - DO NOT EDIT.
 * Regenerate it instead of patching it; hand edits are lost on the next run.
 *
 * © [2025] LimX Dynamics Technology Co., Ltd. All rights reserved.
 */

#ifndef _LIMX_SDK_MSG_HAND_MSGS_TACTILECMD_H_
#define _LIMX_SDK_MSG_HAND_MSGS_TACTILECMD_H_

#include <array>
#include <cstddef>
#include <cstdint>
#include <string>
#include <vector>

#include "limxsdk/codec/codec.h"
#include "limxsdk/msg/std_msgs/Header.h"

namespace limxsdk
{
  namespace msg
  {
    namespace hand_msgs
    {
      /// @brief Mirror of the mros `hand_msgs/TactileCmd` message.
      struct TactileCmd
      {
        static constexpr const char *TYPE = "hand_msgs/TactileCmd";
        static constexpr const char *MD5 = "8b0263238e251bcb7003327943797186";

        /// @brief ROS concatenated definition, as reported by mros.
        static const char *definition() { return "std_msgs/Header header\nstring[] names\nbool[] tactile_switch\nbool[] channel_reset\nbool[] calibration_trigger\n================================================================================\nMSG: std_msgs/Header\nuint32 seq\ntime stamp\nstring frame_id\n"; }

        ::limxsdk::msg::std_msgs::Header header;
        std::vector<std::string> names;
        std::vector<uint8_t> tactile_switch;
        std::vector<uint8_t> channel_reset;
        std::vector<uint8_t> calibration_trigger;

        /// @brief Decode one frame; false means discard the whole message.
        bool decode(::limxsdk::codec::Reader &reader)
        {
          if (!header.decode(reader))
          {
            return false;
          }
          if (!reader.readValueArray(names, 4))
          {
            return false;
          }
          if (!reader.readPodArray(tactile_switch))
          {
            return false;
          }
          if (!reader.readPodArray(channel_reset))
          {
            return false;
          }
          if (!reader.readPodArray(calibration_trigger))
          {
            return false;
          }
          return !reader.failed();
        }

        /// @brief Encode into a buffer of at least encodedSize() bytes.
        bool encode(::limxsdk::codec::Writer &writer) const
        {
          if (!header.encode(writer))
          {
            return false;
          }
          if (!writer.writeValueArray(names))
          {
            return false;
          }
          if (!writer.writePodArray(tactile_switch))
          {
            return false;
          }
          if (!writer.writePodArray(channel_reset))
          {
            return false;
          }
          if (!writer.writePodArray(calibration_trigger))
          {
            return false;
          }
          return !writer.failed();
        }

        /// @brief Exact number of bytes encode() will write.
        std::size_t encodedSize() const
        {
          std::size_t total = 16;
          total += header.encodedSize();
          total += ::limxsdk::codec::arraySize(names);
          total += tactile_switch.size() * 1;
          total += channel_reset.size() * 1;
          total += calibration_trigger.size() * 1;
          return total;
        }

        /// @brief Smallest possible encoding, used to reject bogus array lengths.
        static std::size_t minEncodedSize()
        {
          return 16 + ::limxsdk::msg::std_msgs::Header::minEncodedSize();
        }
      };
    } // namespace hand_msgs
  } // namespace msg
} // namespace limxsdk

#endif // _LIMX_SDK_MSG_HAND_MSGS_TACTILECMD_H_
