/**
 * @file TactileHandState.h
 *
 * @brief Generated mirror of the mros `hand_msgs/TactileHandState` message.
 *
 * THIS FILE IS GENERATED BY tools/limxsdk-gen/limxsdk_gen.py - DO NOT EDIT.
 * Regenerate it instead of patching it; hand edits are lost on the next run.
 *
 * © [2025] LimX Dynamics Technology Co., Ltd. All rights reserved.
 */

#ifndef _LIMX_SDK_MSG_HAND_MSGS_TACTILEHANDSTATE_H_
#define _LIMX_SDK_MSG_HAND_MSGS_TACTILEHANDSTATE_H_

#include <array>
#include <cstddef>
#include <cstdint>
#include <string>
#include <vector>

#include "limxsdk/codec/codec.h"
#include "limxsdk/msg/hand_msgs/HandMsg.h"
#include "limxsdk/msg/hand_msgs/TactileState.h"
#include "limxsdk/msg/std_msgs/Header.h"

namespace limxsdk
{
  namespace msg
  {
    namespace hand_msgs
    {
      /// @brief Mirror of the mros `hand_msgs/TactileHandState` message.
      struct TactileHandState
      {
        static constexpr const char *TYPE = "hand_msgs/TactileHandState";
        static constexpr const char *MD5 = "ac5f5ca79b187659a94b06b37f2a6caa";

        /// @brief ROS concatenated definition, as reported by mros.
        static const char *definition() { return "std_msgs/Header header\nstring hand_type\nuint8[2] ctrl_mode\nhand_msgs/HandMsg[2] hand_state\nhand_msgs/TactileState[2] hand_tactile_state\n================================================================================\nMSG: std_msgs/Header\nuint32 seq\ntime stamp\nstring frame_id\n================================================================================\nMSG: hand_msgs/HandMsg\nstd_msgs/Header header\nstring[] names\nfloat32[] pos\nfloat32[] vel\nfloat32[] current\nfloat32[] time\n================================================================================\nMSG: hand_msgs/TactileState\nstd_msgs/Header header\nstring[] names\nfloat32[] normal_force\nfloat32[] tangential_force\nfloat32[] direction_angle\nuint32[] approximate_value\nuint16[] tactile_state\n"; }

        ::limxsdk::msg::std_msgs::Header header;
        std::string hand_type;
        std::array<uint8_t, 2> ctrl_mode;
        std::array<::limxsdk::msg::hand_msgs::HandMsg, 2> hand_state;
        std::array<::limxsdk::msg::hand_msgs::TactileState, 2> hand_tactile_state;

        /// @brief Decode one frame; false means discard the whole message.
        bool decode(::limxsdk::codec::Reader &reader)
        {
          if (!header.decode(reader))
          {
            return false;
          }
          if (!reader.read(hand_type))
          {
            return false;
          }
          if (!reader.readPodArrayFixed(ctrl_mode))
          {
            return false;
          }
          if (!reader.readMsgArrayFixed(hand_state))
          {
            return false;
          }
          if (!reader.readMsgArrayFixed(hand_tactile_state))
          {
            return false;
          }
          return !reader.failed();
        }

        /// @brief Encode into a buffer of at least encodedSize() bytes.
        bool encode(::limxsdk::codec::Writer &writer) const
        {
          if (!header.encode(writer))
          {
            return false;
          }
          if (!writer.write(hand_type))
          {
            return false;
          }
          if (!writer.writePodArrayFixed(ctrl_mode))
          {
            return false;
          }
          if (!writer.writeMsgArrayFixed(hand_state))
          {
            return false;
          }
          if (!writer.writeMsgArrayFixed(hand_tactile_state))
          {
            return false;
          }
          return !writer.failed();
        }

        /// @brief Exact number of bytes encode() will write.
        std::size_t encodedSize() const
        {
          std::size_t total = 6;
          total += header.encodedSize();
          total += hand_type.size();
          total += ::limxsdk::codec::arraySize(hand_state);
          total += ::limxsdk::codec::arraySize(hand_tactile_state);
          return total;
        }

        /// @brief Smallest possible encoding, used to reject bogus array lengths.
        static std::size_t minEncodedSize()
        {
          return 6 + ::limxsdk::msg::std_msgs::Header::minEncodedSize() + 2 * ::limxsdk::msg::hand_msgs::HandMsg::minEncodedSize() + 2 * ::limxsdk::msg::hand_msgs::TactileState::minEncodedSize();
        }
      };
    } // namespace hand_msgs
  } // namespace msg
} // namespace limxsdk

#endif // _LIMX_SDK_MSG_HAND_MSGS_TACTILEHANDSTATE_H_
