/**
 * @file TactileState.h
 *
 * @brief Generated mirror of the mros `hand_msgs/TactileState` message.
 *
 * THIS FILE IS GENERATED BY tools/limxsdk-gen/limxsdk_gen.py - DO NOT EDIT.
 * Regenerate it instead of patching it; hand edits are lost on the next run.
 *
 * © [2025] LimX Dynamics Technology Co., Ltd. All rights reserved.
 */

#ifndef _LIMX_SDK_MSG_HAND_MSGS_TACTILESTATE_H_
#define _LIMX_SDK_MSG_HAND_MSGS_TACTILESTATE_H_

#include <array>
#include <cstddef>
#include <cstdint>
#include <string>
#include <vector>

#include "limxsdk/codec/codec.h"
#include "limxsdk/msg/std_msgs/Header.h"

namespace limxsdk
{
  namespace msg
  {
    namespace hand_msgs
    {
      /// @brief Mirror of the mros `hand_msgs/TactileState` message.
      struct TactileState
      {
        static constexpr const char *TYPE = "hand_msgs/TactileState";
        static constexpr const char *MD5 = "b8b0b952da0486df66b2e68584d4b3c2";

        /// @brief ROS concatenated definition, as reported by mros.
        static const char *definition() { return "std_msgs/Header header\nstring[] names\nfloat32[] normal_force\nfloat32[] tangential_force\nfloat32[] direction_angle\nuint32[] approximate_value\nuint16[] tactile_state\n================================================================================\nMSG: std_msgs/Header\nuint32 seq\ntime stamp\nstring frame_id\n"; }

        ::limxsdk::msg::std_msgs::Header header;
        std::vector<std::string> names;
        std::vector<float> normal_force;
        std::vector<float> tangential_force;
        std::vector<float> direction_angle;
        std::vector<uint32_t> approximate_value;
        std::vector<uint16_t> tactile_state;

        /// @brief Decode one frame; false means discard the whole message.
        bool decode(::limxsdk::codec::Reader &reader)
        {
          if (!header.decode(reader))
          {
            return false;
          }
          if (!reader.readValueArray(names, 4))
          {
            return false;
          }
          if (!reader.readPodArray(normal_force))
          {
            return false;
          }
          if (!reader.readPodArray(tangential_force))
          {
            return false;
          }
          if (!reader.readPodArray(direction_angle))
          {
            return false;
          }
          if (!reader.readPodArray(approximate_value))
          {
            return false;
          }
          if (!reader.readPodArray(tactile_state))
          {
            return false;
          }
          return !reader.failed();
        }

        /// @brief Encode into a buffer of at least encodedSize() bytes.
        bool encode(::limxsdk::codec::Writer &writer) const
        {
          if (!header.encode(writer))
          {
            return false;
          }
          if (!writer.writeValueArray(names))
          {
            return false;
          }
          if (!writer.writePodArray(normal_force))
          {
            return false;
          }
          if (!writer.writePodArray(tangential_force))
          {
            return false;
          }
          if (!writer.writePodArray(direction_angle))
          {
            return false;
          }
          if (!writer.writePodArray(approximate_value))
          {
            return false;
          }
          if (!writer.writePodArray(tactile_state))
          {
            return false;
          }
          return !writer.failed();
        }

        /// @brief Exact number of bytes encode() will write.
        std::size_t encodedSize() const
        {
          std::size_t total = 24;
          total += header.encodedSize();
          total += ::limxsdk::codec::arraySize(names);
          total += normal_force.size() * 4;
          total += tangential_force.size() * 4;
          total += direction_angle.size() * 4;
          total += approximate_value.size() * 4;
          total += tactile_state.size() * 2;
          return total;
        }

        /// @brief Smallest possible encoding, used to reject bogus array lengths.
        static std::size_t minEncodedSize()
        {
          return 24 + ::limxsdk::msg::std_msgs::Header::minEncodedSize();
        }
      };
    } // namespace hand_msgs
  } // namespace msg
} // namespace limxsdk

#endif // _LIMX_SDK_MSG_HAND_MSGS_TACTILESTATE_H_
