// Copyright (c) 2025, AgiBot Inc.
// All rights reserved.

#include <fstream>
#include <sstream>

std::stringstream stream;

constexpr int max_args_count = 50;

int main()
{
  stream << R"(/**
 * \note This document is generated by the program. Please do not modify it.
 */

#pragma once

#include "./count.h"

/**
 * \brief Concatenating multiple names into a new name.
 */
#define AIMRTE_CONCAT(...) AIMRTE_DETAILS_CONCAT_CALLER(AIMRTE_DETAILS_CONCAT_, AIMRTE_COUNT_ARGS(__VA_ARGS__))(__VA_ARGS__)


// A helper function ensures that the x- and y-parameters are fully expanded before the splice is performed.
#define AIMRTE_DETAILS_CONCAT(x, y)        x##y
#define AIMRTE_DETAILS_CONCAT_CALLER(x, y) AIMRTE_DETAILS_CONCAT(x, y)

// Macro implementations with different number of parameters
#define AIMRTE_DETAILS_CONCAT_2(x, y)    AIMRTE_DETAILS_CONCAT_CALLER(x, y)
)";

  for (int i = 3; i < max_args_count; ++i) {
    stream
      << "#define AIMRTE_DETAILS_CONCAT_" << i << "(x, ...) "
      << "AIMRTE_DETAILS_CONCAT_CALLER(x, AIMRTE_DETAILS_CONCAT_" << i - 1 << "(__VA_ARGS__))"
      << std::endl;
  }

  std::ofstream file("macro-gen-concat.txt");
  file << stream.str() << std::endl;

  return 0;
}
