"""Go2 的速度跟踪**算法变体数值表**（族级 Skills 的数据面）。

族级实现：`adapters/mjlab/kits/quadruped_kit/skills/velocity/{variants,runner,profile}.py`。
本模块只有**数据**：九种变体的逐项源配方数值（`VariantSpec`）、共享的地形配方
（`VariantTerrain`）与 runner 侧数值/算法符号（`VariantRunnerProfile`）。

数值出处：本机型源配方（`00_resources/LeggedGym-Ex` 的 go2 CTS/TS 族 + `00_resources/
HIMLoco` + DreamWaQ 移植版），与 `registry/porting_references.json` 的登记一致；
2026-09-24 移植核对确认"对 LLoco 逐值相符"。本表只承载数值，不承载机制 ——
机制（装哪些观测组、换哪些核、动作项换实现）全部在族级 `variants.py`。

命名口径：`kind` = profile 的算法变体名（`cts` / `amp_cts` / `ts` / `amp_ts` /
`ts_student` / `amp_ts_student` / `him` / `dreamwaq` / `amp_dreamwaq`）。
"""

from __future__ import annotations

import math

from mjlab.terrains.config import (
    discrete_obstacles,
    hf_pyramid_slope,
    pyramid_stairs,
    pyramid_stairs_inv,
    random_rough,
)

from adapters.mjlab.kits.quadruped_kit.skills.velocity.profile import (
    VariantRunnerProfile,
    VariantSpec,
    VariantTerrain,
)

#: 九种变体的源地形配方（五类地块，逐变体只差边界宽度）。
VARIANT_TERRAIN = VariantTerrain(
    size=(8.0, 8.0),
    num_rows=10,
    num_cols=20,
    curriculum=True,
    add_lights=True,
    border_width=25.0,
    sub_terrains={
        "smooth_slope": hf_pyramid_slope(
            proportion=0.15, slope_range=(0.0, 0.4), platform_width=3.0, border_width=1.0
        ),
        "rough_slope": random_rough(
            proportion=0.15, noise_range=(0.02, 0.10), noise_step=0.02, border_width=1.0
        ),
        "stairs_up": pyramid_stairs(
            proportion=0.30,
            step_height_range=(0.0, 0.1),
            step_width=0.31,
            platform_width=3.0,
            border_width=1.0,
        ),
        "stairs_down": pyramid_stairs_inv(
            proportion=0.30,
            step_height_range=(0.0, 0.1),
            step_width=0.31,
            platform_width=3.0,
            border_width=1.0,
        ),
        "discrete": discrete_obstacles(
            proportion=0.10,
            obstacle_width_range=(0.3, 1.0),
            obstacle_height_range=(0.05, 0.25),
            num_obstacles=40,
            border_width=1.0,
        ),
    },
)

#: 九种变体共用的复位档（源实现逐 kind 同值）。
_RESET_POSE_RANGE = {
    "x": (-1.0, 1.0),
    "y": (-1.0, 1.0),
    "z": (0.0, 0.0),
    "yaw": (0.0, 0.0),
}
_RESET_VELOCITY_RANGE = {
    "x": (-0.5, 0.5),
    "y": (-0.5, 0.5),
    "z": (-0.5, 0.5),
    "roll": (-0.5, 0.5),
    "pitch": (-0.5, 0.5),
    "yaw": (-0.5, 0.5),
}
#: 源观测契约的足序：源实现按 `(1, 0, 3, 2)` 重排共享传感器槽位，
#: 等价于"本族的足序 = FR, FL, RR, RL"（见族级 `source_foot_contact_bits`）。
_CONTACT_ORDER = ("FR", "FL", "RR", "RL")

_STUDENT_KINDS = ("ts_student", "amp_ts_student")

#: 变体 → 逐项数值（**唯一真值**；族级机制按这些字段装配）。
VARIANT_SPECS: dict[str, VariantSpec] = {
    "cts": VariantSpec(
        family="cts",
        amp=False,
        contact_match="geom",
        reset_scale_range=(0.9, 1.1),
        reset_pose_range=_RESET_POSE_RANGE,
        reset_velocity_range=_RESET_VELOCITY_RANGE,
        terrain_border_width=70.0,
        clip_rewards_to_positive=False,
        hip_preload_by_leg={},
        encoder_bias_range=(-0.035, 0.035),
        geom_friction_range=(0.2, 1.0),
        com_extent=0.05,
        base_mass_range=(-1.0, 5.0),
        link_mass_range=(0.8, 1.2),
        pd_gain_range=(0.9, 1.1),
        torque_multiplier_range=(0.9, 1.1),
        push_interval_s=4.0,
        push_linear=0.4,
        push_angular=0.6,
        history_frame_count=6,
        contact_order=_CONTACT_ORDER,
        dof_pos_noise=0.01,
        ang_vel_noise=0.2,
        track_sigma=0.25,
        tracking_linear_weight=1.5,
        tracking_angular_weight=0.75,
        orientation_weight=-0.2,
        angular_velocity_xy_weight=-0.05,
        linear_velocity_z_weight=-1.0,
        base_height_weight=-2.0,
        base_height_target=0.4,
        torque_weight=-1.0e-4,
        joint_acceleration_weight=-2.5e-7,
        action_smoothness_weight=-0.01,
        dof_pos_limits_weight=-2.0,
        action_rate_weight=-0.01,
        collision_weight=-1.0,
        collision_groups=("thigh", "shank", "trunk"),
        foot_clearance_weight=-0.5,
        foot_clearance_target=-0.20,
        stumble_weight=-0.5,
        air_time_weight=0.0,
        air_time_offset=0.5,
        hip_position_weight=None,
        rear_hip_limit_weight=None,
        rear_hip_limit_bound=0.4,
        command_resample_s=8.0,
        lin_vel_y_range=(-1.0, 1.0),
        yaw_range=(-1.0, 1.0),
        command_min_lin_norm=0.1,
        zero_command_prob=0.0,
        zero_xy_prob=0.0,
        drop_command_curriculum=False,
        broadphase="sap_segmented",
        nconmax=35,
    ),
    "amp_cts": VariantSpec(
        family="cts",
        amp=True,
        contact_match="geom",
        reset_scale_range=(0.9, 1.1),
        reset_pose_range=_RESET_POSE_RANGE,
        reset_velocity_range=_RESET_VELOCITY_RANGE,
        terrain_border_width=70.0,
        clip_rewards_to_positive=True,
        hip_preload_by_leg={"FL": -0.1, "FR": 0.1, "RL": -0.1, "RR": 0.1},
        encoder_bias_range=(-0.035, 0.035),
        geom_friction_range=(0.2, 1.0),
        com_extent=0.05,
        base_mass_range=(-1.0, 5.0),
        link_mass_range=(0.8, 1.2),
        pd_gain_range=(0.9, 1.1),
        torque_multiplier_range=(0.9, 1.1),
        push_interval_s=4.0,
        push_linear=0.4,
        push_angular=0.6,
        history_frame_count=6,
        contact_order=_CONTACT_ORDER,
        dof_pos_noise=0.01,
        ang_vel_noise=0.2,
        track_sigma=0.25,
        tracking_linear_weight=1.0,
        tracking_angular_weight=0.5,
        orientation_weight=-0.2,
        angular_velocity_xy_weight=-0.05,
        linear_velocity_z_weight=-2.0,
        base_height_weight=-2.0,
        base_height_target=0.4,
        torque_weight=-1.0e-5,
        joint_acceleration_weight=-2.5e-7,
        action_smoothness_weight=-0.01,
        dof_pos_limits_weight=-2.0,
        action_rate_weight=-0.01,
        collision_weight=-1.0,
        collision_groups=("thigh", "shank"),
        foot_clearance_weight=-0.5,
        foot_clearance_target=-0.25,
        stumble_weight=-0.5,
        air_time_weight=1.0,
        air_time_offset=0.5,
        hip_position_weight=-0.1,
        rear_hip_limit_weight=None,
        rear_hip_limit_bound=0.4,
        command_resample_s=10.0,
        lin_vel_y_range=(-0.65, 0.65),
        yaw_range=(-1.0, 1.0),
        command_min_lin_norm=0.2,
        zero_command_prob=0.0,
        zero_xy_prob=0.0,
        drop_command_curriculum=False,
        broadphase="sap_segmented",
        nconmax=35,
    ),
    "dreamwaq": VariantSpec(
        family="dreamwaq",
        amp=False,
        contact_match="geom",
        reset_scale_range=(0.5, 1.5),
        reset_pose_range=_RESET_POSE_RANGE,
        reset_velocity_range=_RESET_VELOCITY_RANGE,
        terrain_border_width=25.0,
        clip_rewards_to_positive=False,
        hip_preload_by_leg={},
        encoder_bias_range=(-0.035, 0.035),
        geom_friction_range=(0.2, 1.25),
        com_extent=0.05,
        base_mass_range=(-1.0, 5.0),
        link_mass_range=(0.8, 1.2),
        pd_gain_range=(0.9, 1.1),
        torque_multiplier_range=(0.9, 1.1),
        push_interval_s=4.0,
        push_linear=0.4,
        push_angular=0.6,
        history_frame_count=6,
        contact_order=_CONTACT_ORDER,
        dof_pos_noise=0.02,
        ang_vel_noise=0.2,
        track_sigma=0.25,
        tracking_linear_weight=1.5,
        tracking_angular_weight=0.75,
        orientation_weight=-0.2,
        angular_velocity_xy_weight=-0.05,
        linear_velocity_z_weight=-1.0,
        base_height_weight=-5.0,
        base_height_target=0.4,
        torque_weight=-1.0e-4,
        joint_acceleration_weight=-2.5e-7,
        action_smoothness_weight=-0.01,
        dof_pos_limits_weight=-2.0,
        action_rate_weight=-0.01,
        collision_weight=-1.0,
        collision_groups=("thigh", "shank", "trunk"),
        foot_clearance_weight=-0.5,
        foot_clearance_target=-0.20,
        stumble_weight=-0.5,
        air_time_weight=0.0,
        air_time_offset=0.5,
        hip_position_weight=None,
        rear_hip_limit_weight=None,
        rear_hip_limit_bound=0.4,
        command_resample_s=10.0,
        lin_vel_y_range=(-1.0, 1.0),
        yaw_range=(-1.0, 1.0),
        command_min_lin_norm=0.2,
        zero_command_prob=0.0,
        zero_xy_prob=0.0,
        drop_command_curriculum=False,
        broadphase="sap_segmented",
        nconmax=35,
    ),
    "amp_dreamwaq": VariantSpec(
        family="dreamwaq",
        amp=True,
        contact_match="geom",
        reset_scale_range=(0.5, 1.5),
        reset_pose_range=_RESET_POSE_RANGE,
        reset_velocity_range=_RESET_VELOCITY_RANGE,
        terrain_border_width=25.0,
        clip_rewards_to_positive=False,
        hip_preload_by_leg={},
        encoder_bias_range=(-0.035, 0.035),
        geom_friction_range=(0.2, 1.25),
        com_extent=0.05,
        base_mass_range=(-1.0, 5.0),
        link_mass_range=(0.8, 1.2),
        pd_gain_range=(0.9, 1.1),
        torque_multiplier_range=(0.9, 1.1),
        push_interval_s=4.0,
        push_linear=0.4,
        push_angular=0.6,
        history_frame_count=6,
        contact_order=_CONTACT_ORDER,
        dof_pos_noise=0.01,
        ang_vel_noise=0.2,
        track_sigma=0.25,
        tracking_linear_weight=1.0,
        tracking_angular_weight=0.5,
        orientation_weight=-0.2,
        angular_velocity_xy_weight=-0.05,
        linear_velocity_z_weight=-2.0,
        base_height_weight=-5.0,
        # 唯一把目标高度压到 0.35 的变体（源 AMP-DreamWaQ 配方）。
        base_height_target=0.35,
        torque_weight=-1.0e-5,
        joint_acceleration_weight=-2.5e-7,
        action_smoothness_weight=-0.01,
        dof_pos_limits_weight=-2.0,
        action_rate_weight=-0.01,
        collision_weight=-1.0,
        collision_groups=("thigh", "shank", "trunk"),
        foot_clearance_weight=-0.5,
        foot_clearance_target=-0.20,
        stumble_weight=-0.5,
        air_time_weight=0.0,
        air_time_offset=0.5,
        hip_position_weight=None,
        rear_hip_limit_weight=-1.0,
        rear_hip_limit_bound=0.4,
        command_resample_s=10.0,
        lin_vel_y_range=(-0.6, 0.6),
        yaw_range=(-1.0, 1.0),
        command_min_lin_norm=0.2,
        zero_command_prob=0.0,
        zero_xy_prob=0.0,
        drop_command_curriculum=False,
        broadphase="sap_segmented",
        nconmax=35,
    ),
    "him": VariantSpec(
        family="him",
        amp=False,
        contact_match="geom",
        reset_scale_range=(0.5, 1.5),
        reset_pose_range=_RESET_POSE_RANGE,
        reset_velocity_range=_RESET_VELOCITY_RANGE,
        terrain_border_width=25.0,
        clip_rewards_to_positive=False,
        hip_preload_by_leg={},
        encoder_bias_range=(-0.035, 0.035),
        geom_friction_range=(0.2, 1.25),
        com_extent=0.05,
        base_mass_range=(-1.0, 5.0),
        link_mass_range=(0.8, 1.2),
        pd_gain_range=(0.9, 1.1),
        torque_multiplier_range=(0.9, 1.1),
        push_interval_s=4.0,
        push_linear=0.4,
        push_angular=0.6,
        # HIM 的 actor 观测就是堆叠历史本身，不另装前序帧组。
        history_frame_count=None,
        contact_order=_CONTACT_ORDER,
        dof_pos_noise=0.01,
        ang_vel_noise=0.2,
        track_sigma=0.25,
        tracking_linear_weight=1.5,
        tracking_angular_weight=0.75,
        orientation_weight=-0.2,
        angular_velocity_xy_weight=-0.05,
        linear_velocity_z_weight=-1.0,
        base_height_weight=-2.0,
        base_height_target=0.4,
        torque_weight=-1.0e-4,
        joint_acceleration_weight=-2.5e-7,
        action_smoothness_weight=-0.01,
        dof_pos_limits_weight=0.0,
        action_rate_weight=-0.01,
        collision_weight=-1.0,
        collision_groups=("thigh", "shank", "trunk"),
        foot_clearance_weight=-0.5,
        foot_clearance_target=-0.20,
        stumble_weight=-0.5,
        air_time_weight=0.0,
        air_time_offset=0.5,
        hip_position_weight=None,
        rear_hip_limit_weight=None,
        rear_hip_limit_bound=0.4,
        command_resample_s=10.0,
        lin_vel_y_range=(-1.0, 1.0),
        yaw_range=(-math.pi, math.pi),
        command_min_lin_norm=0.2,
        zero_command_prob=0.0,
        zero_xy_prob=0.0,
        drop_command_curriculum=False,
        broadphase="sap_segmented",
        nconmax=35,
    ),
    "ts": VariantSpec(
        family="ts",
        amp=False,
        contact_match="geom",
        reset_scale_range=(0.5, 1.5),
        reset_pose_range=_RESET_POSE_RANGE,
        reset_velocity_range=_RESET_VELOCITY_RANGE,
        terrain_border_width=25.0,
        clip_rewards_to_positive=False,
        hip_preload_by_leg={},
        encoder_bias_range=(-0.035, 0.035),
        geom_friction_range=(0.05, 3.0),
        com_extent=0.1,
        base_mass_range=(-1.0, 5.0),
        link_mass_range=(0.8, 1.2),
        pd_gain_range=(0.8, 1.2),
        torque_multiplier_range=(0.8, 1.2),
        push_interval_s=8.0,
        push_linear=1.0,
        push_angular=1.0,
        history_frame_count=5,
        contact_order=_CONTACT_ORDER,
        dof_pos_noise=0.01,
        ang_vel_noise=0.2,
        track_sigma=0.25,
        tracking_linear_weight=1.0,
        tracking_angular_weight=0.5,
        orientation_weight=-0.2,
        angular_velocity_xy_weight=-0.05,
        linear_velocity_z_weight=-2.0,
        base_height_weight=-1.0,
        base_height_target=0.4,
        torque_weight=-1.0e-5,
        joint_acceleration_weight=-2.5e-7,
        # 教师档把嵌套的奖励尺度类整个换掉 ⇒ 继承来的该项不存在（权重 0）。
        action_smoothness_weight=0.0,
        dof_pos_limits_weight=0.0,
        action_rate_weight=-0.01,
        collision_weight=-0.5,
        collision_groups=("thigh", "shank", "trunk"),
        # 教师档同样撤掉净空惩罚；学生档继承基座的 -0.01。
        foot_clearance_weight=0.0,
        foot_clearance_target=-0.20,
        stumble_weight=-0.5,
        air_time_weight=0.0,
        air_time_offset=0.5,
        hip_position_weight=None,
        rear_hip_limit_weight=None,
        rear_hip_limit_bound=0.4,
        command_resample_s=10.0,
        lin_vel_y_range=(-0.6, 0.6),
        yaw_range=(-math.pi, math.pi),
        command_min_lin_norm=0.2,
        zero_command_prob=0.05,
        zero_xy_prob=0.05,
        drop_command_curriculum=False,
        broadphase="sap_segmented",
        nconmax=35,
    ),
    "amp_ts": VariantSpec(
        family="ts",
        amp=True,
        contact_match="geom",
        reset_scale_range=(0.5, 1.5),
        reset_pose_range=_RESET_POSE_RANGE,
        reset_velocity_range=_RESET_VELOCITY_RANGE,
        terrain_border_width=25.0,
        clip_rewards_to_positive=False,
        hip_preload_by_leg={},
        encoder_bias_range=(-0.035, 0.035),
        geom_friction_range=(0.05, 3.0),
        com_extent=0.1,
        base_mass_range=(-1.0, 5.0),
        link_mass_range=(0.8, 1.2),
        pd_gain_range=(0.8, 1.2),
        torque_multiplier_range=(0.8, 1.2),
        push_interval_s=8.0,
        push_linear=1.0,
        push_angular=1.0,
        history_frame_count=5,
        contact_order=_CONTACT_ORDER,
        dof_pos_noise=0.01,
        ang_vel_noise=0.2,
        track_sigma=0.25,
        tracking_linear_weight=1.0,
        tracking_angular_weight=0.5,
        orientation_weight=-0.2,
        angular_velocity_xy_weight=-0.05,
        linear_velocity_z_weight=-2.0,
        base_height_weight=-5.0,
        base_height_target=0.4,
        torque_weight=-1.0e-4,
        joint_acceleration_weight=-2.5e-7,
        action_smoothness_weight=0.0,
        dof_pos_limits_weight=-2.0,
        action_rate_weight=-0.01,
        collision_weight=-1.0,
        collision_groups=("thigh", "shank", "trunk"),
        foot_clearance_weight=0.0,
        foot_clearance_target=-0.20,
        stumble_weight=-0.5,
        air_time_weight=0.0,
        air_time_offset=0.5,
        hip_position_weight=None,
        rear_hip_limit_weight=None,
        rear_hip_limit_bound=0.4,
        command_resample_s=10.0,
        lin_vel_y_range=(-0.6, 0.6),
        yaw_range=(-math.pi, math.pi),
        command_min_lin_norm=0.2,
        zero_command_prob=0.05,
        zero_xy_prob=0.05,
        drop_command_curriculum=False,
        broadphase="sap_segmented",
        nconmax=35,
    ),
    "ts_student": VariantSpec(
        family="ts",
        amp=False,
        contact_match="geom",
        reset_scale_range=(0.5, 1.5),
        reset_pose_range=_RESET_POSE_RANGE,
        reset_velocity_range=_RESET_VELOCITY_RANGE,
        terrain_border_width=25.0,
        clip_rewards_to_positive=False,
        hip_preload_by_leg={},
        encoder_bias_range=(-0.035, 0.035),
        geom_friction_range=(0.05, 3.0),
        com_extent=0.1,
        base_mass_range=(-1.0, 5.0),
        link_mass_range=(0.8, 1.2),
        pd_gain_range=(0.8, 1.2),
        torque_multiplier_range=(0.8, 1.2),
        push_interval_s=8.0,
        push_linear=1.0,
        push_angular=1.0,
        history_frame_count=5,
        contact_order=_CONTACT_ORDER,
        dof_pos_noise=0.03,
        ang_vel_noise=0.3,
        track_sigma=0.25,
        tracking_linear_weight=1.0,
        tracking_angular_weight=0.5,
        orientation_weight=-0.2,
        angular_velocity_xy_weight=-0.05,
        linear_velocity_z_weight=-2.0,
        base_height_weight=-1.0,
        base_height_target=0.4,
        torque_weight=-1.0e-5,
        joint_acceleration_weight=-2.5e-7,
        # 学生档继承源基类的动作平滑尺度，且没有 stumble 项。
        action_smoothness_weight=-0.005,
        dof_pos_limits_weight=0.0,
        action_rate_weight=-0.01,
        collision_weight=-1.0,
        collision_groups=("thigh", "shank", "trunk"),
        foot_clearance_weight=-0.01,
        foot_clearance_target=0.09,
        stumble_weight=0.0,
        air_time_weight=1.0,
        air_time_offset=0.3,
        hip_position_weight=None,
        rear_hip_limit_weight=None,
        rear_hip_limit_bound=0.4,
        command_resample_s=10.0,
        lin_vel_y_range=(-0.5, 0.5),
        yaw_range=(-math.pi, math.pi),
        command_min_lin_norm=0.2,
        zero_command_prob=0.05,
        zero_xy_prob=0.05,
        drop_command_curriculum=True,
        broadphase="sap_segmented",
        nconmax=35,
    ),
    "amp_ts_student": VariantSpec(
        family="ts",
        amp=True,
        contact_match="geom",
        reset_scale_range=(0.5, 1.5),
        reset_pose_range=_RESET_POSE_RANGE,
        reset_velocity_range=_RESET_VELOCITY_RANGE,
        terrain_border_width=25.0,
        clip_rewards_to_positive=False,
        hip_preload_by_leg={},
        encoder_bias_range=(-0.035, 0.035),
        geom_friction_range=(0.05, 3.0),
        com_extent=0.1,
        base_mass_range=(-1.0, 5.0),
        link_mass_range=(0.8, 1.2),
        pd_gain_range=(0.8, 1.2),
        torque_multiplier_range=(0.8, 1.2),
        push_interval_s=8.0,
        push_linear=1.0,
        push_angular=1.0,
        history_frame_count=5,
        contact_order=_CONTACT_ORDER,
        dof_pos_noise=0.03,
        ang_vel_noise=0.3,
        track_sigma=0.25,
        tracking_linear_weight=1.0,
        tracking_angular_weight=0.5,
        orientation_weight=-0.2,
        angular_velocity_xy_weight=-0.05,
        linear_velocity_z_weight=-2.0,
        base_height_weight=-1.0,
        base_height_target=0.4,
        torque_weight=-1.0e-5,
        joint_acceleration_weight=-2.5e-7,
        action_smoothness_weight=-0.005,
        dof_pos_limits_weight=0.0,
        action_rate_weight=-0.01,
        collision_weight=-1.0,
        collision_groups=("thigh", "shank", "trunk"),
        foot_clearance_weight=-0.01,
        foot_clearance_target=0.09,
        stumble_weight=0.0,
        air_time_weight=1.0,
        air_time_offset=0.3,
        hip_position_weight=None,
        rear_hip_limit_weight=None,
        rear_hip_limit_bound=0.4,
        command_resample_s=10.0,
        lin_vel_y_range=(-0.5, 0.5),
        yaw_range=(-math.pi, math.pi),
        command_min_lin_norm=0.2,
        zero_command_prob=0.05,
        zero_xy_prob=0.05,
        drop_command_curriculum=True,
        broadphase="sap_segmented",
        nconmax=35,
    ),
}

#: 源把 std 下限按各关节**完整位置幅值**折算：`0.05 × (upper - lower)`，
#: 顺序 = 契约 `action.joint_order`（髋/大腿/小腿 × 四腿）。
_MIN_STD_PER_JOINT = (0.10472, 0.253075, 0.094247) * 4

#: 变体 → runner 数值与**算法侧符号**（符号串与原实现逐字一致：它们是
#: `rsl_rl.utils.resolve_callable` 吃的入口声明，本仓的 `local_tasks.learning.*`
#: 是已上移算法类的再导出 shim）。
VARIANT_RUNNERS: dict[str, VariantRunnerProfile] = {
    "cts": VariantRunnerProfile(
        experiment_name="go2_cts",
        learning_rate=1.0e-3,
        max_iterations=20_000,
        save_interval=500,
        seed=1,
        algorithm_class="local_tasks.learning.algorithms.CtsPPO",
        actor_class="local_tasks.learning.models.CtsActorModel",
        critic_class="local_tasks.learning.models.CtsCriticModel",
    ),
    "amp_cts": VariantRunnerProfile(
        experiment_name="go2_amp_cts",
        learning_rate=1.0e-3,
        max_iterations=20_000,
        save_interval=500,
        seed=1,
        algorithm_class="local_tasks.learning.algorithms.AmpCtsPPO",
        actor_class="local_tasks.learning.models.CtsActorModel",
        critic_class="local_tasks.learning.models.CtsCriticModel",
        distribution_class="local_tasks.learning.models.Go2ClampedGaussianDistribution",
        min_std=_MIN_STD_PER_JOINT,
    ),
    "ts": VariantRunnerProfile(
        experiment_name="go2_ts",
        learning_rate=1.0e-5,
        max_iterations=20_000,
        save_interval=500,
        seed=5,
        algorithm_class="local_tasks.learning.algorithms.Go2AuxiliaryPPO",
        actor_class="local_tasks.learning.models.TeacherActorModel",
        distribution_class="local_tasks.learning.models.Go2ClampedGaussianDistribution",
        min_std=_MIN_STD_PER_JOINT,
    ),
    "amp_ts": VariantRunnerProfile(
        experiment_name="go2_amp_ts",
        learning_rate=1.0e-5,
        max_iterations=20_000,
        save_interval=500,
        seed=5,
        algorithm_class="local_tasks.learning.algorithms.AmpPPO",
        actor_class="local_tasks.learning.models.TeacherActorModel",
        distribution_class="local_tasks.learning.models.Go2ClampedGaussianDistribution",
        min_std=_MIN_STD_PER_JOINT,
    ),
    "ts_student": VariantRunnerProfile(
        experiment_name="go2_ts_student",
        learning_rate=1.0e-3,
        max_iterations=20_000,
        save_interval=500,
        seed=5,
        algorithm_class="local_tasks.learning.algorithms.TeacherStudentPPO",
        actor_class="local_tasks.learning.models.StudentActorModel",
        distribution_class="local_tasks.learning.models.Go2ClampedGaussianDistribution",
        min_std=_MIN_STD_PER_JOINT,
        # 源学生 LSTM 按 50 帧的更长 rollout 训练。
        num_steps_per_env=50,
    ),
    "him": VariantRunnerProfile(
        experiment_name="go2_him",
        learning_rate=1.0e-3,
        max_iterations=20_000,
        save_interval=100,
        seed=1,
        algorithm_class="adapters.mjlab.algorithms.him.algorithms:HimPPO",
        actor_class="adapters.mjlab.algorithms.him.models:HIMActorModel",
        critic_class="rsl_rl.models.mlp_model:MLPModel",
    ),
}

#: 变体 → 族级 runner 类（profile 的 `entrypoints.runner_class` 指向包内薄委托）。
DISTILLATION_KINDS = _STUDENT_KINDS

__all__ = [
    "DISTILLATION_KINDS",
    "VARIANT_RUNNERS",
    "VARIANT_SPECS",
    "VARIANT_TERRAIN",
]
