package(default_visibility = ["//visibility:public"])

cc_library(
    name = "aimrt_pkg_c_interface",
    hdrs = glob(["*.h"]),
    deps = [
        "//src/interface/aimrt_module_c_interface",
    ],
    includes = [".."],
)
