package(default_visibility = ["//visibility:public"])

cc_library(
    name = "setting",
    hdrs = glob(["**/*.h"]),
    srcs = glob(["**/*.cpp"]),
    deps = [
        "//src/ctx",
        "@nlohmann_json//:json",
    ],
)
