package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "demo1",
    srcs = ["main.cpp"],
    deps = [
        "//aimdk/protocol/demo:demo_service_rpc",
        "//src/program",
        "//aimdk/protocol/demo:demo_channel_cc_proto",
    ],
)
