package(default_visibility = ["//visibility:public"])

filegroup(
    name = "demo_cfg_filegroup",
    srcs = [
        "cfg_demo1_config.yaml",
        "cfg_demo2_config.yaml",
        "cfg_demo3_config.yaml",
        "cfg_demo5_config.yaml",
    ],
)
