/**
 * @file IMUData.h
 *
 * @brief Generated mirror of the mros `controller_msgs/IMUData` message.
 *
 * THIS FILE IS GENERATED BY tools/limxsdk-gen/limxsdk_gen.py - DO NOT EDIT.
 * Regenerate it instead of patching it; hand edits are lost on the next run.
 *
 * © [2025] LimX Dynamics Technology Co., Ltd. All rights reserved.
 */

#ifndef _LIMX_SDK_MSG_CONTROLLER_MSGS_IMUDATA_H_
#define _LIMX_SDK_MSG_CONTROLLER_MSGS_IMUDATA_H_

#include <array>
#include <cstddef>
#include <cstdint>
#include <string>
#include <vector>

#include "limxsdk/codec/codec.h"
#include "limxsdk/msg/std_msgs/Header.h"

namespace limxsdk
{
  namespace msg
  {
    namespace controller_msgs
    {
      /// @brief Mirror of the mros `controller_msgs/IMUData` message.
      struct IMUData
      {
        static constexpr const char *TYPE = "controller_msgs/IMUData";
        static constexpr const char *MD5 = "4713fbd787897a0c91a2a31aa6a873c6";

        /// @brief ROS concatenated definition, as reported by mros.
        static const char *definition() { return "std_msgs/Header header\nuint64 imustamp\nuint32 status\nfloat64[3] euler\nfloat64[4] quat\nfloat64[3] acc\nfloat64[3] gyro\n================================================================================\nMSG: std_msgs/Header\nuint32 seq\ntime stamp\nstring frame_id\n"; }

        ::limxsdk::msg::std_msgs::Header header;
        uint64_t imustamp = 0;
        uint32_t status = 0;
        std::array<double, 3> euler;
        std::array<double, 4> quat;
        std::array<double, 3> acc;
        std::array<double, 3> gyro;

        /// @brief Decode one frame; false means discard the whole message.
        bool decode(::limxsdk::codec::Reader &reader)
        {
          if (!header.decode(reader))
          {
            return false;
          }
          if (!reader.read(imustamp))
          {
            return false;
          }
          if (!reader.read(status))
          {
            return false;
          }
          if (!reader.readPodArrayFixed(euler))
          {
            return false;
          }
          if (!reader.readPodArrayFixed(quat))
          {
            return false;
          }
          if (!reader.readPodArrayFixed(acc))
          {
            return false;
          }
          if (!reader.readPodArrayFixed(gyro))
          {
            return false;
          }
          return !reader.failed();
        }

        /// @brief Encode into a buffer of at least encodedSize() bytes.
        bool encode(::limxsdk::codec::Writer &writer) const
        {
          if (!header.encode(writer))
          {
            return false;
          }
          if (!writer.write(imustamp))
          {
            return false;
          }
          if (!writer.write(status))
          {
            return false;
          }
          if (!writer.writePodArrayFixed(euler))
          {
            return false;
          }
          if (!writer.writePodArrayFixed(quat))
          {
            return false;
          }
          if (!writer.writePodArrayFixed(acc))
          {
            return false;
          }
          if (!writer.writePodArrayFixed(gyro))
          {
            return false;
          }
          return !writer.failed();
        }

        /// @brief Exact number of bytes encode() will write.
        std::size_t encodedSize() const
        {
          std::size_t total = 116;
          total += header.encodedSize();
          return total;
        }

        /// @brief Smallest possible encoding, used to reject bogus array lengths.
        static std::size_t minEncodedSize()
        {
          return 116 + ::limxsdk::msg::std_msgs::Header::minEncodedSize();
        }
      };
    } // namespace controller_msgs
  } // namespace msg
} // namespace limxsdk

#endif // _LIMX_SDK_MSG_CONTROLLER_MSGS_IMUDATA_H_
