/**
 * @file JointState.h
 *
 * @brief Generated mirror of the mros `controller_msgs/JointState` message.
 *
 * THIS FILE IS GENERATED BY tools/limxsdk-gen/limxsdk_gen.py - DO NOT EDIT.
 * Regenerate it instead of patching it; hand edits are lost on the next run.
 *
 * © [2025] LimX Dynamics Technology Co., Ltd. All rights reserved.
 */

#ifndef _LIMX_SDK_MSG_CONTROLLER_MSGS_JOINTSTATE_H_
#define _LIMX_SDK_MSG_CONTROLLER_MSGS_JOINTSTATE_H_

#include <array>
#include <cstddef>
#include <cstdint>
#include <string>
#include <vector>

#include "limxsdk/codec/codec.h"
#include "limxsdk/msg/std_msgs/Header.h"

namespace limxsdk
{
  namespace msg
  {
    namespace controller_msgs
    {
      /// @brief Mirror of the mros `controller_msgs/JointState` message.
      struct JointState
      {
        static constexpr const char *TYPE = "controller_msgs/JointState";
        static constexpr const char *MD5 = "0d1d997e638ba23ee585b83a152596fe";

        /// @brief ROS concatenated definition, as reported by mros.
        static const char *definition() { return "std_msgs/Header header\nstring[] names\nfloat32[] q\nfloat32[] v\nfloat32[] vd\nfloat32[] tau\nuint32 na\n================================================================================\nMSG: std_msgs/Header\nuint32 seq\ntime stamp\nstring frame_id\n"; }

        ::limxsdk::msg::std_msgs::Header header;
        std::vector<std::string> names;
        std::vector<float> q;
        std::vector<float> v;
        std::vector<float> vd;
        std::vector<float> tau;
        uint32_t na = 0;

        /// @brief Decode one frame; false means discard the whole message.
        bool decode(::limxsdk::codec::Reader &reader)
        {
          if (!header.decode(reader))
          {
            return false;
          }
          if (!reader.readValueArray(names, 4))
          {
            return false;
          }
          if (!reader.readPodArray(q))
          {
            return false;
          }
          if (!reader.readPodArray(v))
          {
            return false;
          }
          if (!reader.readPodArray(vd))
          {
            return false;
          }
          if (!reader.readPodArray(tau))
          {
            return false;
          }
          if (!reader.read(na))
          {
            return false;
          }
          return !reader.failed();
        }

        /// @brief Encode into a buffer of at least encodedSize() bytes.
        bool encode(::limxsdk::codec::Writer &writer) const
        {
          if (!header.encode(writer))
          {
            return false;
          }
          if (!writer.writeValueArray(names))
          {
            return false;
          }
          if (!writer.writePodArray(q))
          {
            return false;
          }
          if (!writer.writePodArray(v))
          {
            return false;
          }
          if (!writer.writePodArray(vd))
          {
            return false;
          }
          if (!writer.writePodArray(tau))
          {
            return false;
          }
          if (!writer.write(na))
          {
            return false;
          }
          return !writer.failed();
        }

        /// @brief Exact number of bytes encode() will write.
        std::size_t encodedSize() const
        {
          std::size_t total = 24;
          total += header.encodedSize();
          total += ::limxsdk::codec::arraySize(names);
          total += q.size() * 4;
          total += v.size() * 4;
          total += vd.size() * 4;
          total += tau.size() * 4;
          return total;
        }

        /// @brief Smallest possible encoding, used to reject bogus array lengths.
        static std::size_t minEncodedSize()
        {
          return 24 + ::limxsdk::msg::std_msgs::Header::minEncodedSize();
        }
      };
    } // namespace controller_msgs
  } // namespace msg
} // namespace limxsdk

#endif // _LIMX_SDK_MSG_CONTROLLER_MSGS_JOINTSTATE_H_
