/**
 * @file RCASCmdStampedWL.h
 *
 * @brief Generated mirror of the mros `controller_msgs/RCASCmdStampedWL` message.
 *
 * THIS FILE IS GENERATED BY tools/limxsdk-gen/limxsdk_gen.py - DO NOT EDIT.
 * Regenerate it instead of patching it; hand edits are lost on the next run.
 *
 * © [2025] LimX Dynamics Technology Co., Ltd. All rights reserved.
 */

#ifndef _LIMX_SDK_MSG_CONTROLLER_MSGS_RCASCMDSTAMPEDWL_H_
#define _LIMX_SDK_MSG_CONTROLLER_MSGS_RCASCMDSTAMPEDWL_H_

#include <array>
#include <cstddef>
#include <cstdint>
#include <string>
#include <vector>

#include "limxsdk/codec/codec.h"
#include "limxsdk/msg/std_msgs/Header.h"

namespace limxsdk
{
  namespace msg
  {
    namespace controller_msgs
    {
      /// @brief Mirror of the mros `controller_msgs/RCASCmdStampedWL` message.
      struct RCASCmdStampedWL
      {
        static constexpr const char *TYPE = "controller_msgs/RCASCmdStampedWL";
        static constexpr const char *MD5 = "0197db14404650210fcc1b048026a46d";
        static constexpr int8_t GAIT_STAND = 1;
        static constexpr int8_t GAIT_TROT_WALK = 2;
        static constexpr int8_t GAIT_STAND_TROT = 3;

        /// @brief ROS concatenated definition, as reported by mros.
        static const char *definition() { return "std_msgs/Header header\nfloat64 vx\nfloat64 vy\nfloat64 w\nfloat64 roll\nfloat64 pitch\nfloat64 yaw\nfloat64 height\nint8 GAIT_STAND = 1\nint8 GAIT_TROT_WALK = 2\nint8 GAIT_STAND_TROT = 3\nint8 gait\n================================================================================\nMSG: std_msgs/Header\nuint32 seq\ntime stamp\nstring frame_id\n"; }

        ::limxsdk::msg::std_msgs::Header header;
        double vx = 0;
        double vy = 0;
        double w = 0;
        double roll = 0;
        double pitch = 0;
        double yaw = 0;
        double height = 0;
        int8_t gait = 0;

        /// @brief Decode one frame; false means discard the whole message.
        bool decode(::limxsdk::codec::Reader &reader)
        {
          if (!header.decode(reader))
          {
            return false;
          }
          if (!reader.read(vx))
          {
            return false;
          }
          if (!reader.read(vy))
          {
            return false;
          }
          if (!reader.read(w))
          {
            return false;
          }
          if (!reader.read(roll))
          {
            return false;
          }
          if (!reader.read(pitch))
          {
            return false;
          }
          if (!reader.read(yaw))
          {
            return false;
          }
          if (!reader.read(height))
          {
            return false;
          }
          if (!reader.read(gait))
          {
            return false;
          }
          return !reader.failed();
        }

        /// @brief Encode into a buffer of at least encodedSize() bytes.
        bool encode(::limxsdk::codec::Writer &writer) const
        {
          if (!header.encode(writer))
          {
            return false;
          }
          if (!writer.write(vx))
          {
            return false;
          }
          if (!writer.write(vy))
          {
            return false;
          }
          if (!writer.write(w))
          {
            return false;
          }
          if (!writer.write(roll))
          {
            return false;
          }
          if (!writer.write(pitch))
          {
            return false;
          }
          if (!writer.write(yaw))
          {
            return false;
          }
          if (!writer.write(height))
          {
            return false;
          }
          if (!writer.write(gait))
          {
            return false;
          }
          return !writer.failed();
        }

        /// @brief Exact number of bytes encode() will write.
        std::size_t encodedSize() const
        {
          std::size_t total = 57;
          total += header.encodedSize();
          return total;
        }

        /// @brief Smallest possible encoding, used to reject bogus array lengths.
        static std::size_t minEncodedSize()
        {
          return 57 + ::limxsdk::msg::std_msgs::Header::minEncodedSize();
        }
      };
    } // namespace controller_msgs
  } // namespace msg
} // namespace limxsdk

#endif // _LIMX_SDK_MSG_CONTROLLER_MSGS_RCASCMDSTAMPEDWL_H_
