/**
 * @file RCASCmdStamped.h
 *
 * @brief Generated mirror of the mros `controller_msgs/RCASCmdStamped` message.
 *
 * THIS FILE IS GENERATED BY tools/limxsdk-gen/limxsdk_gen.py - DO NOT EDIT.
 * Regenerate it instead of patching it; hand edits are lost on the next run.
 *
 * © [2025] LimX Dynamics Technology Co., Ltd. All rights reserved.
 */

#ifndef _LIMX_SDK_MSG_CONTROLLER_MSGS_RCASCMDSTAMPED_H_
#define _LIMX_SDK_MSG_CONTROLLER_MSGS_RCASCMDSTAMPED_H_

#include <array>
#include <cstddef>
#include <cstdint>
#include <string>
#include <vector>

#include "limxsdk/codec/codec.h"
#include "limxsdk/msg/std_msgs/Header.h"

namespace limxsdk
{
  namespace msg
  {
    namespace controller_msgs
    {
      /// @brief Mirror of the mros `controller_msgs/RCASCmdStamped` message.
      struct RCASCmdStamped
      {
        static constexpr const char *TYPE = "controller_msgs/RCASCmdStamped";
        static constexpr const char *MD5 = "55583299a0c731b2fc59553bae330532";
        static constexpr int8_t GAIT_NONE = 0;
        static constexpr int8_t GAIT_STAND = 1;
        static constexpr int8_t GAIT_TROT_WALK = 2;

        /// @brief ROS concatenated definition, as reported by mros.
        static const char *definition() { return "std_msgs/Header header\nfloat64 vx\nfloat64 vy\nfloat64 w\nint8 GAIT_NONE = 0\nint8 GAIT_STAND = 1\nint8 GAIT_TROT_WALK = 2\nint8 gait\n================================================================================\nMSG: std_msgs/Header\nuint32 seq\ntime stamp\nstring frame_id\n"; }

        ::limxsdk::msg::std_msgs::Header header;
        double vx = 0;
        double vy = 0;
        double w = 0;
        int8_t gait = 0;

        /// @brief Decode one frame; false means discard the whole message.
        bool decode(::limxsdk::codec::Reader &reader)
        {
          if (!header.decode(reader))
          {
            return false;
          }
          if (!reader.read(vx))
          {
            return false;
          }
          if (!reader.read(vy))
          {
            return false;
          }
          if (!reader.read(w))
          {
            return false;
          }
          if (!reader.read(gait))
          {
            return false;
          }
          return !reader.failed();
        }

        /// @brief Encode into a buffer of at least encodedSize() bytes.
        bool encode(::limxsdk::codec::Writer &writer) const
        {
          if (!header.encode(writer))
          {
            return false;
          }
          if (!writer.write(vx))
          {
            return false;
          }
          if (!writer.write(vy))
          {
            return false;
          }
          if (!writer.write(w))
          {
            return false;
          }
          if (!writer.write(gait))
          {
            return false;
          }
          return !writer.failed();
        }

        /// @brief Exact number of bytes encode() will write.
        std::size_t encodedSize() const
        {
          std::size_t total = 25;
          total += header.encodedSize();
          return total;
        }

        /// @brief Smallest possible encoding, used to reject bogus array lengths.
        static std::size_t minEncodedSize()
        {
          return 25 + ::limxsdk::msg::std_msgs::Header::minEncodedSize();
        }
      };
    } // namespace controller_msgs
  } // namespace msg
} // namespace limxsdk

#endif // _LIMX_SDK_MSG_CONTROLLER_MSGS_RCASCMDSTAMPED_H_
