/**
 * @file RCCmdStamped.h
 *
 * @brief Generated mirror of the mros `controller_msgs/RCCmdStamped` message.
 *
 * THIS FILE IS GENERATED BY tools/limxsdk-gen/limxsdk_gen.py - DO NOT EDIT.
 * Regenerate it instead of patching it; hand edits are lost on the next run.
 *
 * © [2025] LimX Dynamics Technology Co., Ltd. All rights reserved.
 */

#ifndef _LIMX_SDK_MSG_CONTROLLER_MSGS_RCCMDSTAMPED_H_
#define _LIMX_SDK_MSG_CONTROLLER_MSGS_RCCMDSTAMPED_H_

#include <array>
#include <cstddef>
#include <cstdint>
#include <string>
#include <vector>

#include "limxsdk/codec/codec.h"
#include "limxsdk/msg/std_msgs/Header.h"

namespace limxsdk
{
  namespace msg
  {
    namespace controller_msgs
    {
      /// @brief Mirror of the mros `controller_msgs/RCCmdStamped` message.
      struct RCCmdStamped
      {
        static constexpr const char *TYPE = "controller_msgs/RCCmdStamped";
        static constexpr const char *MD5 = "cb92ef9a5f527c5fa02b4b5096689a38";
        static constexpr int8_t IDLE_MODE = 0;
        static constexpr int8_t NAVI_MODE = 1;
        static constexpr int8_t USER_MODE = 2;
        static constexpr int8_t MANUAL_MODE = 3;
        static constexpr int8_t GAIT_NONE = 0;
        static constexpr int8_t GAIT_STAND = 1;
        static constexpr int8_t GAIT_TROT_WALK = 2;
        static constexpr int8_t VISION_NONE = 0;
        static constexpr int8_t NO_VISION = 1;
        static constexpr int8_t LOCAL_VISION = 2;
        static constexpr int8_t VISION = 3;
        static constexpr int8_t NAVI_NONE = 0;
        static constexpr int8_t NAVI_GROUND = 1;
        static constexpr int8_t NAVI_UP_FORWARD = 2;
        static constexpr int8_t NAVI_DOWN_BACKWARD = 3;
        static constexpr int8_t NAVI_PRE_UP = 4;
        static constexpr int8_t NAVI_PRE_DOWN = 5;
        static constexpr int8_t NAVI_LAND_STAIR = 6;
        static constexpr int8_t NAVI_PAUSE = 7;
        static constexpr int8_t NAVI_ROTATE = 8;
        static constexpr int8_t NAVI_DOWN_FORWARD = 9;

        /// @brief ROS concatenated definition, as reported by mros.
        static const char *definition() { return "std_msgs/Header header\nint8 IDLE_MODE    = 0\nint8 NAVI_MODE    = 1\nint8 USER_MODE    = 2\nint8 MANUAL_MODE  = 3\nint8 mode\nfloat64 vx\nfloat64 vy\nfloat64 w\nbool damping\nint8 GAIT_NONE = 0\nint8 GAIT_STAND = 1\nint8 GAIT_TROT_WALK = 2\nint8 gait\nbool standup\nbool sitdown\nint8 VISION_NONE  = 0\nint8 NO_VISION   = 1\nint8 LOCAL_VISION = 2\nint8 VISION       = 3\nint8 vision_mode\nbool stairup\nbool stairdown\nint8 NAVI_NONE = 0\nint8 NAVI_GROUND = 1\nint8 NAVI_UP_FORWARD = 2\nint8 NAVI_DOWN_BACKWARD = 3\nint8 NAVI_PRE_UP = 4\nint8 NAVI_PRE_DOWN = 5\nint8 NAVI_LAND_STAIR = 6\nint8 NAVI_PAUSE = 7\nint8 NAVI_ROTATE = 8\nint8 NAVI_DOWN_FORWARD = 9\nint8 navi_mode\nbool swing_test\nbool cruise\n================================================================================\nMSG: std_msgs/Header\nuint32 seq\ntime stamp\nstring frame_id\n"; }

        ::limxsdk::msg::std_msgs::Header header;
        int8_t mode = 0;
        double vx = 0;
        double vy = 0;
        double w = 0;
        uint8_t damping = 0;
        int8_t gait = 0;
        uint8_t standup = 0;
        uint8_t sitdown = 0;
        int8_t vision_mode = 0;
        uint8_t stairup = 0;
        uint8_t stairdown = 0;
        int8_t navi_mode = 0;
        uint8_t swing_test = 0;
        uint8_t cruise = 0;

        /// @brief Decode one frame; false means discard the whole message.
        bool decode(::limxsdk::codec::Reader &reader)
        {
          if (!header.decode(reader))
          {
            return false;
          }
          if (!reader.read(mode))
          {
            return false;
          }
          if (!reader.read(vx))
          {
            return false;
          }
          if (!reader.read(vy))
          {
            return false;
          }
          if (!reader.read(w))
          {
            return false;
          }
          if (!reader.read(damping))
          {
            return false;
          }
          if (!reader.read(gait))
          {
            return false;
          }
          if (!reader.read(standup))
          {
            return false;
          }
          if (!reader.read(sitdown))
          {
            return false;
          }
          if (!reader.read(vision_mode))
          {
            return false;
          }
          if (!reader.read(stairup))
          {
            return false;
          }
          if (!reader.read(stairdown))
          {
            return false;
          }
          if (!reader.read(navi_mode))
          {
            return false;
          }
          if (!reader.read(swing_test))
          {
            return false;
          }
          if (!reader.read(cruise))
          {
            return false;
          }
          return !reader.failed();
        }

        /// @brief Encode into a buffer of at least encodedSize() bytes.
        bool encode(::limxsdk::codec::Writer &writer) const
        {
          if (!header.encode(writer))
          {
            return false;
          }
          if (!writer.write(mode))
          {
            return false;
          }
          if (!writer.write(vx))
          {
            return false;
          }
          if (!writer.write(vy))
          {
            return false;
          }
          if (!writer.write(w))
          {
            return false;
          }
          if (!writer.write(damping))
          {
            return false;
          }
          if (!writer.write(gait))
          {
            return false;
          }
          if (!writer.write(standup))
          {
            return false;
          }
          if (!writer.write(sitdown))
          {
            return false;
          }
          if (!writer.write(vision_mode))
          {
            return false;
          }
          if (!writer.write(stairup))
          {
            return false;
          }
          if (!writer.write(stairdown))
          {
            return false;
          }
          if (!writer.write(navi_mode))
          {
            return false;
          }
          if (!writer.write(swing_test))
          {
            return false;
          }
          if (!writer.write(cruise))
          {
            return false;
          }
          return !writer.failed();
        }

        /// @brief Exact number of bytes encode() will write.
        std::size_t encodedSize() const
        {
          std::size_t total = 35;
          total += header.encodedSize();
          return total;
        }

        /// @brief Smallest possible encoding, used to reject bogus array lengths.
        static std::size_t minEncodedSize()
        {
          return 35 + ::limxsdk::msg::std_msgs::Header::minEncodedSize();
        }
      };
    } // namespace controller_msgs
  } // namespace msg
} // namespace limxsdk

#endif // _LIMX_SDK_MSG_CONTROLLER_MSGS_RCCMDSTAMPED_H_
