package(
    default_visibility = ["//visibility:public"],
)

exports_files([
    "PoseCommand.msg",
    "PoseCommands.msg",
    "PoseState.msg",
    "PoseStates.msg",
    "TorqSensorState.msg",
])

filegroup(
    name = "ros2_files",
    srcs = glob([
        "*.msg",
    ]),
)
