package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "demo2",
    srcs = ["main.cpp"],
    deps = [
        "//:aimrte",
        "//aimdk/protocol/demo:demo_service_rpc",
        "//aimdk/protocol/demo:demo_channel_cc_proto",
    ],
)
