FSM:
  _: # enabled fsms
    Passive:
      id: 1
    FixStand:
      id: 2
      type: Fix
    Velocity:
      id: 3
      type: RLBase
    BFM_goal:
      id: 4
      type: BFM
    BFM_reward:
      id: 5
      type: BFM
    BFM_tracking:
      id: 6
      type: BFM

  Passive:
    transitions: 
      FixStand: LT + up.on_pressed
    mode: [
      1,1,1,1,1,1,
      1,1,1,1,1,1,
      1,1,1,
      1,1,1,1,1,1,1,
      1,1,1,1,1,1,1,
    ]
    kd: [
      3,3,3,3,3,3,
      3,3,3,3,3,3,
      3,3,3,
      3,3,3,3,3,3,3,  
      3,3,3,3,3,3,3,  
    ]
  FixStand:
    transitions: 
      Passive: LT + B.on_pressed
      Velocity: RB + X.on_pressed
      BFM_goal: RT + Y.on_pressed
      BFM_reward: RT + A.on_pressed
      BFM_tracking: RT + X.on_pressed
    kp: [
      100., 100., 100., 150., 40., 40.,
      100., 100., 100., 150., 40., 40.,
      200,200,200,
      40,40,40,40,40,40,40,
      40,40,40,40,40,40,40,
    ]
    kd: [
      2,2,2,4,2,2,
      2,2,2,4,2,2,
      5,5,5,
      10,10,10,10,10,10,10,
      10,10,10,10,10,10,10,
    ]
    ts: [0, 3]
    qs: [
      [],
      [ -0.1, 0,0,0.3,-0.2,0,
        -0.1, 0,0,0.3,-0.2,0,
        0,0,0,
        0, 0.25,0,0.97,0.15, 0,0,
        0, -0.25,0,0.97,-0.15, 0,0
      ]
    ]
  Velocity:
    transitions: 
      Passive: LT + B.on_pressed
      BFM_goal: RT + Y.on_pressed
      BFM_reward: RT + A.on_pressed
      BFM_tracking: RT + X.on_pressed
    policy_dir: ../../../logs/g1/velocity/g1_moe_cts_v0.0.5_seed1_50k
  BFM_goal:
    transitions: 
      Passive: LT + B.on_pressed
      Velocity: RB + X.on_pressed
      BFM_reward: RT + A.on_pressed
      BFM_tracking: RT + X.on_pressed
    policy_dir: ../../../logs/g1/bfm/official
    deploy_yaml: param/deploy.yaml
    onnx_model: exported/FBcprAuxModel.onnx
    onnx_tensorrt: false
    onnx_cuda: true
    onnx_cuda_device: 0
    waist_kalman:
      enabled: true
      joint_indices: [12, 13, 14]
      process_noise: 1.0e-4
      measurement_noise: 2.0e-3
      initial_error_cov: 1.0e-2
    task_type: goal
    latent_file: goal_inference/goal_reaching.npz
    gamepad_map:
      next_latent: Y.on_pressed
      reset_state: X.on_pressed
    goal:
      selected_goals: [
        fallAndGetUp1_subject4_2193, 
        # walk3_subject3_9044,
        # fallAndGetUp1_subject4_3350, 
        # fallAndGetUp1_subject4_2230, 
        dance1_subject3_505, 
        # dance1_subject3_4024, 
        # dance1_subject3_4700, 
        # dance2_subject4_700, 
        fight1_subject3_5559, 
        # fight1_subject3_10229, 
        # fight1_subject3_11981, 
        # dance1_subject2_1150, 
        # dance1_subject2_2877, 
        # walk2_subject1_2588, 
        fallAndGetUp1_subject4_2193, 
      ]
  BFM_reward:
    transitions: 
      Passive: LT + B.on_pressed
      Velocity: RB + X.on_pressed
      BFM_goal: RT + Y.on_pressed
      BFM_tracking: RT + X.on_pressed
    policy_dir: ../../../logs/g1/bfm/official
    deploy_yaml: param/deploy.yaml
    onnx_model: exported/FBcprAuxModel.onnx
    onnx_tensorrt: false
    onnx_cuda: true
    onnx_cuda_device: 0
    waist_kalman:
      enabled: true
      joint_indices: [12, 13, 14]
      process_noise: 1.0e-4
      measurement_noise: 2.0e-3
      initial_error_cov: 1.0e-2
    task_type: reward
    latent_file: reward_inference/reward_locomotion.npz
    gamepad_map:
      start_motion: B.on_pressed
      next_latent: Y.on_pressed
      reset_state: X.on_pressed
    reward:
      selected_rewards_filter_z:
        - reward: move-ego-0-0
          z_ids: [0]
        - reward: move-ego-low0.6-0-0.7
          z_ids: [0]
        - reward: move-ego-90-0.3
          z_ids: [0]
        - reward: spin-arms-5-l-l
          z_ids: [0]
  BFM_tracking:
    transitions: 
      Passive: LT + B.on_pressed
      Velocity: RB + X.on_pressed
      BFM_goal: RT + Y.on_pressed
      BFM_reward: RT + A.on_pressed
    policy_dir: ../../../logs/g1/bfm/official
    deploy_yaml: param/deploy.yaml
    onnx_model: exported/FBcprAuxModel.onnx
    onnx_tensorrt: false
    onnx_cuda: true
    onnx_cuda_device: 0
    waist_kalman:
      enabled: true
      joint_indices: [12, 13, 14]
      process_noise: 1.0e-4
      measurement_noise: 2.0e-3
      initial_error_cov: 1.0e-2
    task_type: tracking
    latent_file: tracking_inference/zs_walking.npz
    gamepad_map:
      start_motion: B.on_pressed
      next_latent: Y.on_pressed
      reset_state: X.on_pressed
    tracking:
      key: data
      start: 0
      end: 2000
      stop: 0
      gamma: 0.8
      window_size: 3
