package(
    default_visibility = ["//visibility:public"],
)

exports_files([
    "GetLatestBall.srv",
])

filegroup(
    name = "ros2_files",
    srcs = glob(
        [
            "**",
        ],
        exclude = ["BUILD"],
    ),
)
