from ..base_model import BaseModel
from ..base import BaseConfig


class BaseEvalConfig(BaseConfig):
    """Abstract class for evaluation configurations."""

    # Turn on/off the generation of videos. Video generation does not need to be used or even implemented.
    generate_videos: bool = False
    # If videos are generated, the video_dir will be created (converted to Path)
    videos_dir: str = "videos"
    # Prefix that will be used to create the videos names. It will be concat with the video suffix auto-generated by the eval.
    video_name_prefix: str = "unknown_agent"

    @classmethod
    def requires_replay_buffer(self):
        return False


def extract_model(agent_or_model):
    if isinstance(agent_or_model, BaseModel):  # If this is a raw model
        return agent_or_model
    return agent_or_model._model  # If this is an agent