package(
    default_visibility = ["//visibility:public"],
)

exports_files([
    "BenchmarkMessage.msg",
    "BenchmarkSignal.msg",
    "BenchmarkStatus.msg",
    "RosTestData.msg",
    "RosTestMsg.msg",
])
