/**
 * @file Joy.h
 *
 * @brief Generated mirror of the mros `sensor_msgs/Joy` message.
 *
 * THIS FILE IS GENERATED BY tools/limxsdk-gen/limxsdk_gen.py - DO NOT EDIT.
 * Regenerate it instead of patching it; hand edits are lost on the next run.
 *
 * © [2025] LimX Dynamics Technology Co., Ltd. All rights reserved.
 */

#ifndef _LIMX_SDK_MSG_SENSOR_MSGS_JOY_H_
#define _LIMX_SDK_MSG_SENSOR_MSGS_JOY_H_

#include <array>
#include <cstddef>
#include <cstdint>
#include <string>
#include <vector>

#include "limxsdk/codec/codec.h"
#include "limxsdk/msg/std_msgs/Header.h"

namespace limxsdk
{
  namespace msg
  {
    namespace sensor_msgs
    {
      /// @brief Mirror of the mros `sensor_msgs/Joy` message.
      struct Joy
      {
        static constexpr const char *TYPE = "sensor_msgs/Joy";
        static constexpr const char *MD5 = "5a9ea5f83505693b71e785041e67a8bb";

        /// @brief ROS concatenated definition, as reported by mros.
        static const char *definition() { return "std_msgs/Header header\nfloat32[] axes\nint32[] buttons\n================================================================================\nMSG: std_msgs/Header\nuint32 seq\ntime stamp\nstring frame_id\n"; }

        ::limxsdk::msg::std_msgs::Header header;
        std::vector<float> axes;
        std::vector<int32_t> buttons;

        /// @brief Decode one frame; false means discard the whole message.
        bool decode(::limxsdk::codec::Reader &reader)
        {
          if (!header.decode(reader))
          {
            return false;
          }
          if (!reader.readPodArray(axes))
          {
            return false;
          }
          if (!reader.readPodArray(buttons))
          {
            return false;
          }
          return !reader.failed();
        }

        /// @brief Encode into a buffer of at least encodedSize() bytes.
        bool encode(::limxsdk::codec::Writer &writer) const
        {
          if (!header.encode(writer))
          {
            return false;
          }
          if (!writer.writePodArray(axes))
          {
            return false;
          }
          if (!writer.writePodArray(buttons))
          {
            return false;
          }
          return !writer.failed();
        }

        /// @brief Exact number of bytes encode() will write.
        std::size_t encodedSize() const
        {
          std::size_t total = 8;
          total += header.encodedSize();
          total += axes.size() * 4;
          total += buttons.size() * 4;
          return total;
        }

        /// @brief Smallest possible encoding, used to reject bogus array lengths.
        static std::size_t minEncodedSize()
        {
          return 8 + ::limxsdk::msg::std_msgs::Header::minEncodedSize();
        }
      };
    } // namespace sensor_msgs
  } // namespace msg
} // namespace limxsdk

#endif // _LIMX_SDK_MSG_SENSOR_MSGS_JOY_H_
