/**
 * @file JoyH16.h
 *
 * @brief Generated mirror of the mros `sensor_msgs/JoyH16` message.
 *
 * THIS FILE IS GENERATED BY tools/limxsdk-gen/limxsdk_gen.py - DO NOT EDIT.
 * Regenerate it instead of patching it; hand edits are lost on the next run.
 *
 * © [2025] LimX Dynamics Technology Co., Ltd. All rights reserved.
 */

#ifndef _LIMX_SDK_MSG_SENSOR_MSGS_JOYH16_H_
#define _LIMX_SDK_MSG_SENSOR_MSGS_JOYH16_H_

#include <array>
#include <cstddef>
#include <cstdint>
#include <string>
#include <vector>

#include "limxsdk/codec/codec.h"
#include "limxsdk/msg/std_msgs/Header.h"

namespace limxsdk
{
  namespace msg
  {
    namespace sensor_msgs
    {
      /// @brief Mirror of the mros `sensor_msgs/JoyH16` message.
      struct JoyH16
      {
        static constexpr const char *TYPE = "sensor_msgs/JoyH16";
        static constexpr const char *MD5 = "c65ce9204f033c8f40297b950337e517";
        static constexpr uint16_t SW_UP = 1950;
        static constexpr uint16_t SW_MID = 1500;
        static constexpr uint16_t SW_DOWN = 1050;
        static constexpr uint16_t AXES_MAX = 1950;
        static constexpr uint16_t AXES_MID = 1500;
        static constexpr uint16_t AXES_MIN = 1050;

        /// @brief ROS concatenated definition, as reported by mros.
        static const char *definition() { return "std_msgs/Header header\nuint16[] axes\nuint16[] sws\nuint16[] auxs\nbool[] buttons\nuint16 SW_UP   = 1950\nuint16 SW_MID  = 1500\nuint16 SW_DOWN = 1050\nuint16 AXES_MAX = 1950\nuint16 AXES_MID = 1500\nuint16 AXES_MIN = 1050\n================================================================================\nMSG: std_msgs/Header\nuint32 seq\ntime stamp\nstring frame_id\n"; }

        ::limxsdk::msg::std_msgs::Header header;
        std::vector<uint16_t> axes;
        std::vector<uint16_t> sws;
        std::vector<uint16_t> auxs;
        std::vector<uint8_t> buttons;

        /// @brief Decode one frame; false means discard the whole message.
        bool decode(::limxsdk::codec::Reader &reader)
        {
          if (!header.decode(reader))
          {
            return false;
          }
          if (!reader.readPodArray(axes))
          {
            return false;
          }
          if (!reader.readPodArray(sws))
          {
            return false;
          }
          if (!reader.readPodArray(auxs))
          {
            return false;
          }
          if (!reader.readPodArray(buttons))
          {
            return false;
          }
          return !reader.failed();
        }

        /// @brief Encode into a buffer of at least encodedSize() bytes.
        bool encode(::limxsdk::codec::Writer &writer) const
        {
          if (!header.encode(writer))
          {
            return false;
          }
          if (!writer.writePodArray(axes))
          {
            return false;
          }
          if (!writer.writePodArray(sws))
          {
            return false;
          }
          if (!writer.writePodArray(auxs))
          {
            return false;
          }
          if (!writer.writePodArray(buttons))
          {
            return false;
          }
          return !writer.failed();
        }

        /// @brief Exact number of bytes encode() will write.
        std::size_t encodedSize() const
        {
          std::size_t total = 16;
          total += header.encodedSize();
          total += axes.size() * 2;
          total += sws.size() * 2;
          total += auxs.size() * 2;
          total += buttons.size() * 1;
          return total;
        }

        /// @brief Smallest possible encoding, used to reject bogus array lengths.
        static std::size_t minEncodedSize()
        {
          return 16 + ::limxsdk::msg::std_msgs::Header::minEncodedSize();
        }
      };
    } // namespace sensor_msgs
  } // namespace msg
} // namespace limxsdk

#endif // _LIMX_SDK_MSG_SENSOR_MSGS_JOYH16_H_
