/**
 * @file MapMetaData.h
 *
 * @brief Generated mirror of the mros `nav_msgs/MapMetaData` message.
 *
 * THIS FILE IS GENERATED BY tools/limxsdk-gen/limxsdk_gen.py - DO NOT EDIT.
 * Regenerate it instead of patching it; hand edits are lost on the next run.
 *
 * © [2025] LimX Dynamics Technology Co., Ltd. All rights reserved.
 */

#ifndef _LIMX_SDK_MSG_NAV_MSGS_MAPMETADATA_H_
#define _LIMX_SDK_MSG_NAV_MSGS_MAPMETADATA_H_

#include <array>
#include <cstddef>
#include <cstdint>
#include <string>
#include <vector>

#include "limxsdk/codec/codec.h"
#include "limxsdk/msg/geometry_msgs/Pose.h"

namespace limxsdk
{
  namespace msg
  {
    namespace nav_msgs
    {
      /// @brief Mirror of the mros `nav_msgs/MapMetaData` message.
      struct MapMetaData
      {
        static constexpr const char *TYPE = "nav_msgs/MapMetaData";
        static constexpr const char *MD5 = "10cfc8a2818024d3248802c00c95f11b";

        /// @brief ROS concatenated definition, as reported by mros.
        static const char *definition() { return "time map_load_time\nfloat32 resolution\nuint32 width\nuint32 height\ngeometry_msgs/Pose origin\n================================================================================\nMSG: geometry_msgs/Pose\ngeometry_msgs/Point position\ngeometry_msgs/Quaternion orientation\n================================================================================\nMSG: geometry_msgs/Point\nfloat64 x\nfloat64 y\nfloat64 z\n================================================================================\nMSG: geometry_msgs/Quaternion\nfloat64 x\nfloat64 y\nfloat64 z\nfloat64 w\n"; }

        ::limxsdk::codec::Time map_load_time;
        float resolution = 0;
        uint32_t width = 0;
        uint32_t height = 0;
        ::limxsdk::msg::geometry_msgs::Pose origin;

        /// @brief Decode one frame; false means discard the whole message.
        bool decode(::limxsdk::codec::Reader &reader)
        {
          if (!reader.read(map_load_time))
          {
            return false;
          }
          if (!reader.read(resolution))
          {
            return false;
          }
          if (!reader.read(width))
          {
            return false;
          }
          if (!reader.read(height))
          {
            return false;
          }
          if (!origin.decode(reader))
          {
            return false;
          }
          return !reader.failed();
        }

        /// @brief Encode into a buffer of at least encodedSize() bytes.
        bool encode(::limxsdk::codec::Writer &writer) const
        {
          if (!writer.write(map_load_time))
          {
            return false;
          }
          if (!writer.write(resolution))
          {
            return false;
          }
          if (!writer.write(width))
          {
            return false;
          }
          if (!writer.write(height))
          {
            return false;
          }
          if (!origin.encode(writer))
          {
            return false;
          }
          return !writer.failed();
        }

        /// @brief Exact number of bytes encode() will write.
        std::size_t encodedSize() const
        {
          std::size_t total = 20;
          total += origin.encodedSize();
          return total;
        }

        /// @brief Smallest possible encoding, used to reject bogus array lengths.
        static std::size_t minEncodedSize()
        {
          return 20 + ::limxsdk::msg::geometry_msgs::Pose::minEncodedSize();
        }
      };
    } // namespace nav_msgs
  } // namespace msg
} // namespace limxsdk

#endif // _LIMX_SDK_MSG_NAV_MSGS_MAPMETADATA_H_
