/**
 * @file OccupancyGrid.h
 *
 * @brief Generated mirror of the mros `nav_msgs/OccupancyGrid` message.
 *
 * THIS FILE IS GENERATED BY tools/limxsdk-gen/limxsdk_gen.py - DO NOT EDIT.
 * Regenerate it instead of patching it; hand edits are lost on the next run.
 *
 * © [2025] LimX Dynamics Technology Co., Ltd. All rights reserved.
 */

#ifndef _LIMX_SDK_MSG_NAV_MSGS_OCCUPANCYGRID_H_
#define _LIMX_SDK_MSG_NAV_MSGS_OCCUPANCYGRID_H_

#include <array>
#include <cstddef>
#include <cstdint>
#include <string>
#include <vector>

#include "limxsdk/codec/codec.h"
#include "limxsdk/msg/nav_msgs/MapMetaData.h"
#include "limxsdk/msg/std_msgs/Header.h"

namespace limxsdk
{
  namespace msg
  {
    namespace nav_msgs
    {
      /// @brief Mirror of the mros `nav_msgs/OccupancyGrid` message.
      struct OccupancyGrid
      {
        static constexpr const char *TYPE = "nav_msgs/OccupancyGrid";
        static constexpr const char *MD5 = "3381f2d731d4076ec5c71b0759edbe4e";

        /// @brief ROS concatenated definition, as reported by mros.
        static const char *definition() { return "std_msgs/Header header\nnav_msgs/MapMetaData info\nint8[] data\n================================================================================\nMSG: std_msgs/Header\nuint32 seq\ntime stamp\nstring frame_id\n================================================================================\nMSG: nav_msgs/MapMetaData\ntime map_load_time\nfloat32 resolution\nuint32 width\nuint32 height\ngeometry_msgs/Pose origin\n================================================================================\nMSG: geometry_msgs/Pose\ngeometry_msgs/Point position\ngeometry_msgs/Quaternion orientation\n================================================================================\nMSG: geometry_msgs/Point\nfloat64 x\nfloat64 y\nfloat64 z\n================================================================================\nMSG: geometry_msgs/Quaternion\nfloat64 x\nfloat64 y\nfloat64 z\nfloat64 w\n"; }

        ::limxsdk::msg::std_msgs::Header header;
        ::limxsdk::msg::nav_msgs::MapMetaData info;
        std::vector<int8_t> data;

        /// @brief Decode one frame; false means discard the whole message.
        bool decode(::limxsdk::codec::Reader &reader)
        {
          if (!header.decode(reader))
          {
            return false;
          }
          if (!info.decode(reader))
          {
            return false;
          }
          if (!reader.readPodArray(data))
          {
            return false;
          }
          return !reader.failed();
        }

        /// @brief Encode into a buffer of at least encodedSize() bytes.
        bool encode(::limxsdk::codec::Writer &writer) const
        {
          if (!header.encode(writer))
          {
            return false;
          }
          if (!info.encode(writer))
          {
            return false;
          }
          if (!writer.writePodArray(data))
          {
            return false;
          }
          return !writer.failed();
        }

        /// @brief Exact number of bytes encode() will write.
        std::size_t encodedSize() const
        {
          std::size_t total = 4;
          total += header.encodedSize();
          total += info.encodedSize();
          total += data.size() * 1;
          return total;
        }

        /// @brief Smallest possible encoding, used to reject bogus array lengths.
        static std::size_t minEncodedSize()
        {
          return 4 + ::limxsdk::msg::std_msgs::Header::minEncodedSize() + ::limxsdk::msg::nav_msgs::MapMetaData::minEncodedSize();
        }
      };
    } // namespace nav_msgs
  } // namespace msg
} // namespace limxsdk

#endif // _LIMX_SDK_MSG_NAV_MSGS_OCCUPANCYGRID_H_
