/**
 * @file Odometry.h
 *
 * @brief Generated mirror of the mros `nav_msgs/Odometry` message.
 *
 * THIS FILE IS GENERATED BY tools/limxsdk-gen/limxsdk_gen.py - DO NOT EDIT.
 * Regenerate it instead of patching it; hand edits are lost on the next run.
 *
 * © [2025] LimX Dynamics Technology Co., Ltd. All rights reserved.
 */

#ifndef _LIMX_SDK_MSG_NAV_MSGS_ODOMETRY_H_
#define _LIMX_SDK_MSG_NAV_MSGS_ODOMETRY_H_

#include <array>
#include <cstddef>
#include <cstdint>
#include <string>
#include <vector>

#include "limxsdk/codec/codec.h"
#include "limxsdk/msg/geometry_msgs/PoseWithCovariance.h"
#include "limxsdk/msg/geometry_msgs/TwistWithCovariance.h"
#include "limxsdk/msg/std_msgs/Header.h"

namespace limxsdk
{
  namespace msg
  {
    namespace nav_msgs
    {
      /// @brief Mirror of the mros `nav_msgs/Odometry` message.
      struct Odometry
      {
        static constexpr const char *TYPE = "nav_msgs/Odometry";
        static constexpr const char *MD5 = "cd5e73d190d741a2f92e81eda573aca7";

        /// @brief ROS concatenated definition, as reported by mros.
        static const char *definition() { return "std_msgs/Header header\nstring child_frame_id\ngeometry_msgs/PoseWithCovariance pose\ngeometry_msgs/TwistWithCovariance twist\n================================================================================\nMSG: std_msgs/Header\nuint32 seq\ntime stamp\nstring frame_id\n================================================================================\nMSG: geometry_msgs/PoseWithCovariance\ngeometry_msgs/Pose pose\nfloat64[36] covariance\n================================================================================\nMSG: geometry_msgs/TwistWithCovariance\ngeometry_msgs/Twist twist\nfloat64[36] covariance\n================================================================================\nMSG: geometry_msgs/Pose\ngeometry_msgs/Point position\ngeometry_msgs/Quaternion orientation\n================================================================================\nMSG: geometry_msgs/Twist\ngeometry_msgs/Vector3 linear\ngeometry_msgs/Vector3 angular\n================================================================================\nMSG: geometry_msgs/Point\nfloat64 x\nfloat64 y\nfloat64 z\n================================================================================\nMSG: geometry_msgs/Quaternion\nfloat64 x\nfloat64 y\nfloat64 z\nfloat64 w\n================================================================================\nMSG: geometry_msgs/Vector3\nfloat64 x\nfloat64 y\nfloat64 z\n"; }

        ::limxsdk::msg::std_msgs::Header header;
        std::string child_frame_id;
        ::limxsdk::msg::geometry_msgs::PoseWithCovariance pose;
        ::limxsdk::msg::geometry_msgs::TwistWithCovariance twist;

        /// @brief Decode one frame; false means discard the whole message.
        bool decode(::limxsdk::codec::Reader &reader)
        {
          if (!header.decode(reader))
          {
            return false;
          }
          if (!reader.read(child_frame_id))
          {
            return false;
          }
          if (!pose.decode(reader))
          {
            return false;
          }
          if (!twist.decode(reader))
          {
            return false;
          }
          return !reader.failed();
        }

        /// @brief Encode into a buffer of at least encodedSize() bytes.
        bool encode(::limxsdk::codec::Writer &writer) const
        {
          if (!header.encode(writer))
          {
            return false;
          }
          if (!writer.write(child_frame_id))
          {
            return false;
          }
          if (!pose.encode(writer))
          {
            return false;
          }
          if (!twist.encode(writer))
          {
            return false;
          }
          return !writer.failed();
        }

        /// @brief Exact number of bytes encode() will write.
        std::size_t encodedSize() const
        {
          std::size_t total = 4;
          total += header.encodedSize();
          total += child_frame_id.size();
          total += pose.encodedSize();
          total += twist.encodedSize();
          return total;
        }

        /// @brief Smallest possible encoding, used to reject bogus array lengths.
        static std::size_t minEncodedSize()
        {
          return 4 + ::limxsdk::msg::std_msgs::Header::minEncodedSize() + ::limxsdk::msg::geometry_msgs::PoseWithCovariance::minEncodedSize() + ::limxsdk::msg::geometry_msgs::TwistWithCovariance::minEncodedSize();
        }
      };
    } // namespace nav_msgs
  } // namespace msg
} // namespace limxsdk

#endif // _LIMX_SDK_MSG_NAV_MSGS_ODOMETRY_H_
