package(default_visibility = ["//visibility:public"])

filegroup(
    name = "demo_cfg_script",
    srcs = ["run_demo1_module.sh","run_demo2_module.sh","run_demo3_module.sh","run_demo4_module.sh","run_demo5_module.sh"],
)
