package(
    default_visibility = ["//visibility:public"],
)

exports_files([
    "locomotion.proto",
    "mc_adjust.proto",
    "mc_motion_channel.proto",
    "mc_motion_service.proto",
    "motion_param.proto",
    "move.proto",
    "movj.proto",
    "planning.proto",
    "stand.proto",
    "waist.proto",
    "collision.proto",
    "state_notify.proto",
])
