controller_manager:
  ros__parameters:
    update_rate: 100

joint_state_broadcaster:
  ros__parameters:
    update_rate: 50
    type: joint_state_broadcaster/JointStateBroadcaster

position_controller:
  ros__parameters:
    type: forward_command_controller/ForwardCommandController
    interface_name: position
    joints:
      - joint1
      - joint2

gripper_controller:
  ros__parameters:
    type: forward_command_controller/ForwardCommandController
    interface_name: position
    joints:
      - gripper_left_finger_joint

pose_broadcaster:
  ros__parameters:
    type: pose_broadcaster/PoseBroadcaster
    pose_name: pose
    frame_id: ee_link
