package(default_visibility = ["//visibility:public"])

cc_library(
    name = "details",
    srcs = [],
    hdrs = glob(["*.h"]),
    deps = [
        "//src/macro",
        "@aimrt//:libaimrt",
    ],
)
