package(
    default_visibility = ["//visibility:public"],
)

exports_files([
    "hal_power_service.proto",
])

filegroup(
    name = "ros2_files",
    srcs = [
        "CMakeLists.txt",
        'package.xml'
    ],
)
