package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "example-program-app_mode",
    srcs = [
        "main.cpp",
    ],
    deps = [
        "//example/program/common",
        "//src/program/app_mode",
    ],
)
